"""Shared helpers for the paper's figure and table scripts.

Every number a figure or table shows is read from a file of this repository
(paper-dim4/BENCH.md, docs/COMPACT_R3.md, COMPRESSION.md, README.md) by one of these
helpers; nothing is typed into a script.  Output is deterministic: PDF and
SVG metadata carry no timestamps, so a second ``make figures`` reproduces
the bytes.  The layout is that of prism-rs ``paper/prism-suf/figures``.
"""
import csv
import os
import re
import sys
from pathlib import Path

os.environ.setdefault("SOURCE_DATE_EPOCH", "0")

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent
REPO = HERE.parents[1]
DOCS = REPO / "docs"
DATA = HERE / "data"
OUT = HERE / "out"
TABLES = PAPER / "tables"

# One accent colour per implementation, shared with main.tex (\definecolor).
COLORS = {
    "c_ref": "#4C6A92",     # the C reference, broadwell build
    "rs_dim2": "#8FB3DA",   # this crate, dimension 2 (standard and compressed)
    "rs_dim4": "#2A9D8F",   # this crate, dimension 4 (compact)
    "r2": "#D98E2B",        # the round-2 crate (v0.4.31)
    "neutral": "#6B6B6B",
    "light": "#BFBFBF",
}
LABELS = {
    "c_ref": "SQIsign, C reference (broadwell)",
    "rs_dim2": "SQIsign, this crate, dimension 2",
    "rs_dim4": "SQIsign, this crate, dimension 4 (compact)",
    "r2": "SQIsign round 2, crate v0.4.31",
}

matplotlib.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.size": 9,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "svg.hashsalt": "sqisign-rs-dim4",
        "pdf.fonttype": 42,
        "svg.fonttype": "none",
        "axes.titlesize": 9,
        "legend.frameon": False,
        "legend.fontsize": 8,
    }
)


def read(relpath):
    return (REPO / relpath).read_text(encoding="utf-8")


def section(text, heading_regex):
    """The text from the first heading line matching ``heading_regex`` to the
    next heading of the same or higher level."""
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if re.match(heading_regex, line):
            level = len(line) - len(line.lstrip("#"))
            j = i + 1
            while j < len(lines):
                m = re.match(r"^(#+) ", lines[j])
                if m and len(m.group(1)) <= level:
                    break
                j += 1
            return "\n".join(lines[i:j])
    raise KeyError(heading_regex)


def _cells(line):
    inner = line.strip()
    inner = inner[1:] if inner.startswith("|") else inner
    inner = inner[:-1] if inner.endswith("|") else inner
    return [c.strip() for c in inner.split("|")]


def md_table(text, first_cell_regex):
    """Header cells and rows of the first markdown table whose header's
    first cell matches ``first_cell_regex``."""
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("|") and re.search(first_cell_regex, _cells(line)[0]):
            rows = []
            j = i + 2
            while j < len(lines) and lines[j].startswith("|"):
                rows.append(_cells(lines[j]))
                j += 1
            return _cells(line), rows
    raise KeyError(first_cell_regex)


def grab(text, regex, group=1, flags=re.S):
    m = re.search(regex, text, flags)
    if not m:
        raise KeyError(regex)
    return m.group(group)


def num(s):
    s = s.replace("**", "").replace("`", "").replace(" ", "").replace(" ", "").replace(",", "")
    return float(s)


def write_csv(name, header, rows):
    DATA.mkdir(exist_ok=True)
    with open(DATA / name, "w", newline="") as f:
        w = csv.writer(f, lineterminator="\n")
        w.writerow(header)
        for r in rows:
            w.writerow(r)
    return DATA / name


def write_macros(name, pairs, source):
    """A TeX file of \\newcommand lines; macro names may not contain digits."""
    DATA.mkdir(exist_ok=True)
    body = f"% generated by figures/{source}; do not edit\n" + "".join(
        f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in pairs
    )
    (DATA / name).write_text(body, encoding="utf-8")
    print(f"wrote data/{name}", file=sys.stderr)


def save(fig, name):
    OUT.mkdir(exist_ok=True)
    fig.savefig(OUT / f"{name}.pdf", metadata={"CreationDate": None, "ModDate": None, "Producer": None, "Creator": None})
    fig.savefig(OUT / f"{name}.svg", metadata={"Date": None, "Creator": None})
    fig.savefig(OUT / f"{name}.png", dpi=110, metadata={"Software": None})
    plt.close(fig)
    print(f"wrote {name}.pdf/.svg", file=sys.stderr)


def write_table(name, tex):
    TABLES.mkdir(exist_ok=True)
    (TABLES / f"{name}.tex").write_text(tex, encoding="utf-8")
    print(f"wrote tables/{name}.tex", file=sys.stderr)


def fmt(x, nd=1):
    """A number with ``nd`` decimals, no trailing zeros beyond nd, thin group separators off."""
    return f"{x:.{nd}f}"
