"""Table 1: the dimension-4 parameters at the three round-3 primes and the
sizes they predict; level I also measured.  Sources: docs/COMPACT_R3.md
Sections 1 and 3; paper-dim4/BENCH.md (the paper's session, sizes table)."""
from session import *

c3 = read("docs/COMPACT_R3.md")
_, prow = md_table(section(c3, r"^## 1\."), r"^level$")
P = {r[0]: r for r in prow}
_, srow = md_table(section(c3, r"^## 3\."), r"^level$")
SZ = {r[0]: r for r in srow}
pkp = re.search(r"(\d+) / (\d+) / (\d+) bytes", grab(c3, r"(hints in the library's\s+convention \(\*\*theirs\*\*\), \d+ / \d+ / \d+ bytes)"))
lam = {"I": "128", "III": "192", "V": "256"}
meas_sig = {"I": str(SIZES[(R3, 3, 4, "I")][1])}
meas_pk = {"I": str(SIZES[(R3, 3, 4, "I")][0])}


def prime_tex(s):
    m = re.match(r"`(\d+)·2\^(\d+) − 1`", s)
    return f"${m.group(1)} \\cdot 2^{{{m.group(2)}}} - 1$"


L = ["I", "III", "V"]
strip = lambda s: s.replace("**", "").replace("`", "")
rows = [
    ("$p$\\tnote{a}", [prime_tex(P[l][1]) for l in L]),
    ("$\\log_2 p$\\tnote{a}", [P[l][2] for l in L]),
    ("$\\lambda$, challenge bits\\tnote{a}", [lam[l] for l in L]),
    ("$e$, response bound $q < 2^e$\\tnote{b}", [strip(P[l][5]) for l in L]),
    ("$r = \\lceil e/2 \\rceil + 2$, transmitted torsion bits\\tnote{c}", [strip(P[l][6]) for l in L]),
    ("half-chain steps $\\lceil e/2 \\rceil$\\tnote{c}", [P[l][7] for l in L]),
    ("public key, bytes, predicted\\tnote{d}", [pkp.group(i) for i in (1, 2, 3)]),
    ("signature, bytes, predicted\\tnote{d}", [strip(SZ[l][5]) for l in L]),
    ("public key, bytes, measured", [meas_pk.get(l, "not built") for l in L]),
    ("signature, bytes, measured", [meas_sig.get(l, "not built") for l in L]),
    ("round-3 standard signature, bytes\\tnote{a}", [SZ[l][8] for l in L]),
]
lines = ["% generated by figures/tab1_parameters.py; do not edit",
         r"\begin{tabular}{@{}lccc@{}}", r"\toprule", r" & NIST I & NIST III & NIST V \\", r"\midrule"]
for name, vals in rows:
    if name.startswith("public key, bytes, predicted"):
        lines.append(r"\addlinespace")
    lines.append(f"{name} & {vals[0]} & {vals[1]} & {vals[2]} \\\\")
lines += [r"\bottomrule", r"\end{tabular}", r"\begin{tablenotes}\footnotesize",
          r"\item[a] The SQIsign round-3 specification \cite{SQISignV3}.",
          r"\item[b] Ours: $e = \lceil (\log_2 p)/2 \rceil + 11$ (Section~\ref{sec:dim4}).",
          r"\item[c] SQIsignHD's rule for the torsion the half-chains need \cite[Section~4.3]{DLRW24}.",
          r"\item[d] Field-by-field sums of the wire format (Section~\ref{sec:dim4}).",
          r"\end{tablenotes}"]
write_table("tab1_parameters", "\n".join(lines) + "\n")
