"""Table 2: public key and signature bytes as observed in the session, round
2 and round 3, dimension 2 and 4, plus the compressed format.  Source:
paper-dim4/BENCH.md, the paper's session (sizes table)."""
from session import *

L = ["I", "III", "V"]


def cell(key):
    return f"{SIZES[key][0]} + {SIZES[key][1]} = {sum(SIZES[key])}" if key in SIZES else "not built"


rows = [
    ("round 3", "standard (specification)", [cell((R3, 3, 2, l)) for l in L]),
    ("round 3", "compressed (this crate)", [cell((R3C, 3, 2, l)) for l in L]),
    ("round 3", "compact, dim.\\ 4 (this crate)", [cell((R3, 3, 4, l)) for l in L]),
    ("round 2", "standard (specification)", [cell((R2, 2, 2, l)) for l in L]),
    ("round 2", "compact, dim.\\ 4 (crate v0.4.31)", [cell((R2, 2, 4, l)) for l in L]),
]
lines = ["% generated by figures/tab2_sizes.py; do not edit",
         r"\begin{tabular}{@{}llccc@{}}", r"\toprule",
         r"primes & format & NIST I & NIST III & NIST V \\", r"\midrule"]
prev = None
for rnd, fmt, vals in rows:
    if prev and rnd != prev:
        lines.append(r"\addlinespace")
    lines.append(f"{rnd if rnd != prev else ''} & {fmt} & {vals[0]} & {vals[1]} & {vals[2]} \\\\")
    prev = rnd
lines += [r"\bottomrule", r"\end{tabular}"]
write_table("tab2_sizes", "\n".join(lines) + "\n")
