"""Table 4: wall-clock milliseconds on two machines, level I, the bench box
(Xeon) and the M4 Pro, for the Rust code of both rounds and both
dimensions.  The M4 Pro column is read from the session's "M4 Pro" table
when the author has run it and marked pending otherwise.  Source: paper-dim4/BENCH.md,
the paper's session."""
from session import *

ops = [("keygen", "key generation"), ("sign", "signing"), ("verify from bytes", "verification")]
rows = []
for label, impl, rnd, dim in (("round 3, dimension 2 (standard)", R3, 3, 2),
                              ("round 3, dimension 4 (compact)", R3, 3, 4),
                              ("round 2, dimension 2 (standard)", R2, 2, 2),
                              ("round 2, dimension 4 (compact)", R2, 2, 4)):
    for op, opname in ops:
        x = b(impl, rnd, dim, "I", op)["ms"]
        m4 = M4.get((impl, rnd, dim, "I", op))
        rows.append((label, opname, f"{x:.1f}", f"{m4:.1f}" if m4 is not None else "pending"))
    if (impl, rnd, dim, "I", "verify compressed from bytes") in BENCH:
        x = b(impl, rnd, dim, "I", "verify compressed from bytes")["ms"]
        m4 = M4.get((impl, rnd, dim, "I", "verify compressed from bytes"))
        rows.append((label, "verification, compressed", f"{x:.1f}", f"{m4:.1f}" if m4 is not None else "pending"))
lines = ["% generated by figures/tab4_ms.py; do not edit",
         r"\begin{tabular}{@{}llrr@{}}", r"\toprule",
         f"format & operation & Xeon, {XEON_GHZ}\\,GHz (ms) & M4 Pro (ms) \\\\", r"\midrule"]
prev = None
for label, opname, x, m in rows:
    if prev and label != prev:
        lines.append(r"\addlinespace")
    lines.append(f"{label if label != prev else ''} & {opname} & {x} & {m} \\\\")
    prev = label
lines += [r"\bottomrule", r"\end{tabular}"]
write_table("tab4_ms", "\n".join(lines) + "\n")
