"""Table 5: the compact signer's rejection loop at level I, measured against
the expectation of docs/COMPACT_R3.md Section 2.  Sources: paper-dim4/BENCH.md (the
paper's session, rejection-loop row and the sign rows); COMPACT_R3.md."""
from session import *

c3 = read("docs/COMPACT_R3.md")
_, lrow = md_table(section(c3, r"^## 2\."), r"^level$")
exp = {r[0]: r for r in lrow}["I"]
import math
e = int(exp[1])
odd = f"{1 / (1 / (e * math.log(2))):.0f}"  # 1/(e ln 2): the density for odd q
s4 = b(R3, 3, 4, "I", "sign")
s2 = b(R3, 3, 2, "I", "sign")
lines = ["% generated by figures/tab5_loop.py; do not edit",
         r"\begin{tabular}{@{}lrr@{}}", r"\toprule",
         r" & measured & expected \\", r"\midrule",
         f"signatures measured & {LOOP['signatures']} & \\\\",
         f"response samples per signature, mean & {LOOP['samples_mean']:.0f} & {odd} \\\\",
         f"\\quad the same if $q$ had random parity & & {exp[3]} \\\\",
         f"response samples per signature, median (min, max) & {LOOP['samples_median']:.0f} ({LOOP['samples_min']}, {LOOP['samples_max']}) & \\\\",
         f"primality tests per signature, mean & {LOOP['tests_mean']:.0f} & {exp[4]} \\\\",
         r"\addlinespace",
         f"signing, Mcycles, median (min, max) & {s4['median']:.0f} ({s4['min']:.0f}, {s4['max']:.0f}) & \\\\",
         f"signing, dimension 2, Mcycles, median & {s2['median']:.0f} & \\\\",
         r"\bottomrule", r"\end{tabular}"]
write_table("tab5_loop", "\n".join(lines) + "\n")
