//! Left `O0`-ideals in inert Hermite normal form: creation from
//! generators, random ideals of given norm, intersection, the product
//! `conj(a) b`, equivalent ideals of small norm.

use super::dim2::sum_two_squares;
use super::lll::applications::reduce_basis;
use super::stdorder::represent_integer;
use super::{Mat4x4, QuatAlg, QuatAlgElem, QuatIdeal, QuatLattice, Vec2, Vec4};
use crate::mp::{DefaultDomain, Ibz, Rng};

impl<const N: usize> QuatIdeal<N> {
    /// From `(x, y, n)`, with the bounds of `x`, `y` set to that of `n`.
    pub fn from_xyn(x: &Ibz<N>, y: &Ibz<N>, n: &Ibz<N>) -> Self {
        let mut ideal = Self {
            x: *x,
            y: *y,
            norm: *n,
        };
        ideal.x.set_bound(n.get_bound());
        ideal.y.set_bound(n.get_bound());
        ideal
    }

    /// The lattice of the ideal (inert HNF on denominator 2).
    pub fn to_lattice(&self) -> QuatLattice<N> {
        let mut lat = QuatLattice::o0();
        let nb = self.norm.get_bound() + 1;
        lat.basis.0[0][0] = self.norm.mul_2exp(1).with_bound(nb);
        lat.basis.0[1][1] = lat.basis.0[0][0];
        lat.basis.0[2][2] = Ibz::set(1, 2);
        lat.basis.0[0][2] = self.x.mul_2exp(1).with_bound(nb);
        lat.basis.0[1][2] = self.y.mul_2exp(1).with_bound(nb).add(&Ibz::one());
        lat.basis.0[1][3] = lat.basis.0[0][2];
        lat.basis.0[0][3] = lat.basis.0[0][0].sub(&lat.basis.0[1][2]).with_bound(nb);
        lat
    }

    /// The generator `(2x + i(2y + 1) + j) / 2` of an odd-norm ideal.
    pub fn odd_inert_gen(&self) -> QuatAlgElem<N> {
        let mut gen = QuatAlgElem::set(2, 0, 0, 1, 0);
        gen.coord.0[0] = self.x.add(&self.x);
        gen.coord.0[1] = self.y.add(&self.y).add(&Ibz::one());
        gen
    }

    /// InertGenToIdOdd: the ideal generated by `gen` and an odd `norm`
    /// dividing `nrd(gen)`, when it has an inert form.
    pub fn create_o0_inert_odd(
        gen: &QuatAlgElem<N>,
        norm: &Ibz<N>,
        alg: &QuatAlg<N>,
    ) -> Option<Self> {
        let mut tmp_gen = *gen;
        tmp_gen.normalize();
        tmp_gen = tmp_gen.mod_o0(norm, alg);
        debug_assert!(tmp_gen.denom.is_one() || tmp_gen.denom == Ibz::two());
        tmp_gen.denom = Ibz::set(1, 2);
        // s = c^2 + d^2 mod n
        let mut s = tmp_gen.coord.0[2].mul(&tmp_gen.coord.0[2]);
        s = s.add(&tmp_gen.coord.0[3].mul(&tmp_gen.coord.0[3]));
        s = s.modulo(norm);
        let mut tmp = norm.gcd(&s);
        if !tmp.is_one() {
            let mut q = *norm;
            while !tmp.is_one() {
                let (qq, r) = q.div(&tmp);
                debug_assert!(r.is_zero());
                q = qq;
                tmp = q.gcd(&s);
            }
            let mut mul_helper = QuatAlgElem::set(1, 0, 0, 1, 0);
            mul_helper.coord.0[0] = q;
            tmp_gen = mul_helper.mul(&tmp_gen, alg);
            for c in tmp_gen.coord.0.iter_mut() {
                *c = c.modulo(norm);
            }
            tmp_gen.normalize();
            s = tmp_gen.coord.0[2].mul(&tmp_gen.coord.0[2]);
            s = s.add(&tmp_gen.coord.0[3].mul(&tmp_gen.coord.0[3]));
            tmp = s.gcd(norm);
        }
        if tmp.is_one() {
            debug_assert!(tmp_gen.denom.is_one());
            let t = s.add(&s).invmod(norm)?;
            // (a + bi)(c - di) as gaussian product
            let ab = Vec2([tmp_gen.coord.0[0], tmp_gen.coord.0[1]]);
            let cd = Vec2([tmp_gen.coord.0[2], tmp_gen.coord.0[3].neg()]);
            let mut g = ab.gaussian_mul(&cd);
            g.0[0] = g.0[0].modulo(norm);
            g.0[1] = g.0[1].modulo(norm);
            let x = g.0[0].mul(&t).modulo(norm);
            let mut y = g.0[1].sub(&s).modulo(norm);
            y = y.mul(&t).modulo(norm);
            Some(Self::from_xyn(&x, &y, norm))
        } else {
            None
        }
    }

    /// GenToIdOdd: the odd-norm ideal generated by `gen` and `norm`, as an
    /// inert ideal times the split generator `u + iv` returned alongside.
    pub fn create_o0_odd(
        gen: &QuatAlgElem<N>,
        norm: &Ibz<N>,
        alg: &QuatAlg<N>,
    ) -> (Self, QuatAlgElem<N>) {
        debug_assert!(norm.is_odd());
        let o0 = QuatLattice::<N>::o0();
        #[cfg(debug_assertions)]
        {
            let (_, content) = gen.make_primitive(&o0);
            debug_assert!(content.gcd(norm).is_one());
        }
        let _ = &o0;
        let mut tmp_gen = gen.mod_o0(norm, alg);
        tmp_gen.normalize();
        debug_assert!(tmp_gen.denom.is_one() || tmp_gen.denom == Ibz::two());
        tmp_gen.denom = Ibz::set(1, 2);
        // gaussian gcd of (a + bi) and (c - di)
        let ab = Vec2([tmp_gen.coord.0[0], tmp_gen.coord.0[1]]);
        let cd = Vec2([tmp_gen.coord.0[2], tmp_gen.coord.0[3].neg()]);
        let mut uv = ab.gaussian_gcd(&cd);
        // the reference builds this through an element set with 32-bit bounds
        let setter = Vec2([*norm, Ibz::set(0, 32)]);
        uv = uv.gaussian_gcd(&setter);
        let tmp = uv.0[1].neg();
        if uv.0[0].is_zero() && (tmp.is_one() || uv.0[1].is_one()) {
            uv = Vec2::set(1, 0);
        }
        let n2 = sum_two_squares(&uv.0[0], &uv.0[1]);
        let (n, r) = norm.div(&n2);
        debug_assert!(r.is_zero());
        let mut setter = QuatAlgElem::set(1, 0, 0, 0, 0);
        setter.coord.0[0] = uv.0[0];
        setter.coord.0[1] = uv.0[1].neg();
        setter.denom = n2;
        tmp_gen = tmp_gen.mul(&setter, alg);
        tmp_gen = tmp_gen.mod_o0(norm, alg);
        tmp_gen.normalize();
        let ideal = Self::create_o0_inert_odd(&tmp_gen, &n, alg).expect("inert part exists");
        let mut split_gen = QuatAlgElem::set(1, 1, 0, 0, 0);
        split_gen.coord.0[0] = uv.0[0];
        split_gen.coord.0[1] = uv.0[1];
        (ideal, split_gen)
    }

    /// GenToIdPowTwo: the ideal of norm `2^e` generated by `gen`; `None`
    /// when `i + 1` lies in `ideal + 2 O0` (no inert basis).
    pub fn create_o0_pow_two(
        gen: &QuatAlgElem<N>,
        norm: &Ibz<N>,
        alg: &QuatAlg<N>,
    ) -> Option<Self> {
        if norm.is_one() {
            return Some(Self {
                norm: Ibz::set(1, 2),
                x: Ibz::zero(),
                y: Ibz::set(1, 2),
            });
        }
        let mut tmp_gen = *gen;
        tmp_gen.normalize();
        tmp_gen = tmp_gen.mod_o0(norm, alg);
        debug_assert!(tmp_gen.denom.is_one() || tmp_gen.denom == Ibz::two());
        let mut abcd = tmp_gen.to_o0_basis();
        if abcd.0[2].is_even() == abcd.0[3].is_even() {
            if abcd.0[2].is_odd()
                && abcd.0[3].is_odd()
                && (abcd.0[1].is_even() != abcd.0[0].is_even())
            {
                let setter = QuatAlgElem::set(2, 0, 1, 1, 0);
                tmp_gen = setter.mul(&tmp_gen, alg);
                tmp_gen.normalize();
                tmp_gen = tmp_gen.mod_o0(norm, alg);
                abcd = tmp_gen.to_o0_basis();
            } else {
                return None;
            }
        }
        if abcd.0[2].is_odd() {
            let setter = QuatAlgElem::set(1, 0, 1, 0, 0);
            tmp_gen = setter.mul(&tmp_gen, alg);
            tmp_gen = tmp_gen.mod_o0(norm, alg);
            abcd = tmp_gen.to_o0_basis();
        }
        debug_assert!(abcd.0[2].is_even() && abcd.0[3].is_odd());
        let d2 = abcd.0[3].mul(&abcd.0[3]);
        let s = abcd.0[2].mul(&abcd.0[2]).add(&d2);
        let t = s.invmod(norm).expect("odd s is invertible mod 2^e");
        let mut x = abcd.0[0].mul(&abcd.0[2]);
        x = x.add(&abcd.0[1].mul(&abcd.0[3]));
        x = x.add(&abcd.0[2].mul(&abcd.0[3]));
        x = x.modulo(norm);
        x = t.mul(&x).modulo(norm);
        let mut y = abcd.0[1].mul(&abcd.0[2]);
        y = y.sub(&abcd.0[0].mul(&abcd.0[3]));
        y = y.sub(&d2);
        y = y.modulo(norm);
        y = y.mul(&t).modulo(norm);
        Some(Self::from_xyn(&x, &y, norm))
    }

    /// PrimeNormIdealInertSampling: a uniformly random ideal of odd prime
    /// norm. `None` on randomness failure.
    pub fn random_given_prime_norm(
        norm: &Ibz<N>,
        alg: &QuatAlg<N>,
        rng: &mut impl Rng,
    ) -> Option<Self> {
        debug_assert!(*norm != alg.p);
        let n2 = norm.add(norm);
        let n4 = n2.add(&n2);
        let nm1 = norm.sub(&Ibz::one());
        let mut x;
        let mut tmp;
        let mut rp;
        loop {
            x = Ibz::rand_interval(&Ibz::zero(), &nm1, rng)?;
            x = x.add(&x);
            tmp = x.mul(&x).modulo(&n4);
            tmp = alg.p.add(&tmp).neg().modulo(&n4);
            rp = tmp.modulo(norm);
            if rp.legendre(norm) == 1 && (tmp.get() & 3) < 2 {
                break;
            }
        }
        rp = rp.sqrt_mod_p(norm, rng).expect("square residue");
        let r4 = Ibz::set((tmp.get() & 1) as i64, 2);
        let four = Ibz::set(4, 4);
        let mut y = Ibz::crt(&r4, &rp, &four, norm);
        let bit = Ibz::<N>::rand_interval(&Ibz::zero(), &Ibz::one(), rng)?;
        if bit.get() & 1 == 1 {
            y = y.neg();
        }
        y = y.modulo(&n2);
        debug_assert!(y.mul(&y).modulo(&n4) == tmp);
        y = y.sub(&Ibz::one()).div_2exp(1);
        x = x.div_2exp(1);
        Some(Self::from_xyn(&x, &y, norm))
    }

    /// RandomIdealGivenNorm: a uniformly random ideal of odd `norm` as
    /// `(inert part, split generator)`, multiplied by `shift_gen`. `None`
    /// on randomness or RepresentInteger failure.
    pub fn random_given_arbitrary_odd_norm(
        norm: &Ibz<N>,
        shift_gen: &QuatAlgElem<N>,
        alg: &QuatAlg<N>,
        rng: &mut impl Rng,
    ) -> Option<(Self, QuatAlgElem<N>)> {
        debug_assert!(!norm.is_zero());
        let n_temp = alg.prime_cofactor.mul(norm);
        debug_assert!(n_temp.is_odd());
        let mut gen = represent_integer(&n_temp, alg, rng)?;
        if gen.is_zero() {
            return None;
        }
        let mut gen_rerand = QuatAlgElem::zero();
        loop {
            for i in 0..4 {
                gen_rerand.coord.0[i] = Ibz::rand_interval(&Ibz::one(), norm, rng)?;
            }
            let (n_t, d) = gen_rerand.norm(alg);
            debug_assert!(d.is_one());
            let disc = n_t.gcd(norm);
            if disc.is_one() && !gen_rerand.is_zero() {
                break;
            }
        }
        gen = gen.mul(&gen_rerand, alg);
        gen = gen.mod_o0(norm, alg);
        let shifted = shift_gen.mod_o0(norm, alg);
        gen = gen.mul(&shifted, alg);
        gen = gen.mod_o0(norm, alg);
        let (ideal, split_gen) = Self::create_o0_odd(&gen, norm, alg);
        debug_assert!(
            sum_two_squares(&split_gen.coord.0[0], &split_gen.coord.0[1]).mul(&ideal.norm) == *norm
        );
        Some((ideal, split_gen))
    }

    /// Intersect: the intersection of `a * split_a` (with `split_a = u +
    /// iv`, or `None` for `1`) and `b`, for odd coprime norms, as an inert
    /// ideal.
    pub fn intersect_o0(a: &Self, b: &Self, split_a: Option<&QuatAlgElem<N>>) -> Self {
        let (x, y) = match split_a {
            None => (b.x, b.y),
            Some(split) => {
                debug_assert!(split.denom.is_one());
                let setter = Vec2([b.x.add(&b.x), b.y.add(&b.y).add(&Ibz::one())]);
                let mut tmp = Vec2([split.coord.0[0], split.coord.0[1].neg()]);
                let t = b.norm.add(&b.norm);
                tmp = tmp.gaussian_mul(&tmp);
                tmp.0[0] = tmp.0[0].modulo(&t);
                tmp.0[1] = tmp.0[1].modulo(&t);
                tmp = setter.gaussian_mul(&tmp);
                tmp.0[0] = tmp.0[0].modulo(&t);
                tmp.0[1] = tmp.0[1].modulo(&t);
                let u2 = split.coord.0[0].mul(&split.coord.0[0]);
                let v2 = split.coord.0[1].mul(&split.coord.0[1]);
                let t = u2.add(&v2).invmod(&b.norm).expect("coprime split norm");
                debug_assert!(tmp.0[0].is_even());
                let mut x = tmp.0[0].div_2exp(1);
                x = x.mul(&t).modulo(&b.norm);
                let mut y = tmp.0[1].sub(&u2).sub(&v2);
                debug_assert!(y.is_even());
                y = y.div_2exp(1).mul(&t).modulo(&b.norm);
                (x, y)
            }
        };
        let x = Ibz::crt(&a.x, &x, &a.norm, &b.norm);
        let y = Ibz::crt(&a.y, &y, &a.norm, &b.norm);
        let r = a.norm.mul(&b.norm);
        Self::from_xyn(&x, &y, &r)
    }

    /// IdealMultiplication: the product `conj(a) b` as a lattice, for
    /// odd coprime norms.
    pub fn mul_o0(a: &Self, b: &Self) -> QuatLattice<N> {
        let (d, u, v) = a.norm.xgcd(&b.norm);
        debug_assert!(d.is_one());
        let an2 = a.norm.add(&a.norm);
        let bn2 = b.norm.add(&b.norm);
        // X1 = N2 (-v x1 mod 2N1)
        let mut t = a.x.add(&a.x);
        t = v.mul(&t).neg().modulo(&an2);
        let x1 = t.mul(&b.norm);
        // X2 = N1 (u x2 mod 2N2)
        t = b.x.add(&b.x);
        t = u.mul(&t).modulo(&bn2);
        let x2 = t.mul(&a.norm);
        // Y1 = N2 (-v y1 mod 2N1)
        let mut tmp = a.y.add(&a.y).add(&Ibz::one());
        t = v.mul(&tmp).neg().modulo(&an2);
        let y1 = t.mul(&b.norm);
        // Y2 = N1 (u y2 mod 2N2)
        tmp = b.y.add(&b.y).add(&Ibz::one());
        t = u.mul(&tmp).modulo(&bn2);
        let y2 = t.mul(&a.norm);
        let tmp = a.norm.mul(&b.norm);
        let mut prod = QuatLattice {
            denom: Ibz::set(2, 3),
            basis: Mat4x4::identity(),
        };
        prod.basis.0[0][0] = tmp.add(&tmp);
        prod.basis.0[1][1] = prod.basis.0[0][0];
        prod.basis.0[0][2] = x2.add(&x1);
        prod.basis.0[1][2] = y2.sub(&y1);
        prod.basis.0[1][3] = x2.sub(&x1);
        prod.basis.0[0][3] = y2.add(&y1).neg();
        prod
    }

    /// InertGenToId: the ideal generated by `gen` and `norm` (any norm)
    /// when it has an inert form; otherwise the largest inert ideal
    /// dividing it, with `false`.
    pub fn create_o0_inert(gen: &QuatAlgElem<N>, norm: &Ibz<N>, alg: &QuatAlg<N>) -> (Self, bool) {
        let val = norm.two_adic();
        let mut n_even = Ibz::<N>::one().mul_2exp(val as u32);
        let n_odd = norm.div_2exp(val as u32);
        let mut elem = *gen;
        let (odd, split) = Self::create_o0_odd(&elem, &n_odd, alg);
        let (sn, sd) = split.norm(alg);
        debug_assert!(sd.is_one());
        let inert_odd = sn.is_one();
        let mut inert_two = true;
        if n_even.two_adic() > 0 {
            elem = elem.mod_o0(&n_even, alg);
            let mut coeffs = elem.to_o0_basis();
            let split2 = QuatAlgElem::set(2, 1, -1, 0, 0);
            while !n_even.is_one()
                && (coeffs.0[2].is_odd() == coeffs.0[3].is_odd())
                && ((coeffs.0[1].is_even() == coeffs.0[0].is_even()) || coeffs.0[3].is_even())
            {
                inert_two = false;
                elem = split2.mul(&elem, alg);
                elem = elem.mod_o0(&n_even, alg);
                coeffs = elem.to_o0_basis();
                n_even = n_even.div_2exp(1);
            }
        }
        let even = Self::create_o0_pow_two(&elem, &n_even, alg).expect("inert two part");
        let ideal = Self::intersect_o0(&odd, &even, None);
        (ideal, inert_odd && inert_two)
    }

    /// SmallestEquivalentIdeal: `(gen, equiv, red)` with `red` the
    /// equivalent ideal of minimal norm, `equiv` the element such that
    /// `red = ideal * conj(equiv) / n(ideal)`, `gen` a generator of `red`.
    pub fn shortest_equivalent(
        &self,
        alg: &QuatAlg<N>,
        rng: &mut impl Rng,
    ) -> (QuatAlgElem<N>, QuatAlgElem<N>, Self) {
        let lat = reduce_basis(self, alg);
        let coeffs = Vec4::set(1, 0, 0, 0);
        let mut elem = QuatAlgElem {
            denom: lat.denom,
            coord: lat.basis.eval(&coeffs),
        };
        let pb = alg.p.bitsize();
        for c in elem.coord.0[..2].iter_mut() {
            c.set_bound((pb / 2 + self.norm.get_bound()) / 2 + 1);
        }
        for c in elem.coord.0[2..].iter_mut() {
            let mut b = (-pb / 2 + self.norm.get_bound()) / 2 + 1;
            if b < 1 {
                debug_assert!(c.is_zero());
                b = 1;
            }
            c.set_bound(b);
        }
        elem.denom.set_bound(3);
        let equiv = elem;
        let (mut n, g) = elem.norm(alg);
        debug_assert!(g.is_one());
        let (nn, r) = n.div(&self.norm);
        debug_assert!(r.is_zero());
        n = nn;
        n.set_bound(pb + 1);
        let gcd = n.gcd(&self.norm);
        elem = elem.conj();
        if !gcd.is_one() {
            let prod = n.mul(&self.norm);
            let (tmp, _intermediary) = small_equivalent_coprime_enumeration(
                &lat,
                &self.norm,
                Some(&prod),
                alg,
                &mut DefaultDomain(&mut *rng),
            )
            .expect("enumeration");
            elem = tmp.mul(&elem, alg);
            elem.denom = elem.denom.mul(&self.norm);
            elem.normalize();
            elem = elem.mod_o0(&n, alg);
        }
        let (mut red, _) = Self::create_o0_inert(&elem, &n, alg);
        let mut gen = elem;
        let mut equiv = equiv;
        // canonical choice despite i
        let d = red.x.mul_2exp(1);
        if d > red.norm {
            red.x = red.norm.sub(&red.x);
            red.y = red.norm.sub(&red.y).sub(&Ibz::one());
            let i_elem = QuatAlgElem::set(1, 0, 1, 0, 0);
            equiv = i_elem.mul(&equiv, alg);
            gen = gen.mul(&i_elem, alg);
        }
        (gen, equiv, red)
    }

    /// EquivalentCoprimeIdeal: `(gen, equiv)` with `equiv` an equivalent
    /// inert ideal of odd norm that is prime (`coprime_to = Some(0)`),
    /// coprime to `coprime_to`, or merely odd (`None` or `Some(2)`).
    pub fn small_equivalent_coprime(
        &self,
        coprime_to: Option<&Ibz<N>>,
        alg: &QuatAlg<N>,
        rng: &mut impl Rng,
    ) -> Option<(QuatAlgElem<N>, Self)> {
        let red = reduce_basis(self, alg);
        let inorm = self.norm;
        let (mut gen, equiv) =
            small_equivalent_coprime_enumeration(&red, &self.norm, coprime_to, alg, rng)?;
        gen.normalize();
        for c in gen.coord.0.iter_mut() {
            c.set_bound((inorm.get_bound() + equiv.norm.get_bound()) / 2 + 1);
        }
        gen.denom.set_bound(3);
        Some((gen, equiv))
    }
}

/// Enumeration behind EquivalentCoprimeIdeal on a reduced basis.
pub fn small_equivalent_coprime_enumeration<const N: usize>(
    ideal: &QuatLattice<N>,
    ideal_norm: &Ibz<N>,
    coprime_to: Option<&Ibz<N>>,
    alg: &QuatAlg<N>,
    rng: &mut impl Rng,
) -> Option<(QuatAlgElem<N>, QuatIdeal<N>)> {
    let prime = match coprime_to {
        None => true,
        Some(c) => c.is_zero(),
    };
    let add_check = match coprime_to {
        None => true,
        Some(c) => *c != Ibz::two(),
    };
    debug_assert!(alg.equiv_bound_coeff > 0);
    let bound = 32 - (alg.equiv_bound_coeff as u32).leading_zeros() as i32; // floor(log2) + 1
    let pb = alg.p.bitsize();
    loop {
        let mut coeffs = Vec4::<N>::zero();
        for c in coeffs.0.iter_mut() {
            *c = Ibz::rand_interval_minm_m(alg.equiv_bound_coeff, rng)?;
        }
        if coeffs.is_zero() {
            continue;
        }
        let content = coeffs.content();
        let _ = coeffs.scalar_div_inplace(&content);
        let mut elem = QuatAlgElem {
            denom: ideal.denom,
            coord: ideal.basis.eval(&coeffs),
        };
        elem.coord.0[0].set_bound((ideal_norm.get_bound() + bound * 2 + pb) / 2);
        elem.coord.0[1].set_bound((ideal_norm.get_bound() + bound * 2 + pb) / 2);
        elem.coord.0[2].set_bound((ideal_norm.get_bound() + bound * 2) / 2);
        elem.coord.0[3].set_bound((ideal_norm.get_bound() + bound * 2) / 2);
        let (n, d) = elem.norm(alg);
        debug_assert!(d.is_one());
        let (mut n, r) = n.div(ideal_norm);
        debug_assert!(r.is_zero());
        let mut found = n.is_odd();
        if found && add_check {
            found = if prime {
                n.probab_prime(alg.primality_num_iter, rng)
            } else {
                n.gcd(coprime_to.expect("modulus")).is_one()
            };
        }
        if found {
            n.set_bound(bound * 2 + pb + 2);
            let gen0 = elem;
            let elem_c = elem.conj();
            let (equiv, split) = QuatIdeal::create_o0_odd(&elem_c, &n, alg);
            // factor out the split part
            let mut gen = split.mul(&gen0, alg);
            let (sn, sd) = split.norm(alg);
            debug_assert!(sd.is_one());
            let _ = gen.coord.scalar_div_inplace(&sn);
            return Some((gen, equiv));
        }
    }
}

/// Gram matrix of a product `conj(a) b` in the basis of
/// [`QuatIdeal::mul_o0`], divided by its norm.
pub fn product_gram_matrix<const N: usize>(lat: &QuatLattice<N>, alg: &QuatAlg<N>) -> Mat4x4<N> {
    debug_assert!(lat.denom == Ibz::two());
    let b = &lat.basis.0;
    let ax2 = b[0][2].sub(&b[1][3]).div_2exp(1);
    let bx2 = b[0][2].add(&b[1][3]).div_2exp(1);
    let by = b[0][3].add(&b[1][2]).neg().div_2exp(1);
    let ay = b[1][2].sub(&b[0][3]).div_2exp(1);
    let nanb = b[0][0].div_2exp(1);
    let mut g = Mat4x4::zero();
    g.0[1][1] = b[0][0];
    g.0[0][0] = g.0[1][1];
    let mut tmp = ax2.add(&bx2);
    g.0[2][2] = tmp.mul(&tmp);
    tmp = ay.sub(&by);
    g.0[2][2] = g.0[2][2].add(&tmp.mul(&tmp));
    g.0[2][2] = g.0[2][2].add(&alg.p);
    let (q, r) = g.0[2][2].div(&g.0[0][0]);
    debug_assert!(r.is_zero());
    g.0[2][2] = q;
    let r_ = ay.mul(&by);
    let s = ax2.mul(&bx2);
    let t = ax2.add(&by).mul(&bx2.add(&ay));
    let (q, r) = r_.sub(&s).div(&nanb);
    debug_assert!(r.is_zero());
    g.0[3][3] = q.mul_2exp(1).add(&g.0[2][2]);
    let (q, r) = r_.add(&s).sub(&t).div(&nanb);
    debug_assert!(r.is_zero());
    g.0[2][3] = q;
    g.0[0][2] = ax2.add(&bx2);
    g.0[0][3] = ay.add(&by).neg();
    g.0[1][2] = ay.sub(&by);
    g.0[1][3] = bx2.sub(&ax2);
    let mut upper = nanb.get_bound();
    if alg.p.bitsize() > upper {
        upper = alg.p.bitsize();
    }
    for i in 0..4 {
        for j in 0..=i {
            g.0[j][i].set_bound(upper + 5);
            if i != j {
                g.0[i][j] = g.0[j][i];
            }
        }
    }
    g
}
