//! and conjugating elements.
//!
//! Generated by SageMath precompute scripts. DO NOT EDIT.

use num_bigint::BigInt;
use std::sync::LazyLock;

type Ibz = BigInt;

fn ibz(s: &str) -> Ibz {
    s.parse::<Ibz>()
        .expect("invariant: precomputed constant must parse")
}

/// Prime cofactor for random ideal generation: next_prime(2^505)
pub static QUAT_PRIME_COFACTOR: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("104748499452676539840422070298483172870932545473378073263465323779076281484949585756264642954428933028828373892081922272294952209468332577706512882860083")
});

/// The quaternion algebra prime p.
pub static QUATALG_P: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("88381546413195830490356121814345177109849335243162749316048866938595612502926212981848292492799412243073940471444121917248865926738905612439870244913151")
});

/// Number of precomputed extremal orders.
pub const NUM_ORDERS: usize = 7;

// Precomputed p-extremal maximal orders.
//
// Each order is represented as:
// - `q`: the level (1 for standard O0, prime q for alternates)
// - `order_denom`: denominator of the order basis matrix
// - `order_basis`: 4x4 basis matrix (row-major)
// - `i_denom`: denominator of sqrt(-q) in the order
// - `i_coord`: coordinates of sqrt(-q)
// - `j_denom`: denominator of sqrt(-p) (always 1)
// - `j_coord`: coordinates of sqrt(-p) (always [0,0,1,0])

pub static EXTREMAL_ORDER_0_Q: i64 = 1;
pub static EXTREMAL_ORDER_0_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static EXTREMAL_ORDER_0_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static EXTREMAL_ORDER_0_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static EXTREMAL_ORDER_0_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static EXTREMAL_ORDER_0_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static EXTREMAL_ORDER_0_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static EXTREMAL_ORDER_0_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static EXTREMAL_ORDER_0_I_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static EXTREMAL_ORDER_0_I_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_I_COORD_1: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static EXTREMAL_ORDER_0_I_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_0_I_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));

pub static EXTREMAL_ORDER_1_Q: i64 = 5;
pub static EXTREMAL_ORDER_1_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("33088064665148498528993389074658045471458410326756779584129378302168168973700")
});
pub static EXTREMAL_ORDER_1_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("33088064665148498528993389074658045471458410326756779584129378302168168973700")
});
pub static EXTREMAL_ORDER_1_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("16544032332574249264496694537329022735729205163378389792064689151084084486850")
});
pub static EXTREMAL_ORDER_1_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-57136340940730071730119970118388503695712587943738927630686069370352647277715")
});
pub static EXTREMAL_ORDER_1_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("44190773206597915245178060907172588554924667621581374658024433469297806251445965588641927224880670130501453684613347182241311285080246985408829328273261")
});
pub static EXTREMAL_ORDER_1_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("16544032332574249264496694537329022735729205163378389792064689151084084486850")
});
pub static EXTREMAL_ORDER_1_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("5"));
pub static EXTREMAL_ORDER_1_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("5713634094073007173011997011838850369571258794373892763068606937035264727773")
});
pub static EXTREMAL_ORDER_1_I_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("33088064665148498528993389074658045471458410326756779584129378302168168973700")
});
pub static EXTREMAL_ORDER_1_I_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_I_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-57136340940730071730119970118388503695712587943738927630686069370352647277715")
});
pub static EXTREMAL_ORDER_1_I_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_1_I_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("5"));

pub static EXTREMAL_ORDER_2_Q: i64 = 37;
pub static EXTREMAL_ORDER_2_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("332521113390987919898733955700245201183519068534895006886382414518324995298970")
});
pub static EXTREMAL_ORDER_2_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("332521113390987919898733955700245201183519068534895006886382414518324995298970")
});
pub static EXTREMAL_ORDER_2_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("166260556695493959949366977850122600591759534267447503443191207259162497649485")
});
pub static EXTREMAL_ORDER_2_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-1468057004630372526384191846849074776959643611404604215365265938457651981853714")
});
pub static EXTREMAL_ORDER_2_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("176763092826391660980712243628690354219698670486325498632097733877191225005435815192112290079462770043123143506183480106936965792360641161263379792273221")
});
pub static EXTREMAL_ORDER_2_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("166260556695493959949366977850122600591759534267447503443191207259162497649485")
});
pub static EXTREMAL_ORDER_2_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("148"));
pub static EXTREMAL_ORDER_2_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("19838608170680709816002592524987496985941129883846002910341431600779080835903")
});
pub static EXTREMAL_ORDER_2_I_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("332521113390987919898733955700245201183519068534895006886382414518324995298970")
});
pub static EXTREMAL_ORDER_2_I_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_I_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-1468057004630372526384191846849074776959643611404604215365265938457651981853714")
});
pub static EXTREMAL_ORDER_2_I_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_2_I_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("148"));

pub static EXTREMAL_ORDER_3_Q: i64 = 61;
pub static EXTREMAL_ORDER_3_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("387284123591087837254966834619278458636664228522306402154948928971132996862750")
});
pub static EXTREMAL_ORDER_3_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("387284123591087837254966834619278458636664228522306402154948928971132996862750")
});
pub static EXTREMAL_ORDER_3_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("193642061795543918627483417309639229318332114261153201077474464485566498431375")
});
pub static EXTREMAL_ORDER_3_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("1971660414035010734775219502160292053916825826229311253382823797415458833368258")
});
pub static EXTREMAL_ORDER_3_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-176763092826391660980712243628690354219698670486325498632097733877191225005092851869765064456628043202528752036871106016196275878813936483252473562217219")
});
pub static EXTREMAL_ORDER_3_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("193642061795543918627483417309639229318332114261153201077474464485566498431375")
});
pub static EXTREMAL_ORDER_3_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("-244"));
pub static EXTREMAL_ORDER_3_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-16161150934713202744059176247215508638662506772371403716252654077175892076883")
});
pub static EXTREMAL_ORDER_3_I_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("387284123591087837254966834619278458636664228522306402154948928971132996862750")
});
pub static EXTREMAL_ORDER_3_I_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_I_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("1971660414035010734775219502160292053916825826229311253382823797415458833368258")
});
pub static EXTREMAL_ORDER_3_I_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_3_I_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("-244"));

pub static EXTREMAL_ORDER_4_Q: i64 = 97;
pub static EXTREMAL_ORDER_4_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("119518545108709038548294071574886394417700255137203845136763291346977694945172")
});
pub static EXTREMAL_ORDER_4_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("119518545108709038548294071574886394417700255137203845136763291346977694945172")
});
pub static EXTREMAL_ORDER_4_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("59759272554354519274147035787443197208850127568601922568381645673488847472586")
});
pub static EXTREMAL_ORDER_4_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-744333422878339249641694692544367932125511429761829137690082129376696732177417")
});
pub static EXTREMAL_ORDER_4_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-44190773206597915245178060907172588554924667621581374658024433469297806251766211338384913260429056022109161300865954788269713900882424394986734307209235")
});
pub static EXTREMAL_ORDER_4_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("59759272554354519274147035787443197208850127568601922568381645673488847472586")
});
pub static EXTREMAL_ORDER_4_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("-97"));
pub static EXTREMAL_ORDER_4_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("3836770221022367266194302538888494495492326957535201740670526440086065629741")
});
pub static EXTREMAL_ORDER_4_I_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("119518545108709038548294071574886394417700255137203845136763291346977694945172")
});
pub static EXTREMAL_ORDER_4_I_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_I_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-744333422878339249641694692544367932125511429761829137690082129376696732177417")
});
pub static EXTREMAL_ORDER_4_I_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_4_I_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("-97"));

pub static EXTREMAL_ORDER_5_Q: i64 = 113;
pub static EXTREMAL_ORDER_5_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("11005244500016418293927980784996197621777562840323993659459208608079570869812")
});
pub static EXTREMAL_ORDER_5_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("11005244500016418293927980784996197621777562840323993659459208608079570869812")
});
pub static EXTREMAL_ORDER_5_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("5502622250008209146963990392498098810888781420161996829729604304039785434906")
});
pub static EXTREMAL_ORDER_5_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("54698023904747309429282409617279990506417038990094749112748090989639823970051")
});
pub static EXTREMAL_ORDER_5_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("4301756683828115643335917433441579416851073839268983373789989098781202378466576979425400024502951460597392853838641296400485417804075963847788887811309")
});
pub static EXTREMAL_ORDER_5_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("5502622250008209146963990392498098810888781420161996829729604304039785434906")
});
pub static EXTREMAL_ORDER_5_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("11"));
pub static EXTREMAL_ORDER_5_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-242026654445784554996824821315398188081491322965021013773221641547078867123")
});
pub static EXTREMAL_ORDER_5_I_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("11005244500016418293927980784996197621777562840323993659459208608079570869812")
});
pub static EXTREMAL_ORDER_5_I_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_I_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("54698023904747309429282409617279990506417038990094749112748090989639823970051")
});
pub static EXTREMAL_ORDER_5_I_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_5_I_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("11"));

pub static EXTREMAL_ORDER_6_Q: i64 = 149;
pub static EXTREMAL_ORDER_6_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("771405056703245970026655923283129671166922323385533149455957637049969493768092")
});
pub static EXTREMAL_ORDER_6_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("771405056703245970026655923283129671166922323385533149455957637049969493768092")
});
pub static EXTREMAL_ORDER_6_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("385702528351622985013327961641564835583461161692766574727978818524984746884046")
});
pub static EXTREMAL_ORDER_6_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-6293713583140669549121001154819683976806579577280530635473559569321533758082481")
});
pub static EXTREMAL_ORDER_6_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-220953866032989576225890304535862942774623338107906873290122167346489031259195198591867441265125272563318917869669987955464336718045743231333288043388048")
});
pub static EXTREMAL_ORDER_6_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("385702528351622985013327961641564835583461161692766574727978818524984746884046")
});
pub static EXTREMAL_ORDER_6_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("-745"));
pub static EXTREMAL_ORDER_6_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("21119844238727079023895977029596254955726777104968223608971676407119240798712")
});
pub static EXTREMAL_ORDER_6_I_DENOM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("771405056703245970026655923283129671166922323385533149455957637049969493768092")
});
pub static EXTREMAL_ORDER_6_I_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_I_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-6293713583140669549121001154819683976806579577280530635473559569321533758082481")
});
pub static EXTREMAL_ORDER_6_I_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static EXTREMAL_ORDER_6_I_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("-745"));

// Connecting ideal 0 (q=1)
pub static CONNECTING_IDEAL_0_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_0_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_0_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_0_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_0_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_0_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_0_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_0_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_0_NORM: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));

// Connecting ideal 1 (q=5)
pub static CONNECTING_IDEAL_1_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_1_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("16851141221886169542744078842234253087465057214612564448680826214460743857354")
});
pub static CONNECTING_IDEAL_1_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("4809655255116314640225316208746091644850835523396429609311338213636895660803")
});
pub static CONNECTING_IDEAL_1_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("16851141221886169542744078842234253087465057214612564448680826214460743857354")
});
pub static CONNECTING_IDEAL_1_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("12041485966769854902518762633488161442614221691216134839369488000823848196551")
});
pub static CONNECTING_IDEAL_1_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_1_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_1_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_1_NORM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("8425570610943084771372039421117126543732528607306282224340413107230371928677")
});

// Connecting ideal 2 (q=37)
pub static CONNECTING_IDEAL_2_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_2_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("8987057118675349186452269072979600031987001852294459645577903095089864737810")
});
pub static CONNECTING_IDEAL_2_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("3179011246333843018162094457759048468980313552702156720987288479072141864573")
});
pub static CONNECTING_IDEAL_2_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("8987057118675349186452269072979600031987001852294459645577903095089864737810")
});
pub static CONNECTING_IDEAL_2_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("5808045872341506168290174615220551563006688299592302924590614616017722873237")
});
pub static CONNECTING_IDEAL_2_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_2_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_2_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_2_NORM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("4493528559337674593226134536489800015993500926147229822788951547544932368905")
});

// Connecting ideal 3 (q=61)
pub static CONNECTING_IDEAL_3_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_3_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("6348920058870292414015849747857023912076462762660760691064736540510376997750")
});
pub static CONNECTING_IDEAL_3_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("144425393768735854509775938786474429235674932859750994295406362949974791207")
});
pub static CONNECTING_IDEAL_3_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("6348920058870292414015849747857023912076462762660760691064736540510376997750")
});
pub static CONNECTING_IDEAL_3_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("6204494665101556559506073809070549482840787829801009696769330177560402206543")
});
pub static CONNECTING_IDEAL_3_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_3_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_3_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_3_NORM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("3174460029435146207007924873928511956038231381330380345532368270255188498875")
});

// Connecting ideal 4 (q=97)
pub static CONNECTING_IDEAL_4_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_4_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("72464326449224434361517616023837758095124507560475808889755574488505043417642")
});
pub static CONNECTING_IDEAL_4_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("951509204975505362849111427627183802045261404109255446054236186104609612771")
});
pub static CONNECTING_IDEAL_4_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("72464326449224434361517616023837758095124507560475808889755574488505043417642")
});
pub static CONNECTING_IDEAL_4_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("71512817244248928998668504596210574293079246156366553443701338302400433804871")
});
pub static CONNECTING_IDEAL_4_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_4_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_4_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_4_NORM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("36232163224612217180758808011918879047562253780237904444877787244252521708821")
});

// Connecting ideal 5 (q=113)
pub static CONNECTING_IDEAL_5_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_5_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("17071933719419329081445334252084918817103091420377343934982245436457677849046")
});
pub static CONNECTING_IDEAL_5_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("7097002228071201726997851202788466215711741130221460534069142342817888910945")
});
pub static CONNECTING_IDEAL_5_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("17071933719419329081445334252084918817103091420377343934982245436457677849046")
});
pub static CONNECTING_IDEAL_5_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("9974931491348127354447483049296452601391350290155883400913103093639788938101")
});
pub static CONNECTING_IDEAL_5_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_5_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_5_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_5_NORM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("8535966859709664540722667126042459408551545710188671967491122718228838924523")
});

// Connecting ideal 6 (q=149)
pub static CONNECTING_IDEAL_6_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONNECTING_IDEAL_6_BASIS_00: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("21924900636234848373511558007710993834660464383169327518035430813296757398150")
});
pub static CONNECTING_IDEAL_6_BASIS_01: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_02: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_03: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("16912078953011320774551120628031796856991456830509729789909404353795992752643")
});
pub static CONNECTING_IDEAL_6_BASIS_10: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_11: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("21924900636234848373511558007710993834660464383169327518035430813296757398150")
});
pub static CONNECTING_IDEAL_6_BASIS_12: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("5012821683223527598960437379679196977669007552659597728126026459500764645507")
});
pub static CONNECTING_IDEAL_6_BASIS_13: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_20: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_21: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_22: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_6_BASIS_23: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_30: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_31: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_32: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONNECTING_IDEAL_6_BASIS_33: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONNECTING_IDEAL_6_NORM: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("10962450318117424186755779003855496917330232191584663759017715406648378699075")
});

// Conjugating element 0 (q=1)
pub static CONJUGATING_ELEM_0_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONJUGATING_ELEM_0_COORD_0: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONJUGATING_ELEM_0_COORD_1: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONJUGATING_ELEM_0_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));
pub static CONJUGATING_ELEM_0_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("0"));

// Conjugating element 1 (q=5)
pub static CONJUGATING_ELEM_1_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONJUGATING_ELEM_1_COORD_0: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("21660796477002484182969395050980344732315892738008994057992164428097639518157")
});
pub static CONJUGATING_ELEM_1_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-21660796477002484182969395050980344732315892738008994057992164428097639518157")
});
pub static CONJUGATING_ELEM_1_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONJUGATING_ELEM_1_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("-1"));

// Conjugating element 2 (q=37)
pub static CONJUGATING_ELEM_2_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONJUGATING_ELEM_2_COORD_0: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-19838608170680709816002592524987496985941129883846002910341431600779080835861")
});
pub static CONJUGATING_ELEM_2_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-19838608170680709816002592524987496985941129883846002910341431600779080835861")
});
pub static CONJUGATING_ELEM_2_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONJUGATING_ELEM_2_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));

// Conjugating element 3 (q=61)
pub static CONJUGATING_ELEM_3_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("1"));
pub static CONJUGATING_ELEM_3_COORD_0: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("16161150934713202744059176247215508638662506772371403716252654077175892076789")
});
pub static CONJUGATING_ELEM_3_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("16161150934713202744059176247215508638662506772371403716252654077175892076789")
});
pub static CONJUGATING_ELEM_3_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("-2"));
pub static CONJUGATING_ELEM_3_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("-2"));

// Conjugating element 4 (q=97)
pub static CONJUGATING_ELEM_4_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONJUGATING_ELEM_4_COORD_0: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("65803762014395896821573836030447471480807677731711020767375921185772776128245")
});
pub static CONJUGATING_ELEM_4_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-65803762014395896821573836030447471480807677731711020767375921185772776128245")
});
pub static CONJUGATING_ELEM_4_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("-7"));
pub static CONJUGATING_ELEM_4_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("7"));

// Conjugating element 5 (q=113)
pub static CONJUGATING_ELEM_5_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONJUGATING_ELEM_5_COORD_0: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-9974931491348127354447483049296452601391350290155883400913103093639788938101")
});
pub static CONJUGATING_ELEM_5_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-9974931491348127354447483049296452601391350290155883400913103093639788938101")
});
pub static CONJUGATING_ELEM_5_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("-1"));
pub static CONJUGATING_ELEM_5_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("-1"));

// Conjugating element 6 (q=149)
pub static CONJUGATING_ELEM_6_DENOM: LazyLock<Ibz> = LazyLock::new(|| ibz("2"));
pub static CONJUGATING_ELEM_6_COORD_0: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-44457821299268383081072104102725408463605223731271867124538810092973846599159")
});
pub static CONJUGATING_ELEM_6_COORD_1: LazyLock<Ibz> = LazyLock::new(|| {
    ibz("-44457821299268383081072104102725408463605223731271867124538810092973846599159")
});
pub static CONJUGATING_ELEM_6_COORD_2: LazyLock<Ibz> = LazyLock::new(|| ibz("13"));
pub static CONJUGATING_ELEM_6_COORD_3: LazyLock<Ibz> = LazyLock::new(|| ibz("13"));
