//! Cross-validation test: assert the Rust Level 1 EC arithmetic
//! produces byte-identical output to the reference implementation
//! for a fixed sequence of operations on known inputs.
//!
//! The expected hex bytes below were generated by the external harness
//! under `tools/c-validate/ec_validate.c`; see the README for the
//! procedure to regenerate them.

use hex_literal::hex;
use sqisign_verify::ec::jacobian::{jac_add, jac_dbl};
use sqisign_verify::ec::point::*;
use sqisign_verify::ec::{EcCurve, EcPoint, JacPoint};
use sqisign_verify::fp::{Fp2, FpBackend};
use sqisign_verify::params::Level1;

fn fp2_small<L: FpBackend>(re: u64, im: u64) -> Fp2<L> {
    Fp2 {
        re: sqisign_verify::fp::Fp::<L>::from_small(re),
        im: sqisign_verify::fp::Fp::<L>::from_small(im),
    }
}

fn fp2_encode<L: FpBackend>(a: &Fp2<L>) -> [u8; 64] {
    let arr = a.encode();
    let mut out = [0u8; 64];
    out.copy_from_slice(arr.as_ref());
    out
}

fn point_encode<L: FpBackend>(p: &EcPoint<L>) -> ([u8; 64], [u8; 64]) {
    (fp2_encode(&p.x), fp2_encode(&p.z))
}

fn jac_encode<L: FpBackend>(p: &JacPoint<L>) -> ([u8; 64], [u8; 64], [u8; 64]) {
    (fp2_encode(&p.x), fp2_encode(&p.y), fp2_encode(&p.z))
}

fn hex_str(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

fn assert_fp2(label: &str, got: &[u8; 64], expected: &[u8; 64]) {
    assert_eq!(
        &got[..],
        &expected[..],
        "{label}:\n  got      {}\n  expected {}",
        hex_str(got),
        hex_str(expected),
    );
}

fn assert_point(label: &str, p: &EcPoint<Level1>, exp_x: &[u8; 64], exp_z: &[u8; 64]) {
    let (gx, gz) = point_encode::<Level1>(p);
    assert_fp2(&format!("{label}.x"), &gx, exp_x);
    assert_fp2(&format!("{label}.z"), &gz, exp_z);
}

fn assert_jac(
    label: &str,
    p: &JacPoint<Level1>,
    exp_x: &[u8; 64],
    exp_y: &[u8; 64],
    exp_z: &[u8; 64],
) {
    let (gx, gy, gz) = jac_encode::<Level1>(p);
    assert_fp2(&format!("{label}.x"), &gx, exp_x);
    assert_fp2(&format!("{label}.y"), &gy, exp_y);
    assert_fp2(&format!("{label}.z"), &gz, exp_z);
}

#[test]
fn c_crossvalidate_ec_lvl1() {
    // ---- Curve E0: A=0, C=1 ----
    let mut e0 = EcCurve::<Level1>::default();
    e0.normalize_a24();

    // ---- Points ----
    let p = EcPoint::new(fp2_small::<Level1>(3, 1), Fp2::one());
    let q = EcPoint::new(fp2_small::<Level1>(7, 2), Fp2::one());
    let pq = EcPoint::new(fp2_small::<Level1>(5, 3), Fp2::one());

    // ---- Test 1: xDBL ----
    {
        let ac = EcPoint::new(e0.a.clone(), e0.c.clone());
        let r = xdbl(&p, &ac);
        assert_point(
            "xDBL(P)",
            &r,
            &hex!("34000000000000000000000000000000000000000000000000000000000000005001000000000000000000000000000000000000000000000000000000000000"),
            &hex!("5001000000000000000000000000000000000000000000000000000000000000b001000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 2: xADD ----
    {
        let r = xadd(&p, &q, &pq);
        assert_point(
            "xADD(P,Q,PQ)",
            &r,
            &hex!("6c020000000000000000000000000000000000000000000000000000000000005007000000000000000000000000000000000000000000000000000000000000"),
            &hex!("cc000000000000000000000000000000000000000000000000000000000000005401000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 3: xDBLADD ----
    {
        let (dbl_out, add_out) = xdbladd(&p, &q, &pq, &e0.a24, true);
        assert_point(
            "xDBLADD.dbl",
            &dbl_out,
            &hex!("0d000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000000"),
            &hex!("54000000000000000000000000000000000000000000000000000000000000006c00000000000000000000000000000000000000000000000000000000000000"),
        );
        assert_point(
            "xDBLADD.add",
            &add_out,
            &hex!("6c020000000000000000000000000000000000000000000000000000000000005007000000000000000000000000000000000000000000000000000000000000"),
            &hex!("cc000000000000000000000000000000000000000000000000000000000000005401000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 4: xMUL (scalar multiplication by 42) ----
    {
        let k: [u64; 4] = [42, 0, 0, 0];
        let r = ec_mul(&p, &k, 6, &mut e0.clone());
        assert_point(
            "xMUL(P,42)",
            &r,
            &hex!("2a996ccaf7bfaab3f2769b661f8738718eff500712787c17b49c207806d1d504aed5741b5d22d52a4de548808096e27f75f4b23ccc46dad56f404b792fd49900"),
            &hex!("c3e5728b6cec96626e5067b11f726e0e20a646c4ce5ba8d5df032c11911ea4039276237074dc4631a05816e2401bdb88f10d079cb79626c04f09fac0e3b82a02"),
        );
    }

    // ---- Test 5: ec_ladder3pt ----
    {
        let m: [u64; 4] = [17, 0, 0, 0];
        let r = ec_ladder3pt(&m, &p, &q, &pq, &e0).expect("ladder3pt failed");
        assert_point(
            "ladder3pt(P,Q,PQ,17)",
            &r,
            &hex!("c704d1af653116314f0859363c93bb98d85bdc298e9f324de2ac0187dfbd7300239c568d8bd0a340511b3504e180116770406d4a24705f5ad6a06f319795b701"),
            &hex!("a8725429c8d4639f913b88147b77ba2386a75b17a86b1158cc105246e953b400593e8f3b3f8274459c5435994f8de6125660cb6706c3ed3d738d7bad67ef8f00"),
        );
    }

    // ---- Test 6: j-invariant of E0 ----
    {
        let j = e0.j_inv();
        let j_bytes = fp2_encode(&j);
        assert_fp2(
            "j_inv(E0)",
            &j_bytes,
            &hex!("c0060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 7: j-invariant of E1 (A=6, C=1) ----
    {
        let e1 = EcCurve::<Level1>::from_a(&fp2_small::<Level1>(6, 0)).unwrap();
        let j = e1.j_inv();
        let j_bytes = fp2_encode(&j);
        assert_fp2(
            "j_inv(E1)",
            &j_bytes,
            &hex!("08630400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 8: ec_normalize_point ----
    {
        let mut t = EcPoint::new(fp2_small::<Level1>(3, 1), fp2_small::<Level1>(7, 2));
        t.normalize();
        assert_point(
            "normalize(3+i:7+2i)",
            &t,
            &hex!("b3cf2135c1782bfb1c52138cb7b2cf2135c1782bfb1c52138cb7b2cf2135c100f156f639a426186f659f436a82f156f639a426186f659f436a82f156f639a402"),
            &hex!("01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Jacobian tests ----
    let jp = JacPoint::new(
        fp2_small::<Level1>(3, 1),
        fp2_small::<Level1>(11, 5),
        Fp2::one(),
    );
    let jq = JacPoint::new(
        fp2_small::<Level1>(7, 2),
        fp2_small::<Level1>(13, 4),
        Fp2::one(),
    );

    // ---- Test 9: Jacobian DBL ----
    {
        let r = jac_dbl(&jp, &e0);
        assert_jac(
            "jac_dbl(P)",
            &r,
            &hex!("9cfbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0433f6ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04"),
            &hex!("2ae5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff045988ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04"),
            &hex!("16000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 10: Jacobian ADD ----
    {
        let r = jac_add(&jp, &jq, &e0);
        assert_jac(
            "jac_add(P,Q)",
            &r,
            &hex!("84ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff047effffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04"),
            &hex!("9700000000000000000000000000000000000000000000000000000000000000a6fdffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04"),
            &hex!("04000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 11: jac_to_xz ----
    {
        let pq_jac = jac_add(&jp, &jq, &e0);
        let xz = pq_jac.to_xz();
        assert_point(
            "jac_to_xz(P+Q)",
            &xz,
            &hex!("84ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff047effffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04"),
            &hex!("0f000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 12: Jacobian ADD with identity ----
    {
        let jz = JacPoint::<Level1>::identity();
        let r = jac_add(&jp, &jz, &e0);
        assert_jac(
            "jac_add(P,0)",
            &r,
            &hex!("03000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000"),
            &hex!("0b000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000"),
            &hex!("01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"),
        );
    }

    // ---- Test 13: jac_neg + add = identity ----
    {
        let neg_jp = jp.neg();
        let r = jac_add(&jp, &neg_jp, &e0);
        assert_jac(
            "jac_add(P,-P)",
            &r,
            &hex!("8001000000000000000000000000000000000000000000000000000000000000b801000000000000000000000000000000000000000000000000000000000000"),
            &hex!("d00f000000000000000000000000000000000000000000000000000000000000d034000000000000000000000000000000000000000000000000000000000000"),
            &hex!("00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"),
        );
    }
}
