[package]
name = "sqisign-verify-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.sqisign-verify]
path = ".."

[[bin]]
name = "fuzz_pubkey_from_bytes"
path = "fuzz_targets/fuzz_pubkey_from_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_signature_from_bytes"
path = "fuzz_targets/fuzz_signature_from_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_verify"
path = "fuzz_targets/fuzz_verify.rs"
test = false
doc = false
bench = false
