//! Precomputed endomorphism-ring constants per prime, for the signing side:
//! the action of the maximal order `O0 = Z<1, i, (i + j)/2, (1 + k)/2>` on
//! the basis of `E0[2^f]`, and quaternion-layer sizes.
//!
//! The per-prime files are generated by `tools/gen-precomp` and checked
//! against the SQIsign reference implementation. See PRECOMP.md.

pub mod p324_3;
pub mod p500_27;
pub mod p664_17;

/// A 2x2 matrix over `Z/2^f` with little-endian byte entries of length `N`,
/// in the reference's `ibz_mat_2x2_t` layout: `[[a(P0), a(Q0)], [b(P0), b(Q0)]]`.
pub type Mat2x2<const N: usize> = [[[u8; N]; 2]; 2];

/// Basis of the maximal order `O0` in the quaternion algebra `(-1, -p)`, as
/// integer coordinates over `(1, i, j, k)` divided by [`O0_DENOM`]:
/// `1, i, (i + j)/2, (1 + k)/2`. Rows are basis elements.
pub const O0_BASIS_NUM: [[i8; 4]; 4] = [[2, 0, 0, 0], [0, 2, 0, 0], [0, 1, 1, 0], [1, 0, 0, 1]];

/// Common denominator of [`O0_BASIS_NUM`].
pub const O0_DENOM: u8 = 2;
