//! Cross-validation: compare ALL Level 1 signing precomputed constants
//! against the reference output.
//!
//! The expected values come from `tools/c-validate/signing_precomp_expected.txt`,
//! generated by `tools/c-validate/signing_precomp_cval`.
//!
//! Every constant is compared string-for-string. Mismatches are reported
//! with full context (label, expected, got).

use num_bigint::BigInt;
use std::collections::HashMap;

use sqisign_rs::precomp::level1::{e0_basis, ec_params};
use sqisign_rs::precomp_signing::level1::{
    endomorphism_action, quaternion_constants, quaternion_data, torsion_constants,
};

fn load_expected() -> HashMap<String, String> {
    let raw = include_str!("../../../tools/c-validate/signing_precomp_expected.txt");
    let mut map = HashMap::new();
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with("===") {
            continue;
        }
        if let Some((key, val)) = line.split_once('=') {
            map.insert(key.to_string(), val.to_string());
        }
    }
    map
}

fn assert_match(expected: &HashMap<String, String>, key: &str, got: &str) {
    let exp = expected
        .get(key)
        .unwrap_or_else(|| panic!("Missing key in C output: {key}"));
    assert_eq!(
        got, exp,
        "\nMISMATCH for {key}:\n  Rust: {got}\n  C:    {exp}"
    );
}

fn bigint_to_decimal(b: &BigInt) -> String {
    format!("{b}")
}

fn fp_limbs_to_hex_csv(limbs: &[u64]) -> String {
    limbs
        .iter()
        .map(|l| format!("{:#x}", l))
        .collect::<Vec<_>>()
        .join(",")
}

// ========================================================================
// Tests
// ========================================================================

#[test]
fn crossvalidate_torsion_constants() {
    let expected = load_expected();

    assert_match(&expected, "TORSION_2POWER_BYTES", "32");
    assert_match(
        &expected,
        "TWO_TO_SECURITY_BITS",
        &bigint_to_decimal(&torsion_constants::TWO_TO_SECURITY_BITS),
    );
    assert_match(
        &expected,
        "TORSION_PLUS_2POWER",
        &bigint_to_decimal(&torsion_constants::TORSION_PLUS_2POWER),
    );
    assert_match(
        &expected,
        "SEC_DEGREE",
        &bigint_to_decimal(&torsion_constants::SEC_DEGREE),
    );
    assert_match(
        &expected,
        "COM_DEGREE",
        &bigint_to_decimal(&torsion_constants::COM_DEGREE),
    );
}

#[test]
fn crossvalidate_ec_params() {
    let expected = load_expected();

    assert_match(
        &expected,
        "TORSION_EVEN_POWER",
        &ec_params::TORSION_EVEN_POWER.to_string(),
    );
    assert_match(
        &expected,
        "P_COFACTOR_FOR_2F_BITLENGTH",
        &ec_params::P_COFACTOR_FOR_2F_BITLENGTH.to_string(),
    );
    assert_match(
        &expected,
        "P_COFACTOR_FOR_2F",
        &ec_params::P_COFACTOR_FOR_2F[0].to_string(),
    );
}

#[test]
fn crossvalidate_quaternion_data() {
    let expected = load_expected();

    assert_match(
        &expected,
        "QUAT_prime_cofactor",
        &bigint_to_decimal(&quaternion_data::QUAT_PRIME_COFACTOR),
    );
    assert_match(
        &expected,
        "QUATALG_P",
        &bigint_to_decimal(&quaternion_data::QUATALG_P),
    );
}

#[test]
fn crossvalidate_extremal_orders() {
    let expected = load_expected();

    struct OrderRefs {
        q: i64,
        denom: &'static BigInt,
        basis: [&'static BigInt; 16],
        i_denom: &'static BigInt,
        i_coord: [&'static BigInt; 4],
    }

    macro_rules! order_ref {
        ($idx:literal) => {
            paste::paste! {
                OrderRefs {
                    q: quaternion_data::[<EXTREMAL_ORDER_ $idx _Q>],
                    denom: &*quaternion_data::[<EXTREMAL_ORDER_ $idx _DENOM>],
                    basis: [
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_00>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_01>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_02>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_03>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_10>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_11>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_12>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_13>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_20>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_21>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_22>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_23>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_30>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_31>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_32>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _BASIS_33>],
                    ],
                    i_denom: &*quaternion_data::[<EXTREMAL_ORDER_ $idx _I_DENOM>],
                    i_coord: [
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _I_COORD_0>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _I_COORD_1>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _I_COORD_2>],
                        &*quaternion_data::[<EXTREMAL_ORDER_ $idx _I_COORD_3>],
                    ],
                }
            }
        };
    }

    let orders = [
        order_ref!(0),
        order_ref!(1),
        order_ref!(2),
        order_ref!(3),
        order_ref!(4),
        order_ref!(5),
        order_ref!(6),
    ];

    for (idx, o) in orders.iter().enumerate() {
        let pfx = format!("EXTREMAL_ORDER[{idx}]");

        assert_match(&expected, &format!("{pfx}.q"), &o.q.to_string());
        assert_match(
            &expected,
            &format!("{pfx}.order.denom"),
            &bigint_to_decimal(o.denom),
        );

        for i in 0..4 {
            for j in 0..4 {
                assert_match(
                    &expected,
                    &format!("{pfx}.order.basis[{i}][{j}]"),
                    &bigint_to_decimal(o.basis[i * 4 + j]),
                );
            }
        }

        // C's "z" = Rust's "I" (sqrt(-q) in the order)
        assert_match(
            &expected,
            &format!("{pfx}.z.denom"),
            &bigint_to_decimal(o.i_denom),
        );
        for k in 0..4 {
            assert_match(
                &expected,
                &format!("{pfx}.z.coord[{k}]"),
                &bigint_to_decimal(o.i_coord[k]),
            );
        }

        // C's "t" = sqrt(-p) = j, always denom=1, coord=[0,0,1,0]
        assert_match(&expected, &format!("{pfx}.t.denom"), "1");
        assert_match(&expected, &format!("{pfx}.t.coord[0]"), "0");
        assert_match(&expected, &format!("{pfx}.t.coord[1]"), "0");
        assert_match(&expected, &format!("{pfx}.t.coord[2]"), "1");
        assert_match(&expected, &format!("{pfx}.t.coord[3]"), "0");
    }
}

#[test]
fn crossvalidate_connecting_ideals() {
    let expected = load_expected();

    struct IdealRefs {
        denom: &'static BigInt,
        basis: [&'static BigInt; 16],
        norm: &'static BigInt,
    }

    macro_rules! ideal_ref {
        ($idx:literal) => {
            paste::paste! {
                IdealRefs {
                    denom: &*quaternion_data::[<CONNECTING_IDEAL_ $idx _DENOM>],
                    basis: [
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_00>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_01>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_02>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_03>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_10>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_11>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_12>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_13>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_20>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_21>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_22>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_23>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_30>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_31>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_32>],
                        &*quaternion_data::[<CONNECTING_IDEAL_ $idx _BASIS_33>],
                    ],
                    norm: &*quaternion_data::[<CONNECTING_IDEAL_ $idx _NORM>],
                }
            }
        };
    }

    let ideals = [
        ideal_ref!(0),
        ideal_ref!(1),
        ideal_ref!(2),
        ideal_ref!(3),
        ideal_ref!(4),
        ideal_ref!(5),
        ideal_ref!(6),
    ];

    for (idx, ideal) in ideals.iter().enumerate() {
        let pfx = format!("CONNECTING_IDEAL[{idx}]");

        assert_match(
            &expected,
            &format!("{pfx}.norm"),
            &bigint_to_decimal(ideal.norm),
        );
        assert_match(
            &expected,
            &format!("{pfx}.lattice.denom"),
            &bigint_to_decimal(ideal.denom),
        );

        for i in 0..4 {
            for j in 0..4 {
                assert_match(
                    &expected,
                    &format!("{pfx}.lattice.basis[{i}][{j}]"),
                    &bigint_to_decimal(ideal.basis[i * 4 + j]),
                );
            }
        }
    }
}

#[test]
fn crossvalidate_conjugating_elements() {
    let expected = load_expected();

    struct ElemRefs {
        denom: &'static BigInt,
        coord: [&'static BigInt; 4],
    }

    macro_rules! elem_ref {
        ($idx:literal) => {
            paste::paste! {
                ElemRefs {
                    denom: &*quaternion_data::[<CONJUGATING_ELEM_ $idx _DENOM>],
                    coord: [
                        &*quaternion_data::[<CONJUGATING_ELEM_ $idx _COORD_0>],
                        &*quaternion_data::[<CONJUGATING_ELEM_ $idx _COORD_1>],
                        &*quaternion_data::[<CONJUGATING_ELEM_ $idx _COORD_2>],
                        &*quaternion_data::[<CONJUGATING_ELEM_ $idx _COORD_3>],
                    ],
                }
            }
        };
    }

    let elems = [
        elem_ref!(0),
        elem_ref!(1),
        elem_ref!(2),
        elem_ref!(3),
        elem_ref!(4),
        elem_ref!(5),
        elem_ref!(6),
    ];

    for (idx, e) in elems.iter().enumerate() {
        let pfx = format!("CONJUGATING_ELEM[{idx}]");

        assert_match(
            &expected,
            &format!("{pfx}.denom"),
            &bigint_to_decimal(e.denom),
        );
        for k in 0..4 {
            assert_match(
                &expected,
                &format!("{pfx}.coord[{k}]"),
                &bigint_to_decimal(e.coord[k]),
            );
        }
    }
}

#[test]
fn crossvalidate_endomorphism_curves_and_bases() {
    let expected = load_expected();

    struct CurveRefs {
        a_re: &'static [u64; 5],
        a_im: &'static [u64; 5],
        c_re: &'static [u64; 5],
        c_im: &'static [u64; 5],
        a24_x_re: &'static [u64; 5],
        a24_x_im: &'static [u64; 5],
        a24_z_re: &'static [u64; 5],
        a24_z_im: &'static [u64; 5],
        p_x_re: &'static [u64; 5],
        p_x_im: &'static [u64; 5],
        p_z_re: &'static [u64; 5],
        p_z_im: &'static [u64; 5],
        q_x_re: &'static [u64; 5],
        q_x_im: &'static [u64; 5],
        q_z_re: &'static [u64; 5],
        q_z_im: &'static [u64; 5],
        pmq_x_re: &'static [u64; 5],
        pmq_x_im: &'static [u64; 5],
        pmq_z_re: &'static [u64; 5],
        pmq_z_im: &'static [u64; 5],
    }

    macro_rules! curve_ref {
        ($idx:literal) => {
            paste::paste! {
                CurveRefs {
                    a_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_A_RE>],
                    a_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_A_IM>],
                    c_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_C_RE>],
                    c_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_C_IM>],
                    a24_x_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_A24_X_RE>],
                    a24_x_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_A24_X_IM>],
                    a24_z_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_A24_Z_RE>],
                    a24_z_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _CURVE_A24_Z_IM>],
                    p_x_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_P_X_RE>],
                    p_x_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_P_X_IM>],
                    p_z_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_P_Z_RE>],
                    p_z_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_P_Z_IM>],
                    q_x_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_Q_X_RE>],
                    q_x_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_Q_X_IM>],
                    q_z_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_Q_Z_RE>],
                    q_z_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_Q_Z_IM>],
                    pmq_x_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_PMQ_X_RE>],
                    pmq_x_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_PMQ_X_IM>],
                    pmq_z_re: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_PMQ_Z_RE>],
                    pmq_z_im: &endomorphism_action::[<ENDOMORPHISM_ $idx _BASIS_PMQ_Z_IM>],
                }
            }
        };
    }

    let curves = [
        curve_ref!(0),
        curve_ref!(1),
        curve_ref!(2),
        curve_ref!(3),
        curve_ref!(4),
        curve_ref!(5),
        curve_ref!(6),
    ];

    for (idx, c) in curves.iter().enumerate() {
        let pfx = format!("ENDOMORPHISM[{idx}]");

        let checks: &[(&str, &[u64; 5])] = &[
            ("curve.A.re", c.a_re),
            ("curve.A.im", c.a_im),
            ("curve.C.re", c.c_re),
            ("curve.C.im", c.c_im),
            ("curve.A24.x.re", c.a24_x_re),
            ("curve.A24.x.im", c.a24_x_im),
            ("curve.A24.z.re", c.a24_z_re),
            ("curve.A24.z.im", c.a24_z_im),
            ("basis.P.x.re", c.p_x_re),
            ("basis.P.x.im", c.p_x_im),
            ("basis.P.z.re", c.p_z_re),
            ("basis.P.z.im", c.p_z_im),
            ("basis.Q.x.re", c.q_x_re),
            ("basis.Q.x.im", c.q_x_im),
            ("basis.Q.z.re", c.q_z_re),
            ("basis.Q.z.im", c.q_z_im),
            ("basis.PmQ.x.re", c.pmq_x_re),
            ("basis.PmQ.x.im", c.pmq_x_im),
            ("basis.PmQ.z.re", c.pmq_z_re),
            ("basis.PmQ.z.im", c.pmq_z_im),
        ];

        for (suffix, limbs) in checks {
            let key = format!("{pfx}.{suffix}");
            assert_match(&expected, &key, &fp_limbs_to_hex_csv(limbs.as_ref()));
        }
    }
}

#[test]
fn crossvalidate_endomorphism_action_matrices() {
    let expected = load_expected();

    // Rust stores row-major: [0][0], [0][1], [1][0], [1][1]
    // C prints row-major:    [0][0], [0][1], [1][0], [1][1]
    // Same order, direct index mapping.

    struct ActionRefs {
        action_i: &'static [std::sync::LazyLock<BigInt>; 4],
        action_j: &'static [std::sync::LazyLock<BigInt>; 4],
        action_k: &'static [std::sync::LazyLock<BigInt>; 4],
        action_gen2: &'static [std::sync::LazyLock<BigInt>; 4],
        action_gen3: &'static [std::sync::LazyLock<BigInt>; 4],
        action_gen4: &'static [std::sync::LazyLock<BigInt>; 4],
    }

    macro_rules! action_ref {
        ($idx:literal) => {
            paste::paste! {
                ActionRefs {
                    action_i: &endomorphism_action::[<ENDOMORPHISM_ $idx _ACTION_I>],
                    action_j: &endomorphism_action::[<ENDOMORPHISM_ $idx _ACTION_J>],
                    action_k: &endomorphism_action::[<ENDOMORPHISM_ $idx _ACTION_K>],
                    action_gen2: &endomorphism_action::[<ENDOMORPHISM_ $idx _ACTION_GEN2>],
                    action_gen3: &endomorphism_action::[<ENDOMORPHISM_ $idx _ACTION_GEN3>],
                    action_gen4: &endomorphism_action::[<ENDOMORPHISM_ $idx _ACTION_GEN4>],
                }
            }
        };
    }

    let actions = [
        action_ref!(0),
        action_ref!(1),
        action_ref!(2),
        action_ref!(3),
        action_ref!(4),
        action_ref!(5),
        action_ref!(6),
    ];

    for (idx, a) in actions.iter().enumerate() {
        let pfx = format!("ENDOMORPHISM[{idx}]");

        let matrices: &[(&str, &[std::sync::LazyLock<BigInt>; 4])] = &[
            ("action_i", a.action_i),
            ("action_j", a.action_j),
            ("action_k", a.action_k),
            ("action_gen2", a.action_gen2),
            ("action_gen3", a.action_gen3),
            ("action_gen4", a.action_gen4),
        ];

        for (name, mat) in matrices {
            for r in 0..2 {
                for c in 0..2 {
                    let key = format!("{pfx}.{name}[{r}][{c}]");
                    let rust_i = r * 2 + c;
                    let val = &*mat[rust_i];
                    assert_match(&expected, &key, &bigint_to_decimal(val));
                }
            }
        }
    }
}

#[test]
fn crossvalidate_e0_basis() {
    let expected = load_expected();

    assert_match(
        &expected,
        "BASIS_E0_PX.re",
        &fp_limbs_to_hex_csv(&e0_basis::BASIS_E0_P_X_RE),
    );
    assert_match(
        &expected,
        "BASIS_E0_PX.im",
        &fp_limbs_to_hex_csv(&e0_basis::BASIS_E0_P_X_IM),
    );
    assert_match(
        &expected,
        "BASIS_E0_QX.re",
        &fp_limbs_to_hex_csv(&e0_basis::BASIS_E0_Q_X_RE),
    );
    assert_match(
        &expected,
        "BASIS_E0_QX.im",
        &fp_limbs_to_hex_csv(&e0_basis::BASIS_E0_Q_X_IM),
    );
}

#[test]
fn crossvalidate_quaternion_constants() {
    let expected = load_expected();

    assert_match(
        &expected,
        "QUAT_PRIMALITY_NUM_ITER",
        &quaternion_constants::QUAT_PRIMALITY_NUM_ITER.to_string(),
    );
    assert_match(
        &expected,
        "QUAT_REPRES_BOUND_INPUT",
        &quaternion_constants::QUAT_REPRES_BOUND_INPUT.to_string(),
    );
    assert_match(
        &expected,
        "QUAT_EQUIV_BOUND_COEFF",
        &quaternion_constants::QUAT_EQUIV_BOUND_COEFF.to_string(),
    );
    assert_match(
        &expected,
        "FINDUV_BOX_SIZE",
        &quaternion_constants::FINDUV_BOX_SIZE.to_string(),
    );
    assert_match(
        &expected,
        "FINDUV_CUBE_SIZE",
        &quaternion_constants::FINDUV_CUBE_SIZE.to_string(),
    );
}
