//! Cross-validation tests for id2iso functions against the reference implementation.
//!
//! Expected values generated by `tools/c-validate/id2iso_cval`.

use sqisign_rs::id2iso::verify_side::mp_invert_matrix;

/// Parse a hex string of limbs (16 hex chars per limb, limb 0 first) into [u64; 4].
fn parse_digits(s: &str) -> [u64; 4] {
    assert_eq!(s.len(), 64, "expected 64 hex chars for 4 limbs");
    let mut out = [0u64; 4];
    for i in 0..4 {
        let hex = &s[i * 16..(i + 1) * 16];
        out[i] = u64::from_str_radix(hex, 16).unwrap();
    }
    out
}

fn digits_to_hex(x: &[u64]) -> String {
    x.iter().map(|d| format!("{:016x}", d)).collect::<String>()
}

#[test]
fn test_mp_invert_matrix_small() {
    let mut r1 = [3u64, 0, 0, 0];
    let mut r2 = [1u64, 0, 0, 0];
    let mut s1 = [2u64, 0, 0, 0];
    let mut s2 = [5u64, 0, 0, 0];

    mp_invert_matrix(&mut r1, &mut r2, &mut s1, &mut s2, 256, 4);

    let expected_r1 =
        parse_digits("89d89d89d89d89d9d89d89d89d89d89d9d89d89d89d89d8989d89d89d89d89d8");
    let expected_r2 =
        parse_digits("b13b13b13b13b13b3b13b13b13b13b1313b13b13b13b13b1b13b13b13b13b13b");
    let expected_s1 =
        parse_digits("6276276276276276762762762762762727627627627627626276276276276276");
    let expected_s2 =
        parse_digits("ec4ec4ec4ec4ec4f4ec4ec4ec4ec4ec4c4ec4ec4ec4ec4ecec4ec4ec4ec4ec4e");

    assert_eq!(
        r1,
        expected_r1,
        "r1 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&r1),
        digits_to_hex(&expected_r1)
    );
    assert_eq!(
        r2,
        expected_r2,
        "r2 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&r2),
        digits_to_hex(&expected_r2)
    );
    assert_eq!(
        s1,
        expected_s1,
        "s1 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&s1),
        digits_to_hex(&expected_s1)
    );
    assert_eq!(
        s2,
        expected_s2,
        "s2 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&s2),
        digits_to_hex(&expected_s2)
    );

    // Verify: original * inverse = identity mod 2^256
    verify_inverse(
        &[3, 0, 0, 0],
        &[1, 0, 0, 0],
        &[2, 0, 0, 0],
        &[5, 0, 0, 0],
        &r1,
        &r2,
        &s1,
        &s2,
        256,
    );
}

#[test]
fn test_mp_invert_matrix_large() {
    let mut r1 = [0x123456789abcdef1u64, 0x0fedcba987654321, 0, 0];
    let mut r2 = [0x1111111111111111u64, 0, 0, 0];
    let mut s1 = [0x2222222222222222u64, 0, 0, 0];
    let mut s2 = [0x3333333333333333u64, 0x4444444444444444, 0, 0];

    mp_invert_matrix(&mut r1, &mut r2, &mut s1, &mut s2, 256, 4);

    let expected_r1 =
        parse_digits("546a0c4d33f6aaf341941de8588aae1747321c7d8af9bde4e0ebf781151231fe");
    let expected_r2 =
        parse_digits("8e87513b995871af2c1a3463160683b95821b0a75ef9666794d9c1f5cfad66cc");
    let expected_s1 =
        parse_digits("1d0ea27732b0e35e583468c62c0d0773b043614ebdf2ccce29b383eb9f5acd98");
    let expected_s2 =
        parse_digits("4ba5c9d8446fb431d3117a9d9611629301279168f897e2f19b3a12257f6c8cdb");

    assert_eq!(
        r1,
        expected_r1,
        "r1 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&r1),
        digits_to_hex(&expected_r1)
    );
    assert_eq!(
        r2,
        expected_r2,
        "r2 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&r2),
        digits_to_hex(&expected_r2)
    );
    assert_eq!(
        s1,
        expected_s1,
        "s1 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&s1),
        digits_to_hex(&expected_s1)
    );
    assert_eq!(
        s2,
        expected_s2,
        "s2 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&s2),
        digits_to_hex(&expected_s2)
    );
}

#[test]
fn test_mp_invert_matrix_128() {
    let mut r1 = [7u64, 0, 0, 0];
    let mut r2 = [3u64, 0, 0, 0];
    let mut s1 = [4u64, 0, 0, 0];
    let mut s2 = [9u64, 0, 0, 0];

    mp_invert_matrix(&mut r1, &mut r2, &mut s1, &mut s2, 128, 4);

    let expected_r1 =
        parse_digits("d2d2d2d2d2d2d2d3d2d2d2d2d2d2d2d200000000000000000000000000000000");
    let expected_r2 =
        parse_digits("0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f00000000000000000000000000000000");
    let expected_s1 =
        parse_digits("1414141414141414141414141414141400000000000000000000000000000000");
    let expected_s2 =
        parse_digits("dcdcdcdcdcdcdcdddcdcdcdcdcdcdcdc00000000000000000000000000000000");

    assert_eq!(
        r1,
        expected_r1,
        "r1 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&r1),
        digits_to_hex(&expected_r1)
    );
    assert_eq!(
        r2,
        expected_r2,
        "r2 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&r2),
        digits_to_hex(&expected_r2)
    );
    assert_eq!(
        s1,
        expected_s1,
        "s1 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&s1),
        digits_to_hex(&expected_s1)
    );
    assert_eq!(
        s2,
        expected_s2,
        "s2 mismatch:\n  got:  {}\n  want: {}",
        digits_to_hex(&s2),
        digits_to_hex(&expected_s2)
    );
}

/// Verify that original * inverse = identity mod 2^e.
#[allow(clippy::too_many_arguments)]
fn verify_inverse(
    a: &[u64; 4],
    b: &[u64; 4],
    c: &[u64; 4],
    d: &[u64; 4],
    inv_a: &[u64; 4],
    inv_b: &[u64; 4],
    inv_c: &[u64; 4],
    inv_d: &[u64; 4],
    e: usize,
) {
    let check00 = mp_mul_add_mod(a, inv_a, b, inv_c, e);
    let check01 = mp_mul_add_mod(a, inv_b, b, inv_d, e);
    let check10 = mp_mul_add_mod(c, inv_a, d, inv_c, e);
    let check11 = mp_mul_add_mod(c, inv_b, d, inv_d, e);

    assert_eq!(check00, [1, 0, 0, 0], "M*M^-1 [0][0] != 1");
    assert_eq!(check01, [0, 0, 0, 0], "M*M^-1 [0][1] != 0");
    assert_eq!(check10, [0, 0, 0, 0], "M*M^-1 [1][0] != 0");
    assert_eq!(check11, [1, 0, 0, 0], "M*M^-1 [1][1] != 1");
}

/// Compute (a*b + c*d) mod 2^e as [u64; 4].
fn mp_mul_add_mod(a: &[u64; 4], b: &[u64; 4], c: &[u64; 4], d: &[u64; 4], e: usize) -> [u64; 4] {
    let ab = widening_mul(a, b);
    let cd = widening_mul(c, d);
    let mut sum = [0u64; 4];
    let mut carry = 0u64;
    for i in 0..4 {
        let s = (ab[i] as u128) + (cd[i] as u128) + (carry as u128);
        sum[i] = s as u64;
        carry = (s >> 64) as u64;
    }
    mod_2exp(&mut sum, e);
    sum
}

fn widening_mul(a: &[u64; 4], b: &[u64; 4]) -> [u64; 4] {
    let mut out = [0u64; 4];
    for i in 0..4 {
        let mut carry = 0u64;
        for j in 0..4 {
            if i + j >= 4 {
                break;
            }
            let p = (a[i] as u128) * (b[j] as u128) + (out[i + j] as u128) + (carry as u128);
            out[i + j] = p as u64;
            carry = (p >> 64) as u64;
        }
    }
    out
}

fn mod_2exp(x: &mut [u64; 4], e: usize) {
    let full_words = e / 64;
    let rem = e % 64;
    for val in x.iter_mut().skip(full_words + 1) {
        *val = 0;
    }
    if full_words < 4 {
        if rem > 0 {
            x[full_words] &= (1u64 << rem) - 1;
        } else {
            x[full_words] = 0;
        }
    }
}
