//!
//! These control search bounds, iteration limits, and table sizes in the
//! quaternion ideal algorithms (norm equations, equivalent ideals).
//!
//! Generated by SageMath precompute scripts. DO NOT EDIT.

/// Repetition parameter for primality testing of ideal norms.
pub const QUAT_PRIMALITY_NUM_ITER: u32 = 32;

/// Bound on the search radius when finding representations of integers
/// as norms of quaternion elements (Cornacchia-like enumeration).
pub const QUAT_REPRES_BOUND_INPUT: u32 = 20;

/// Coefficient bound for the lattice enumeration when testing ideal
/// equivalence. Larger values find more equivalences at higher cost.
pub const QUAT_EQUIV_BOUND_COEFF: i32 = 64;

/// Half-side length of the 4D hypercube enumeration in `find_uv`.
pub const FINDUV_BOX_SIZE: u32 = 2;

/// Cube size parameter for `find_uv` enumeration.
pub const FINDUV_CUBE_SIZE: u32 = 624;

/// Total number of precomputed extremal maximal orders (including the
/// primary order O0).
pub const NUM_EXTREMAL_ORDERS: usize = 7;

/// Number of alternate extremal orders (excluding O0). Used for
/// fallback paths in ideal-to-isogeny translation.
pub const NUM_ALTERNATE_EXTREMAL_ORDERS: usize = 6;
