//! and conjugating elements.
//!
//! Generated by SageMath precompute scripts. DO NOT EDIT.

#![allow(non_snake_case)]
use num_bigint::BigInt;

type Ibz = BigInt;

fn ibz(s: &str) -> Ibz {
    s.parse::<Ibz>()
        .expect("invariant: precomputed constant must parse")
}

/// Prime cofactor for random ideal generation: next_prime(2^251)
pub fn QUAT_PRIME_COFACTOR() -> Ibz {
    ibz("3618502788666131106986593281521497120414687020801267626233049500247285301313")
}

/// The quaternion algebra prime p.
pub fn QUATALG_P() -> Ibz {
    ibz("2261564242916331941866620800950935700259179388000792266395655937654553313279")
}

/// Number of precomputed extremal orders.
pub const NUM_ORDERS: usize = 7;

// Precomputed p-extremal maximal orders.
//
// Each order is represented as:
// - `q`: the level (1 for standard O0, prime q for alternates)
// - `order_denom`: denominator of the order basis matrix
// - `order_basis`: 4x4 basis matrix (row-major)
// - `i_denom`: denominator of sqrt(-q) in the order
// - `i_coord`: coordinates of sqrt(-q)
// - `j_denom`: denominator of sqrt(-p) (always 1)
// - `j_coord`: coordinates of sqrt(-p) (always [0,0,1,0])

pub static EXTREMAL_ORDER_0_Q: i64 = 1;
pub fn EXTREMAL_ORDER_0_DENOM() -> Ibz {
    ibz("2")
}
pub fn EXTREMAL_ORDER_0_BASIS_00() -> Ibz {
    ibz("2")
}
pub fn EXTREMAL_ORDER_0_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_03() -> Ibz {
    ibz("1")
}
pub fn EXTREMAL_ORDER_0_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_11() -> Ibz {
    ibz("2")
}
pub fn EXTREMAL_ORDER_0_BASIS_12() -> Ibz {
    ibz("1")
}
pub fn EXTREMAL_ORDER_0_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn EXTREMAL_ORDER_0_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn EXTREMAL_ORDER_0_I_DENOM() -> Ibz {
    ibz("2")
}
pub fn EXTREMAL_ORDER_0_I_COORD_0() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_I_COORD_1() -> Ibz {
    ibz("2")
}
pub fn EXTREMAL_ORDER_0_I_COORD_2() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_0_I_COORD_3() -> Ibz {
    ibz("0")
}

pub static EXTREMAL_ORDER_1_Q: i64 = 5;
pub fn EXTREMAL_ORDER_1_DENOM() -> Ibz {
    ibz("21267647932558653966460912964485513216")
}
pub fn EXTREMAL_ORDER_1_BASIS_00() -> Ibz {
    ibz("21267647932558653966460912964485513216")
}
pub fn EXTREMAL_ORDER_1_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_02() -> Ibz {
    ibz("10633823966279326983230456482242756608")
}
pub fn EXTREMAL_ORDER_1_BASIS_03() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_11() -> Ibz {
    ibz("-1")
}
pub fn EXTREMAL_ORDER_1_BASIS_12() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_13() -> Ibz {
    ibz("-226156424291633194186662080095093570025917938800079226639565593765455331328")
}
pub fn EXTREMAL_ORDER_1_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_22() -> Ibz {
    ibz("10633823966279326983230456482242756608")
}
pub fn EXTREMAL_ORDER_1_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_31() -> Ibz {
    ibz("-1")
}
pub fn EXTREMAL_ORDER_1_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_BASIS_33() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_I_DENOM() -> Ibz {
    ibz("21267647932558653966460912964485513216")
}
pub fn EXTREMAL_ORDER_1_I_COORD_0() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_I_COORD_1() -> Ibz {
    ibz("-1")
}
pub fn EXTREMAL_ORDER_1_I_COORD_2() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_1_I_COORD_3() -> Ibz {
    ibz("-1")
}

pub static EXTREMAL_ORDER_2_Q: i64 = 17;
pub fn EXTREMAL_ORDER_2_DENOM() -> Ibz {
    ibz("245182225149868003796196138577400527060")
}
pub fn EXTREMAL_ORDER_2_BASIS_00() -> Ibz {
    ibz("245182225149868003796196138577400527060")
}
pub fn EXTREMAL_ORDER_2_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_02() -> Ibz {
    ibz("122591112574934001898098069288700263530")
}
pub fn EXTREMAL_ORDER_2_BASIS_03() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_11() -> Ibz {
    ibz("606919627131690061891065823639604854087")
}
pub fn EXTREMAL_ORDER_2_BASIS_12() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_13() -> Ibz {
    ibz("1130782121458165970933310400475467850290244889417608208404286569202466176839")
}
pub fn EXTREMAL_ORDER_2_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_22() -> Ibz {
    ibz("122591112574934001898098069288700263530")
}
pub fn EXTREMAL_ORDER_2_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_31() -> Ibz {
    ibz("17")
}
pub fn EXTREMAL_ORDER_2_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_BASIS_33() -> Ibz {
    ibz("-17850577268579119467384288930576613351")
}
pub fn EXTREMAL_ORDER_2_I_DENOM() -> Ibz {
    ibz("245182225149868003796196138577400527060")
}
pub fn EXTREMAL_ORDER_2_I_COORD_0() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_I_COORD_1() -> Ibz {
    ibz("606919627131690061891065823639604854087")
}
pub fn EXTREMAL_ORDER_2_I_COORD_2() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_2_I_COORD_3() -> Ibz {
    ibz("17")
}

pub static EXTREMAL_ORDER_3_Q: i64 = 37;
pub fn EXTREMAL_ORDER_3_DENOM() -> Ibz {
    ibz("31343866351284281315972180222393312738")
}
pub fn EXTREMAL_ORDER_3_BASIS_00() -> Ibz {
    ibz("31343866351284281315972180222393312738")
}
pub fn EXTREMAL_ORDER_3_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_02() -> Ibz {
    ibz("15671933175642140657986090111196656369")
}
pub fn EXTREMAL_ORDER_3_BASIS_03() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_11() -> Ibz {
    ibz("-12852103084087684247989675327603880058")
}
pub fn EXTREMAL_ORDER_3_BASIS_12() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_13() -> Ibz {
    ibz("122246715833315240100898421673023551362755891969484510835983494874380473679")
}
pub fn EXTREMAL_ORDER_3_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_22() -> Ibz {
    ibz("15671933175642140657986090111196656369")
}
pub fn EXTREMAL_ORDER_3_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_31() -> Ibz {
    ibz("4")
}
pub fn EXTREMAL_ORDER_3_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_BASIS_33() -> Ibz {
    ibz("173677068703887624972833450373025407")
}
pub fn EXTREMAL_ORDER_3_I_DENOM() -> Ibz {
    ibz("31343866351284281315972180222393312738")
}
pub fn EXTREMAL_ORDER_3_I_COORD_0() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_I_COORD_1() -> Ibz {
    ibz("-12852103084087684247989675327603880058")
}
pub fn EXTREMAL_ORDER_3_I_COORD_2() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_3_I_COORD_3() -> Ibz {
    ibz("4")
}

pub static EXTREMAL_ORDER_4_Q: i64 = 41;
pub fn EXTREMAL_ORDER_4_DENOM() -> Ibz {
    ibz("61109756063996575029159215803231285154")
}
pub fn EXTREMAL_ORDER_4_BASIS_00() -> Ibz {
    ibz("61109756063996575029159215803231285154")
}
pub fn EXTREMAL_ORDER_4_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_02() -> Ibz {
    ibz("30554878031998287514579607901615642577")
}
pub fn EXTREMAL_ORDER_4_BASIS_03() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_11() -> Ibz {
    ibz("91489792805550548189500963350249200950")
}
pub fn EXTREMAL_ORDER_4_BASIS_12() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_13() -> Ibz {
    ibz("-220640413943056774816255687897652263418721085862205825799569868263191362051")
}
pub fn EXTREMAL_ORDER_4_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_22() -> Ibz {
    ibz("30554878031998287514579607901615642577")
}
pub fn EXTREMAL_ORDER_4_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_31() -> Ibz {
    ibz("-8")
}
pub fn EXTREMAL_ORDER_4_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_BASIS_33() -> Ibz {
    ibz("-1115729180555494490115865406710356111")
}
pub fn EXTREMAL_ORDER_4_I_DENOM() -> Ibz {
    ibz("61109756063996575029159215803231285154")
}
pub fn EXTREMAL_ORDER_4_I_COORD_0() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_I_COORD_1() -> Ibz {
    ibz("91489792805550548189500963350249200950")
}
pub fn EXTREMAL_ORDER_4_I_COORD_2() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_4_I_COORD_3() -> Ibz {
    ibz("-8")
}

pub static EXTREMAL_ORDER_5_Q: i64 = 53;
pub fn EXTREMAL_ORDER_5_DENOM() -> Ibz {
    ibz("504767425197178039123703057460015896228")
}
pub fn EXTREMAL_ORDER_5_BASIS_00() -> Ibz {
    ibz("504767425197178039123703057460015896228")
}
pub fn EXTREMAL_ORDER_5_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_02() -> Ibz {
    ibz("252383712598589019561851528730007948114")
}
pub fn EXTREMAL_ORDER_5_BASIS_03() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_11() -> Ibz {
    ibz("-2674162332259959516220178679035231564771")
}
pub fn EXTREMAL_ORDER_5_BASIS_12() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_13() -> Ibz {
    ibz("1130782121458165970933310400475467848943876207054942385439824214915428698675")
}
pub fn EXTREMAL_ORDER_5_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_22() -> Ibz {
    ibz("252383712598589019561851528730007948114")
}
pub fn EXTREMAL_ORDER_5_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_31() -> Ibz {
    ibz("53")
}
pub fn EXTREMAL_ORDER_5_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_BASIS_33() -> Ibz {
    ibz("25227946530754335058680930934294637427")
}
pub fn EXTREMAL_ORDER_5_I_DENOM() -> Ibz {
    ibz("504767425197178039123703057460015896228")
}
pub fn EXTREMAL_ORDER_5_I_COORD_0() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_I_COORD_1() -> Ibz {
    ibz("-2674162332259959516220178679035231564771")
}
pub fn EXTREMAL_ORDER_5_I_COORD_2() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_5_I_COORD_3() -> Ibz {
    ibz("53")
}

pub static EXTREMAL_ORDER_6_Q: i64 = 97;
pub fn EXTREMAL_ORDER_6_DENOM() -> Ibz {
    ibz("5362313252833514217909272354244692770810")
}
pub fn EXTREMAL_ORDER_6_BASIS_00() -> Ibz {
    ibz("5362313252833514217909272354244692770810")
}
pub fn EXTREMAL_ORDER_6_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_02() -> Ibz {
    ibz("2681156626416757108954636177122346385405")
}
pub fn EXTREMAL_ORDER_6_BASIS_03() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_11() -> Ibz {
    ibz("-37779854715767072173888284957021506833686")
}
pub fn EXTREMAL_ORDER_6_BASIS_12() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_13() -> Ibz {
    ibz("9046256971665327767466483203803742791104900075177804731209930282535239807147")
}
pub fn EXTREMAL_ORDER_6_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_22() -> Ibz {
    ibz("2681156626416757108954636177122346385405")
}
pub fn EXTREMAL_ORDER_6_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_31() -> Ibz {
    ibz("776")
}
pub fn EXTREMAL_ORDER_6_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_BASIS_33() -> Ibz {
    ibz("194741519153438516360248891531038695223")
}
pub fn EXTREMAL_ORDER_6_I_DENOM() -> Ibz {
    ibz("5362313252833514217909272354244692770810")
}
pub fn EXTREMAL_ORDER_6_I_COORD_0() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_I_COORD_1() -> Ibz {
    ibz("-37779854715767072173888284957021506833686")
}
pub fn EXTREMAL_ORDER_6_I_COORD_2() -> Ibz {
    ibz("0")
}
pub fn EXTREMAL_ORDER_6_I_COORD_3() -> Ibz {
    ibz("776")
}

// Connecting ideal 0 (q=1)
pub fn CONNECTING_IDEAL_0_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_0_BASIS_00() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_0_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_03() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_0_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_11() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_0_BASIS_12() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_0_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_0_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_0_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_0_NORM() -> Ibz {
    ibz("1")
}

// Connecting ideal 1 (q=5)
pub fn CONNECTING_IDEAL_1_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_1_BASIS_00() -> Ibz {
    ibz("127605887595351923798765477786913079298")
}
pub fn CONNECTING_IDEAL_1_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_03() -> Ibz {
    ibz("21267647932558653966460912964485513217")
}
pub fn CONNECTING_IDEAL_1_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_11() -> Ibz {
    ibz("127605887595351923798765477786913079298")
}
pub fn CONNECTING_IDEAL_1_BASIS_12() -> Ibz {
    ibz("106338239662793269832304564822427566081")
}
pub fn CONNECTING_IDEAL_1_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_1_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_1_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_1_NORM() -> Ibz {
    ibz("63802943797675961899382738893456539649")
}

// Connecting ideal 2 (q=17)
pub fn CONNECTING_IDEAL_2_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_2_BASIS_00() -> Ibz {
    ibz("160777652418025160432629685951457916414")
}
pub fn CONNECTING_IDEAL_2_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_03() -> Ibz {
    ibz("7566296959877291146913093652505689829")
}
pub fn CONNECTING_IDEAL_2_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_11() -> Ibz {
    ibz("160777652418025160432629685951457916414")
}
pub fn CONNECTING_IDEAL_2_BASIS_12() -> Ibz {
    ibz("153211355458147869285716592298952226585")
}
pub fn CONNECTING_IDEAL_2_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_2_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_2_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_2_NORM() -> Ibz {
    ibz("80388826209012580216314842975728958207")
}

// Connecting ideal 3 (q=37)
pub fn CONNECTING_IDEAL_3_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_3_BASIS_00() -> Ibz {
    ibz("31343866351284281315972180222393312738")
}
pub fn CONNECTING_IDEAL_3_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_03() -> Ibz {
    ibz("11048992358842991390990463887499298199")
}
pub fn CONNECTING_IDEAL_3_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_11() -> Ibz {
    ibz("31343866351284281315972180222393312738")
}
pub fn CONNECTING_IDEAL_3_BASIS_12() -> Ibz {
    ibz("20294873992441289924981716334894014539")
}
pub fn CONNECTING_IDEAL_3_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_3_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_3_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_3_NORM() -> Ibz {
    ibz("15671933175642140657986090111196656369")
}

// Connecting ideal 4 (q=41)
pub fn CONNECTING_IDEAL_4_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_4_BASIS_00() -> Ibz {
    ibz("61109756063996575029159215803231285154")
}
pub fn CONNECTING_IDEAL_4_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_03() -> Ibz {
    ibz("19074943608693390402332522394185060763")
}
pub fn CONNECTING_IDEAL_4_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_11() -> Ibz {
    ibz("61109756063996575029159215803231285154")
}
pub fn CONNECTING_IDEAL_4_BASIS_12() -> Ibz {
    ibz("42034812455303184626826693409046224391")
}
pub fn CONNECTING_IDEAL_4_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_4_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_4_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_4_NORM() -> Ibz {
    ibz("30554878031998287514579607901615642577")
}

// Connecting ideal 5 (q=53)
pub fn CONNECTING_IDEAL_5_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_5_BASIS_00() -> Ibz {
    ibz("238306336656231922442397201726960835058")
}
pub fn CONNECTING_IDEAL_5_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_03() -> Ibz {
    ibz("2836324646680553218899309278021737427")
}
pub fn CONNECTING_IDEAL_5_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_11() -> Ibz {
    ibz("238306336656231922442397201726960835058")
}
pub fn CONNECTING_IDEAL_5_BASIS_12() -> Ibz {
    ibz("235470012009551369223497892448939097631")
}
pub fn CONNECTING_IDEAL_5_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_5_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_5_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_5_NORM() -> Ibz {
    ibz("119153168328115961221198600863480417529")
}

// Connecting ideal 6 (q=97)
pub fn CONNECTING_IDEAL_6_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONNECTING_IDEAL_6_BASIS_00() -> Ibz {
    ibz("55281579926118703277415178909739100730")
}
pub fn CONNECTING_IDEAL_6_BASIS_01() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_02() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_03() -> Ibz {
    ibz("27326792610053587916383648118131589749")
}
pub fn CONNECTING_IDEAL_6_BASIS_10() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_11() -> Ibz {
    ibz("55281579926118703277415178909739100730")
}
pub fn CONNECTING_IDEAL_6_BASIS_12() -> Ibz {
    ibz("27954787316065115361031530791607510981")
}
pub fn CONNECTING_IDEAL_6_BASIS_13() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_20() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_21() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_22() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_6_BASIS_23() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_30() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_31() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_32() -> Ibz {
    ibz("0")
}
pub fn CONNECTING_IDEAL_6_BASIS_33() -> Ibz {
    ibz("1")
}
pub fn CONNECTING_IDEAL_6_NORM() -> Ibz {
    ibz("27640789963059351638707589454869550365")
}

// Conjugating element 0 (q=1)
pub fn CONJUGATING_ELEM_0_DENOM() -> Ibz {
    ibz("1")
}
pub fn CONJUGATING_ELEM_0_COORD_0() -> Ibz {
    ibz("1")
}
pub fn CONJUGATING_ELEM_0_COORD_1() -> Ibz {
    ibz("0")
}
pub fn CONJUGATING_ELEM_0_COORD_2() -> Ibz {
    ibz("0")
}
pub fn CONJUGATING_ELEM_0_COORD_3() -> Ibz {
    ibz("0")
}

// Conjugating element 1 (q=5)
pub fn CONJUGATING_ELEM_1_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONJUGATING_ELEM_1_COORD_0() -> Ibz {
    ibz("21267647932558653966460912964485513217")
}
pub fn CONJUGATING_ELEM_1_COORD_1() -> Ibz {
    ibz("-21267647932558653966460912964485513217")
}
pub fn CONJUGATING_ELEM_1_COORD_2() -> Ibz {
    ibz("1")
}
pub fn CONJUGATING_ELEM_1_COORD_3() -> Ibz {
    ibz("-1")
}

// Conjugating element 2 (q=17)
pub fn CONJUGATING_ELEM_2_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONJUGATING_ELEM_2_COORD_0() -> Ibz {
    ibz("138078761538393286991890404993940846927")
}
pub fn CONJUGATING_ELEM_2_COORD_1() -> Ibz {
    ibz("-138078761538393286991890404993940846927")
}
pub fn CONJUGATING_ELEM_2_COORD_2() -> Ibz {
    ibz("-3")
}
pub fn CONJUGATING_ELEM_2_COORD_3() -> Ibz {
    ibz("3")
}

// Conjugating element 3 (q=37)
pub fn CONJUGATING_ELEM_3_DENOM() -> Ibz {
    ibz("1")
}
pub fn CONJUGATING_ELEM_3_COORD_0() -> Ibz {
    ibz("15671933175642140657986090111196656369")
}
pub fn CONJUGATING_ELEM_3_COORD_1() -> Ibz {
    ibz("-15671933175642140657986090111196656369")
}
pub fn CONJUGATING_ELEM_3_COORD_2() -> Ibz {
    ibz("0")
}
pub fn CONJUGATING_ELEM_3_COORD_3() -> Ibz {
    ibz("0")
}

// Conjugating element 4 (q=41)
pub fn CONJUGATING_ELEM_4_DENOM() -> Ibz {
    ibz("1")
}
pub fn CONJUGATING_ELEM_4_COORD_0() -> Ibz {
    ibz("30554878031998287514579607901615642577")
}
pub fn CONJUGATING_ELEM_4_COORD_1() -> Ibz {
    ibz("-30554878031998287514579607901615642577")
}
pub fn CONJUGATING_ELEM_4_COORD_2() -> Ibz {
    ibz("0")
}
pub fn CONJUGATING_ELEM_4_COORD_3() -> Ibz {
    ibz("0")
}

// Conjugating element 5 (q=53)
pub fn CONJUGATING_ELEM_5_DENOM() -> Ibz {
    ibz("2")
}
pub fn CONJUGATING_ELEM_5_COORD_0() -> Ibz {
    ibz("252487959889634688536893748117069522193")
}
pub fn CONJUGATING_ELEM_5_COORD_1() -> Ibz {
    ibz("-252487959889634688536893748117069522193")
}
pub fn CONJUGATING_ELEM_5_COORD_2() -> Ibz {
    ibz("5")
}
pub fn CONJUGATING_ELEM_5_COORD_3() -> Ibz {
    ibz("-5")
}

// Conjugating element 6 (q=97)
pub fn CONJUGATING_ELEM_6_DENOM() -> Ibz {
    ibz("1")
}
pub fn CONJUGATING_ELEM_6_COORD_0() -> Ibz {
    ibz("194741519153438516360248891531038695019")
}
pub fn CONJUGATING_ELEM_6_COORD_1() -> Ibz {
    ibz("-194741519153438516360248891531038695019")
}
pub fn CONJUGATING_ELEM_6_COORD_2() -> Ibz {
    ibz("-4")
}
pub fn CONJUGATING_ELEM_6_COORD_3() -> Ibz {
    ibz("4")
}
