//!
//! These large integers parameterize the sigma protocol: they determine
//! the torsion group sizes and the degrees of the commitment and
//! challenge isogenies.
//!
//! Generated by SageMath precompute scripts. DO NOT EDIT.

#![allow(non_snake_case)]
use num_bigint::BigInt;

type Ibz = BigInt;

fn ibz(s: &str) -> Ibz {
    match s.parse::<Ibz>() {
        Ok(v) => v,
        Err(_) => panic!("corrupt precomputed constant"),
    }
}

/// Byte length of `2^TORSION_EVEN_POWER` (= `2²⁴⁸` for Level 1 = 32 bytes).
pub const TORSION_2POWER_BYTES: usize = 32;

/// `2^128`: used as the modulus for challenge scalars (`2^LAMBDA`).
pub fn TWO_TO_SECURITY_BITS() -> Ibz {
    ibz("340282366920938463463374607431768211456")
}

/// `2²⁴⁸`: the full even torsion `|E0[2ᶠ]| = (2ᶠ)²`, but stored
/// here as the single power `2ᶠ` for scalar arithmetic.
pub fn TORSION_PLUS_2POWER() -> Ibz {
    ibz("452312848583266388373324160190187140051835877600158453279131187530910662656")
}

/// Prescribed norm for random ideal sampling in keygen:
/// `next_prime(2^(4 * LAMBDA))` where `LAMBDA = 128` for Level 1
/// (= `next_prime(2^512)` = `2^512 + 75`).
pub fn SEC_DEGREE() -> Ibz {
    ibz("13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084171")
}

/// Prescribed norm for commitment ideal sampling in signing
/// (equal to `SEC_DEGREE`).
pub fn COM_DEGREE() -> Ibz {
    ibz("13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084171")
}
