//! Precomputed curve constants per prime: the deterministic basis of
//! `E0[2^f]` on `E0: y^2 = x^3 + x` and a few derived sizes.
//!
//! The files are generated by `tools/gen-precomp` from the prime alone and
//! checked value-for-value against the SQIsign reference implementation.
//! See PRECOMP.md at the workspace root for the inventory.

pub mod p324_3;
pub mod p500_27;
pub mod p664_17;

/// Extra 2-torsion the isogeny layers keep above the working length
/// (`EC_EXTRA_TORSION` and `HD_EXTRA_TORSION` in the reference).
pub const EXTRA_TORSION: u32 = 2;

/// Access to a prime's precomputed curve constants from generic code.
pub trait PrimePrecomp: crate::params::Prime {
    /// Canonical `Fp2` bytes of `x(P0)`, first generator of `E0[2^f]`.
    fn e0_basis_px() -> &'static [u8];
    /// Canonical `Fp2` bytes of `x(Q0)`, second generator, above `(0, 0)`.
    fn e0_basis_qx() -> &'static [u8];
    /// Canonical `Fp2` bytes of `x(P0 - Q0)`.
    fn e0_basis_pmqx() -> &'static [u8];
}

macro_rules! impl_precomp {
    ($prime:ty, $module:ident) => {
        impl PrimePrecomp for $prime {
            fn e0_basis_px() -> &'static [u8] {
                &$module::E0_BASIS_PX
            }
            fn e0_basis_qx() -> &'static [u8] {
                &$module::E0_BASIS_QX
            }
            fn e0_basis_pmqx() -> &'static [u8] {
                &$module::E0_BASIS_PMQX
            }
        }
    };
}

impl_precomp!(crate::params::P324_3, p324_3);
impl_precomp!(crate::params::P500_27, p500_27);
impl_precomp!(crate::params::P664_17, p664_17);
