//!
//! Generated by SageMath precompute scripts. DO NOT EDIT.

pub const QUAT_PRIMALITY_NUM_ITER: u32 = 32;
pub const QUAT_REPRES_BOUND_INPUT: u32 = 21;
pub const QUAT_EQUIV_BOUND_COEFF: i32 = 64;
pub const FINDUV_BOX_SIZE: u32 = 3;
pub const FINDUV_CUBE_SIZE: u32 = 2400;
pub const NUM_EXTREMAL_ORDERS: usize = 8;
pub const NUM_ALTERNATE_EXTREMAL_ORDERS: usize = 7;
