//! (2, 2)-isogeny chains between products of elliptic curves in the theta
//! model, following the SQIsign round-3 reference (`src/hd`) and spec
//! Section 4.5.
//!
//! A chain of length `n` computes a `(2^n, 2^n)`-isogeny `E1 x E2 -> E3 x
//! E4` from a kernel given by two couple points of order `2^(n + 2)` whose
//! `[4]`-multiples generate it. The first step glues the product into a
//! level-2 theta structure, the middle steps are generic theta isogenies,
//! and the last step splits back to a product of Montgomery curves in
//! canonical form.

use crate::ec::{EcCurve, EcPoint};
use crate::fp::{Fp2, FpBackend};
use crate::params::Prime;

pub mod chain;
pub mod gluing;
pub mod isogeny;
pub mod splitting;
pub mod structure;

/// A point in level-2 theta coordinates `(x : y : z : t)`.
#[derive(Clone, Debug)]
pub struct ThetaPoint<L: Prime> {
    /// First coordinate.
    pub x: Fp2<L>,
    /// Second coordinate.
    pub y: Fp2<L>,
    /// Third coordinate.
    pub z: Fp2<L>,
    /// Fourth coordinate.
    pub t: Fp2<L>,
}

/// A theta structure on a principally polarised abelian surface: the data
/// needed to double and to evaluate isogenies from it.
#[derive(Clone, Debug)]
pub struct ThetaStructure<L: Prime> {
    /// Coordinate-wise inverse of the dual theta null point.
    pub inv_dual_null_point: ThetaPoint<L>,
    /// Intermediate values from the isogeny that produced this structure,
    /// from which the dual null point can be rebuilt cheaply.
    pub dbl_data: ThetaPoint<L>,
    /// Inverse of the squared (Hadamard-transformed) dual null point, for
    /// doubling.
    pub inv_sqr_null_point: ThetaPoint<L>,
    /// Whether `inv_sqr_null_point` has been computed.
    pub precomputation: bool,
}

/// A point on a product `E1 x E2`, both components on the Kummer line.
#[derive(Clone, Debug)]
pub struct ThetaCouplePoint<L: Prime> {
    /// Component on `E1`.
    pub p1: EcPoint<L>,
    /// Component on `E2`.
    pub p2: EcPoint<L>,
}

/// Two couple points generating (after multiplication by 4) the kernel.
#[derive(Clone, Debug)]
pub struct ThetaKernelCouplePoints<L: Prime> {
    /// First generator.
    pub t1: ThetaCouplePoint<L>,
    /// Second generator.
    pub t2: ThetaCouplePoint<L>,
}

/// Which codomain factors a chain brings to canonical Montgomery form, and
/// whether the extra consistency checks of signature verification run.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ChainMode {
    /// Normalise both `E3` and `E4`.
    Both,
    /// Normalise only `E3`.
    E1,
    /// Normalise only `E4`.
    E2,
    /// Normalise `E3`, check `E4`'s null point, and verify the kernel at each
    /// step: the mode used by signature verification.
    Verify,
}

/// A product of two Montgomery curves.
#[derive(Clone, Debug)]
pub struct ThetaCoupleCurve<L: Prime> {
    /// First factor.
    pub e1: EcCurve<L>,
    /// Second factor.
    pub e2: EcCurve<L>,
}

impl<L: FpBackend> ThetaPoint<L> {
    /// `(x : y : z : t)`.
    #[inline]
    pub fn new(x: Fp2<L>, y: Fp2<L>, z: Fp2<L>, t: Fp2<L>) -> Self {
        Self { x, y, z, t }
    }

    /// `(0 : 0 : 0 : 0)`, a placeholder.
    #[inline]
    pub fn zero() -> Self {
        Self {
            x: Fp2::zero(),
            y: Fp2::zero(),
            z: Fp2::zero(),
            t: Fp2::zero(),
        }
    }
}

impl<L: FpBackend> ThetaCouplePoint<L> {
    /// `(p1, p2)`.
    #[inline]
    pub fn new(p1: EcPoint<L>, p2: EcPoint<L>) -> Self {
        Self { p1, p2 }
    }

    /// `(p, 0)`.
    #[inline]
    pub fn on_e1(p: EcPoint<L>) -> Self {
        Self {
            p1: p,
            p2: EcPoint::identity(),
        }
    }

    /// `(0, p)`.
    #[inline]
    pub fn on_e2(p: EcPoint<L>) -> Self {
        Self {
            p1: EcPoint::identity(),
            p2: p,
        }
    }

    /// `[2] (P1, P2)`.
    #[inline]
    pub fn double(&self, e12: &ThetaCoupleCurve<L>) -> Self {
        Self {
            p1: crate::ec::point::ec_dbl(&self.p1, &e12.e1),
            p2: crate::ec::point::ec_dbl(&self.p2, &e12.e2),
        }
    }

    /// `[2^n] (P1, P2)`.
    #[inline]
    pub fn double_iter(&self, n: u16, e12: &ThetaCoupleCurve<L>) -> Self {
        let mut out = self.clone();
        for _ in 0..n {
            out = out.double(e12);
        }
        out
    }
}

impl<L: FpBackend> ThetaKernelCouplePoints<L> {
    /// The kernel generated by `(B1.P, B2.P)` and `(B1.Q, B2.Q)` for bases
    /// `B1` of `E1` and `B2` of `E2`.
    #[inline]
    pub fn from_bases(b1: &crate::ec::EcBasis<L>, b2: &crate::ec::EcBasis<L>) -> Self {
        Self {
            t1: ThetaCouplePoint::new(b1.p.clone(), b2.p.clone()),
            t2: ThetaCouplePoint::new(b1.q.clone(), b2.q.clone()),
        }
    }
}
