//! Prime-field arithmetic `Fp` and its quadratic extension `Fp2`.
//!
//! All primes satisfy `p = 3 mod 4`, so `Fp2 = Fp[i] / (i^2 + 1)`.
//! Arithmetic is in Montgomery form; results of `add`, `sub`, `neg`,
//! `mul`, `sqr` and `mul_small` are lazily reduced to `[0, 2p)` and the
//! final reduction happens in encoding and comparison.
//!
//! Each prime has its own unrolled backend module implementing
//! [`FpBackend`]; [`Fp`] and [`Fp2`] are the stable generic surface over
//! `L: FpBackend`. On x86-64 the round-3 primes use the saturated-limb
//! modules generated by `tools/gen-fp-asm` (assembly or portable kernels,
//! chosen at run time by [`dispatch`]); elsewhere, and for the other
//! primes, the unsaturated radix modules generated by `tools/gen-fp`.

use crate::params::Prime;
use hybrid_array::Array;
pub use subtle::Choice;
use zeroize::Zeroize;

#[allow(clippy::module_inception)]
pub mod fp;
pub mod fp2;

/// Run-time choice between the assembly and the portable kernels of the
/// x86-64 backends.
#[cfg(target_arch = "x86_64")]
#[allow(unsafe_code)] // `cpuid` through `core::arch`
pub mod dispatch;
pub mod p324_3;
/// The round-3 primes on x86-64: saturated limbs, inline-assembly
/// multiplication when the CPU has BMI2 and ADX, portable Rust otherwise
/// (generated by `tools/gen-fp-asm/gen_fp_asm.py`).
#[cfg(target_arch = "x86_64")]
#[allow(unsafe_code)] // the `asm!` blocks of the crate, and their calls
pub mod p324_3_asm;
pub mod p500_27;
/// Level III, as [`p324_3_asm`].
#[cfg(target_arch = "x86_64")]
#[allow(unsafe_code)]
pub mod p500_27_asm;
pub mod p664_17;
/// Level V, as [`p324_3_asm`].
#[cfg(target_arch = "x86_64")]
#[allow(unsafe_code)]
pub mod p664_17_asm;

/// Use the portable field kernels from now on (x86-64; a no-op elsewhere,
/// where they are the only kernels). For tests and CI, which run the
/// known-answer tests under both paths.
pub fn force_portable_arithmetic() {
    #[cfg(target_arch = "x86_64")]
    dispatch::force_portable();
}

/// Undo [`force_portable_arithmetic`]: detect the CPU again on the next
/// operation.
pub fn force_auto_arithmetic() {
    #[cfg(target_arch = "x86_64")]
    dispatch::force_auto();
}

/// The field kernels in use, for benchmark headers.
pub fn arithmetic_backend() -> &'static str {
    #[cfg(target_arch = "x86_64")]
    {
        dispatch::backend()
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        "portable (unsaturated radix)"
    }
}

/// A prime-field element in the backend's internal Montgomery form.
///
/// The limb layout is an implementation detail of each backend; user
/// code interacts with `Fp` only through its methods. The layout is that
/// of the limb array (`repr(transparent)`), which the assembly backend
/// relies on.
#[derive(Clone, Debug)]
#[repr(transparent)]
pub struct Fp<L: Prime> {
    pub(crate) limbs: Array<u64, L::FpLimbs>,
}

/// A quadratic-extension element `re + im * i` with `i^2 = -1`. `re` is
/// laid out before `im` (`repr(C)`), which the assembly backend's fused
/// multiplication relies on.
#[derive(Clone, Debug)]
#[repr(C)]
pub struct Fp2<L: Prime> {
    /// Real part.
    pub re: Fp<L>,
    /// Imaginary part.
    pub im: Fp<L>,
}

/// Per-prime field-arithmetic backend on raw limb storage.
///
/// Inputs and outputs are in the backend's internal Montgomery form unless
/// noted otherwise.
pub trait FpBackend: Prime {
    /// `out <- 0`.
    fn set_zero(out: &mut Array<u64, Self::FpLimbs>);
    /// `out <- 1`.
    fn set_one(out: &mut Array<u64, Self::FpLimbs>);
    /// `out <- val`.
    fn set_small(out: &mut Array<u64, Self::FpLimbs>, val: u64);
    /// Constant-time equality after full reduction.
    fn is_equal(a: &Array<u64, Self::FpLimbs>, b: &Array<u64, Self::FpLimbs>) -> Choice;
    /// Constant-time zero test after full reduction.
    fn is_zero(a: &Array<u64, Self::FpLimbs>) -> Choice;
    /// `out <- a`.
    fn copy(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// `out <- a + b mod 2p`.
    fn add(
        out: &mut Array<u64, Self::FpLimbs>,
        a: &Array<u64, Self::FpLimbs>,
        b: &Array<u64, Self::FpLimbs>,
    );
    /// `out <- a - b mod 2p`.
    fn sub(
        out: &mut Array<u64, Self::FpLimbs>,
        a: &Array<u64, Self::FpLimbs>,
        b: &Array<u64, Self::FpLimbs>,
    );
    /// `out <- -a mod 2p`.
    fn neg(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// Montgomery multiplication `out <- a * b * R^-1 mod 2p`.
    fn mul(
        out: &mut Array<u64, Self::FpLimbs>,
        a: &Array<u64, Self::FpLimbs>,
        b: &Array<u64, Self::FpLimbs>,
    );
    /// Montgomery squaring `out <- a^2 * R^-1 mod 2p`.
    fn sqr(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// `out <- 1 / a mod p`, with `0` for `a = 0`.
    fn inv(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// `out <- sqrt(a)` up to sign; only meaningful for square `a`.
    fn sqrt(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// `Choice(1)` if `a` is a square or zero.
    fn is_square(a: &Array<u64, Self::FpLimbs>) -> Choice;
    /// `out <- a / 2`.
    fn half(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// `out <- a / 3`.
    fn div3(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// Square-root progenitor `out <- a^((p-3)/4)`.
    fn exp3div4(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>);
    /// `out <- a * val mod 2p` for a small integer.
    fn mul_small(out: &mut Array<u64, Self::FpLimbs>, a: &Array<u64, Self::FpLimbs>, val: u32);
    /// Canonical little-endian encoding, exactly `FpEncodedBytes` bytes.
    fn encode(out: &mut [u8], a: &Array<u64, Self::FpLimbs>);
    /// Decode `FpEncodedBytes` canonical bytes; `Choice(1)` iff in `[0, p)`.
    /// On failure `out` is zero.
    fn decode(out: &mut Array<u64, Self::FpLimbs>, bytes: &[u8]) -> Choice;
    /// Decode a byte string of any length with full modular reduction.
    fn decode_reduce(out: &mut Array<u64, Self::FpLimbs>, bytes: &[u8]);
    /// Constant-time conditional swap.
    fn cswap(a: &mut Array<u64, Self::FpLimbs>, b: &mut Array<u64, Self::FpLimbs>, ctl: Choice);
    /// Constant-time select: `a0` if `ctl` is clear, `a1` if set.
    fn select(
        out: &mut Array<u64, Self::FpLimbs>,
        a0: &Array<u64, Self::FpLimbs>,
        a1: &Array<u64, Self::FpLimbs>,
        ctl: Choice,
    );

    /// `(out_re, out_im) <- (a_re + i a_im)(b_re + i b_im)`. The default is
    /// Karatsuba over `mul` (three multiplications, five additions); a
    /// backend may fuse the four products into two reductions instead
    /// (P25, the assembly backend).
    #[inline]
    fn fp2_mul(
        out_re: &mut Array<u64, Self::FpLimbs>,
        out_im: &mut Array<u64, Self::FpLimbs>,
        a_re: &Array<u64, Self::FpLimbs>,
        a_im: &Array<u64, Self::FpLimbs>,
        b_re: &Array<u64, Self::FpLimbs>,
        b_im: &Array<u64, Self::FpLimbs>,
    ) {
        let mut t0_in = Array::<u64, Self::FpLimbs>::default();
        let mut t1_in = Array::<u64, Self::FpLimbs>::default();
        let mut t0 = Array::<u64, Self::FpLimbs>::default();
        let mut t1 = Array::<u64, Self::FpLimbs>::default();
        let mut re_yz = Array::<u64, Self::FpLimbs>::default();
        Self::add(&mut t0_in, a_re, a_im);
        Self::add(&mut t1_in, b_re, b_im);
        Self::mul(&mut t0, &t0_in, &t1_in);
        Self::mul(&mut t1, a_im, b_im);
        Self::mul(&mut re_yz, a_re, b_re);
        // im = t0 - t1 - re_yz, re = re_yz - t1
        let mut tmp = Array::<u64, Self::FpLimbs>::default();
        Self::sub(&mut tmp, &t0, &t1);
        Self::sub(out_im, &tmp, &re_yz);
        Self::sub(out_re, &re_yz, &t1);
    }

    /// `a <- a b` in place (P28). The default goes through a temporary
    /// the compiler folds into direct stores once the backend's product
    /// leaves its kernel in registers; a backend may override it.
    #[inline]
    fn mul_assign(a: &mut Array<u64, Self::FpLimbs>, b: &Array<u64, Self::FpLimbs>) {
        let mut t = Array::<u64, Self::FpLimbs>::default();
        Self::mul(&mut t, a, b);
        *a = t;
    }

    /// `a <- a^2` in place (P28).
    #[inline]
    fn sqr_assign(a: &mut Array<u64, Self::FpLimbs>) {
        let mut t = Array::<u64, Self::FpLimbs>::default();
        Self::sqr(&mut t, a);
        *a = t;
    }

    /// `a <- a + b` in place (P28).
    #[inline]
    fn add_assign(a: &mut Array<u64, Self::FpLimbs>, b: &Array<u64, Self::FpLimbs>) {
        let mut t = Array::<u64, Self::FpLimbs>::default();
        Self::add(&mut t, a, b);
        *a = t;
    }

    /// `a <- a - b` in place (P28).
    #[inline]
    fn sub_assign(a: &mut Array<u64, Self::FpLimbs>, b: &Array<u64, Self::FpLimbs>) {
        let mut t = Array::<u64, Self::FpLimbs>::default();
        Self::sub(&mut t, a, b);
        *a = t;
    }

    /// `a <- a b` on whole `Fp2` values in place (P28).
    #[inline]
    fn fp2_mul_assign(a: &mut Fp2<Self>, b: &Fp2<Self>) {
        let mut t = Fp2 {
            re: Fp {
                limbs: Array::<u64, Self::FpLimbs>::default(),
            },
            im: Fp {
                limbs: Array::<u64, Self::FpLimbs>::default(),
            },
        };
        Self::fp2_mul_pair(&mut t, a, b);
        *a = t;
    }

    /// `a <- a^2` on a whole `Fp2` value in place (P28).
    #[inline]
    fn fp2_sqr_assign(a: &mut Fp2<Self>) {
        let mut re = Array::<u64, Self::FpLimbs>::default();
        let mut im = Array::<u64, Self::FpLimbs>::default();
        Self::fp2_sqr(&mut re, &mut im, &a.re.limbs, &a.im.limbs);
        a.re.limbs = re;
        a.im.limbs = im;
    }

    /// `out <- a b` on whole `Fp2` values: [`Self::fp2_mul`] by default; the
    /// x86-64 backends read the operands as `2 FpLimbs` contiguous limbs
    /// (`Fp2` is `repr(C)`) and return the products in registers, so that
    /// the compiler keeps no copies (P26 item 2).
    #[inline]
    fn fp2_mul_pair(out: &mut Fp2<Self>, a: &Fp2<Self>, b: &Fp2<Self>) {
        Self::fp2_mul(
            &mut out.re.limbs,
            &mut out.im.limbs,
            &a.re.limbs,
            &a.im.limbs,
            &b.re.limbs,
            &b.im.limbs,
        );
    }

    /// `(out_re, out_im) <- (a_re + i a_im)^2`. The default is two
    /// multiplications: `re = (a_re + a_im)(a_re - a_im)`, `im = 2 a_re a_im`.
    #[inline]
    fn fp2_sqr(
        out_re: &mut Array<u64, Self::FpLimbs>,
        out_im: &mut Array<u64, Self::FpLimbs>,
        a_re: &Array<u64, Self::FpLimbs>,
        a_im: &Array<u64, Self::FpLimbs>,
    ) {
        let mut sum = Array::<u64, Self::FpLimbs>::default();
        let mut diff = Array::<u64, Self::FpLimbs>::default();
        let mut half = Array::<u64, Self::FpLimbs>::default();
        Self::add(&mut sum, a_re, a_im);
        Self::sub(&mut diff, a_re, a_im);
        Self::mul(&mut half, a_re, a_im);
        Self::add(out_im, &half, &half);
        Self::mul(out_re, &sum, &diff);
    }
}

impl<L: Prime> Zeroize for Fp<L> {
    fn zeroize(&mut self) {
        self.limbs.as_mut_slice().zeroize();
    }
}

impl<L: Prime> Zeroize for Fp2<L> {
    fn zeroize(&mut self) {
        self.re.zeroize();
        self.im.zeroize();
    }
}
