//! `p324_3` (`p = 3 * 2^324 - 1`, SQIsign round 3, NIST level I): the x86-64 backend, saturated
//! 64-bit limbs with the Montgomery multiplication in inline assembly
//! (`mulx`, `adcx`, `adox`) when the CPU has BMI2 and ADX and in portable
//! Rust otherwise, chosen once at run time (`fp::dispatch`, P26 item 0; the
//! assembly was P25's opt-in `asm` feature).
//!
//! GENERATED by `tools/gen-fp-asm/gen_fp_asm.py`. Do not edit; change the
//! generator.
//!
//! Representation: 6 little-endian 64-bit limbs, Montgomery form with
//! `R = 2^384`, every stored value below `2^326` (58 spare bits).
//! Addition subtracts `p` conditionally twice and returns below `2^326`;
//! subtraction adds `p` conditionally twice and returns non-negative and
//! below `2^326`; the product of two values below `2^327` is below
//! `p + 2^270`. Comparisons and the encoding reduce to `[0, p)` first.
//!
//! The multiplication is the schedule of the SQIsign round-3 reference's
//! `broadwell` backend (`src/gf/broadwell/p324_3/fp_asm.S`, Apache-2.0):
//! one row of `mulx` per word of `b` accumulated with the two carry chains
//! (`adcx`/`adox`), and after each row one Montgomery fold, a single
//! multiplication because `p + 1 = 0x30 * 2^320` has one non-zero
//! limb and `-p^-1 = 1 mod 2^64`. This size keeps everything in `r8`-`r15`, `rax` and the three pointer registers. The fused `Fp2`
//! product computes `a_re b_re + a_im (2p - b_im)` and `a_re b_im + a_im
//! b_re` with one reduction each; squaring uses two products of unreduced
//! sums. The exponentiations use `(p - 3) / 4 = 2 2^322 + (2^322 - 1)`:
//! the all-ones chain for `2^322 - 1` and a short tail.
//!
//! The assembly needs BMI2 and ADX (Intel Broadwell or AMD Zen and later);
//! `fp::dispatch` reads CPUID once (in `no_std`, through `core::arch`) and
//! every kernel below branches on the cached answer, a relaxed atomic load.
//! The portable kernels of this module share the representation, so the
//! two paths agree bit for bit; `tests/fp_backends_differential.rs`
//! compares both against big-integer arithmetic, and the known-answer tests
//! run under both (`PRISM_FORCE_PORTABLE=1`). On other architectures the
//! generated radix backend (`p324_3.rs`) is the implementation.

use super::dispatch;
use super::{Fp2, FpBackend};
use crate::params::P324_3;
use hybrid_array::Array;
use subtle::Choice;

const NLIMBS: usize = 6;
type Limbs = Array<u64, <P324_3 as crate::params::Prime>::FpLimbs>;

/// `p`.
const P: [u64; 6] = [
    0xffffffffffffffff,
    0xffffffffffffffff,
    0xffffffffffffffff,
    0xffffffffffffffff,
    0xffffffffffffffff,
    0x000000000000002f,
];
/// `R mod p`, the Montgomery form of 1.
const ONE: [u64; 6] = [
    0x0555555555555555,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000010,
];
/// `R^2 mod p`, the constant that takes an integer to Montgomery form.
const R2: [u64; 6] = [
    0xc71c71c71c71c71c,
    0x5571c71c71c71c71,
    0x5555555555555555,
    0x5555555555555555,
    0x5555555555555555,
    0x0000000000000015,
];
/// `3^-1` in Montgomery form.
const THREE_INV: [u64; 6] = [
    0x571c71c71c71c71c,
    0x5555555555555555,
    0x5555555555555555,
    0x5555555555555555,
    0x5555555555555555,
    0x0000000000000015,
];
/// `2^320` in Montgomery form: one 40-byte chunk of `decode_reduce`.
const CHUNK_R: [u64; 6] = [
    0x5571c71c71c71c71,
    0x5555555555555555,
    0x5555555555555555,
    0x5555555555555555,
    0x5555555555555555,
    0x0000000000000025,
];
/// `2p`, for the fused multiplication's `2p - b_im` and the lazy subtraction.
static P2: [u64; 6] = [
    0xfffffffffffffffe,
    0xffffffffffffffff,
    0xffffffffffffffff,
    0xffffffffffffffff,
    0xffffffffffffffff,
    0x000000000000005f,
];
/// The one non-zero limb of `p + 1`, at index 5.
static P_PLUS_1_TOP: u64 = 0x30;
/// Its index: the fold adds `m P_PLUS_1_TOP` at this limb.
const FOLD: usize = 5;
/// Canonical encoding length.
const ENCODED_BYTES: usize = 41;
const CHUNK_BYTES: usize = ENCODED_BYTES - 1;
/// `e - 2`: the all-ones part of `(p - 3) / 4` has this many bits.
const ONES_BITS: u32 = 322;
/// `c - 1`, the small exponent of the tail of `(p - 3) / 4`.
const TAIL: u64 = 2;

#[inline]
fn as_arr(a: &Limbs) -> &[u64; NLIMBS] {
    <&[u64; NLIMBS]>::try_from(&a[..]).expect("invariant: FpLimbs == NLIMBS")
}

#[inline]
fn as_arr_mut(a: &mut Limbs) -> &mut [u64; NLIMBS] {
    <&mut [u64; NLIMBS]>::try_from(&mut a[..]).expect("invariant: FpLimbs == NLIMBS")
}

/// `a b / R mod p`, the assembly kernel. The result leaves the block in registers and
/// is stored into `c` by the compiler and drops the
/// zeroed temporary an output pointer would have forced it to keep (a
/// third of the multiplication's cost, measured, P26 item 2).
///
/// # Safety
/// Live `NLIMBS`-limb arrays; the CPU has BMI2 and ADX
/// (`dispatch::asm_available`).
#[inline(always)]
unsafe fn mont_mul_asm(a: *const u64, b: *const u64) -> [u64; NLIMBS] {
    let c0: u64;
    let c1: u64;
    let c2: u64;
    let c3: u64;
    let c4: u64;
    let c5: u64;
    core::arch::asm!(
        "mov rdx, qword ptr [rcx + 0]",
        "mulx r9, r8, qword ptr [rsi + 0]",
        "xor r14d, r14d",
        "mulx r10, rax, qword ptr [rsi + 8]",
        "adcx r9, rax",
        "mulx r11, rax, qword ptr [rsi + 16]",
        "adcx r10, rax",
        "mulx r12, rax, qword ptr [rsi + 24]",
        "adcx r11, rax",
        "mulx r13, rax, qword ptr [rsi + 32]",
        "adcx r12, rax",
        "mulx r14, rax, qword ptr [rsi + 40]",
        "adcx r13, rax",
        "adc r14, 0",
        "mov rdx, r8",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r13, rax",
        "adox r14, r15",
        "mov rdx, qword ptr [rcx + 8]",
        "xor r8d, r8d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r14, rax",
        "adox r8, r15",
        "adc r8, 0",
        "mov rdx, r9",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r14, rax",
        "adox r8, r15",
        "mov rdx, qword ptr [rcx + 16]",
        "xor r9d, r9d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r8, rax",
        "adox r9, r15",
        "adc r9, 0",
        "mov rdx, r10",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r8, rax",
        "adox r9, r15",
        "mov rdx, qword ptr [rcx + 24]",
        "xor r10d, r10d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r9, rax",
        "adox r10, r15",
        "adc r10, 0",
        "mov rdx, r11",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r9, rax",
        "adox r10, r15",
        "mov rdx, qword ptr [rcx + 32]",
        "xor r11d, r11d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r10, rax",
        "adox r11, r15",
        "adc r11, 0",
        "mov rdx, r12",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r10, rax",
        "adox r11, r15",
        "mov rdx, qword ptr [rcx + 40]",
        "xor r12d, r12d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r11, rax",
        "adox r12, r15",
        "adc r12, 0",
        "mov rdx, r13",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r11, rax",
        "adox r12, r15",
        pp1 = sym P_PLUS_1_TOP,
        lateout("r14") c0,
        lateout("r8") c1,
        lateout("r9") c2,
        lateout("r10") c3,
        lateout("r11") c4,
        lateout("r12") c5,
        in("rsi") a,
        in("rcx") b,
        out("rax") _,
        out("rdx") _,
        out("r13") _,
        out("r15") _,
        options(nostack),
    );
    [c0, c1, c2, c3, c4, c5]
}

/// `(a_re b_re - a_im b_im) / R`: the real part of an `Fp2` product, inputs
/// as `2 NLIMBS` contiguous limbs (`re` then `im`), one reduction.
/// `scratch` is an `NLIMBS`-limb buffer for `2p - b_im` (unused when the
/// kernel parks its operands in its own frame).
///
/// # Safety
/// As [`mont_mul_asm`], with `2 NLIMBS`-limb inputs and a live scratch.
#[inline(always)]
unsafe fn fp2_mul_re_asm(a: *const u64, b: *const u64, scratch: *mut u64) -> [u64; NLIMBS] {
    let _ = &scratch;
    let c0: u64;
    let c1: u64;
    let c2: u64;
    let c3: u64;
    let c4: u64;
    let c5: u64;
    core::arch::asm!(
        "mov r8, qword ptr [rip + {p2}]",
        "mov r9, qword ptr [rip + {p2} + 8]",
        "mov r10, r9",
        "mov r11, r9",
        "mov r12, r9",
        "mov r13, qword ptr [rip + {p2} + 40]",
        "sub r8, qword ptr [rcx + 48]",
        "sbb r9, qword ptr [rcx + 56]",
        "sbb r10, qword ptr [rcx + 64]",
        "sbb r11, qword ptr [rcx + 72]",
        "sbb r12, qword ptr [rcx + 80]",
        "sbb r13, qword ptr [rcx + 88]",
        "mov qword ptr [rdi + 0], r8",
        "mov qword ptr [rdi + 8], r9",
        "mov qword ptr [rdi + 16], r10",
        "mov qword ptr [rdi + 24], r11",
        "mov qword ptr [rdi + 32], r12",
        "mov qword ptr [rdi + 40], r13",
        "mov rdx, qword ptr [rcx + 0]",
        "mulx r9, r8, qword ptr [rsi + 0]",
        "xor r14d, r14d",
        "mulx r10, rax, qword ptr [rsi + 8]",
        "adcx r9, rax",
        "mulx r11, rax, qword ptr [rsi + 16]",
        "adcx r10, rax",
        "mulx r12, rax, qword ptr [rsi + 24]",
        "adcx r11, rax",
        "mulx r13, rax, qword ptr [rsi + 32]",
        "adcx r12, rax",
        "mulx r14, rax, qword ptr [rsi + 40]",
        "adcx r13, rax",
        "adc r14, 0",
        "mov rdx, qword ptr [rdi + 0]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r13, rax",
        "adox r14, r15",
        "adc r14, 0",
        "mov rdx, r8",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r13, rax",
        "adox r14, r15",
        "mov rdx, qword ptr [rcx + 8]",
        "xor r8d, r8d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r14, rax",
        "adox r8, r15",
        "adc r8, 0",
        "mov rdx, qword ptr [rdi + 8]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r14, rax",
        "adox r8, r15",
        "adc r8, 0",
        "mov rdx, r9",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r14, rax",
        "adox r8, r15",
        "mov rdx, qword ptr [rcx + 16]",
        "xor r9d, r9d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r8, rax",
        "adox r9, r15",
        "adc r9, 0",
        "mov rdx, qword ptr [rdi + 16]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r8, rax",
        "adox r9, r15",
        "adc r9, 0",
        "mov rdx, r10",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r8, rax",
        "adox r9, r15",
        "mov rdx, qword ptr [rcx + 24]",
        "xor r10d, r10d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r9, rax",
        "adox r10, r15",
        "adc r10, 0",
        "mov rdx, qword ptr [rdi + 24]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r9, rax",
        "adox r10, r15",
        "adc r10, 0",
        "mov rdx, r11",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r9, rax",
        "adox r10, r15",
        "mov rdx, qword ptr [rcx + 32]",
        "xor r11d, r11d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r10, rax",
        "adox r11, r15",
        "adc r11, 0",
        "mov rdx, qword ptr [rdi + 32]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r10, rax",
        "adox r11, r15",
        "adc r11, 0",
        "mov rdx, r12",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r10, rax",
        "adox r11, r15",
        "mov rdx, qword ptr [rcx + 40]",
        "xor r12d, r12d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r11, rax",
        "adox r12, r15",
        "adc r12, 0",
        "mov rdx, qword ptr [rdi + 40]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r11, rax",
        "adox r12, r15",
        "adc r12, 0",
        "mov rdx, r13",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r11, rax",
        "adox r12, r15",
        pp1 = sym P_PLUS_1_TOP,
        p2 = sym P2,
        lateout("r14") c0,
        lateout("r8") c1,
        lateout("r9") c2,
        lateout("r10") c3,
        lateout("r11") c4,
        lateout("r12") c5,
        in("rsi") a,
        in("rcx") b,
        in("rdi") scratch,
        out("rax") _,
        out("rdx") _,
        out("r13") _,
        out("r15") _,
        options(nostack),
    );
    [c0, c1, c2, c3, c4, c5]
}

/// `(a_re b_im + a_im b_re) / R`: the imaginary part, one reduction.
///
/// # Safety
/// As [`mont_mul_asm`], with `2 NLIMBS`-limb inputs.
#[inline(always)]
unsafe fn fp2_mul_im_asm(a: *const u64, b: *const u64) -> [u64; NLIMBS] {
    let c0: u64;
    let c1: u64;
    let c2: u64;
    let c3: u64;
    let c4: u64;
    let c5: u64;
    core::arch::asm!(
        "mov rdx, qword ptr [rcx + 48]",
        "mulx r9, r8, qword ptr [rsi + 0]",
        "xor r14d, r14d",
        "mulx r10, rax, qword ptr [rsi + 8]",
        "adcx r9, rax",
        "mulx r11, rax, qword ptr [rsi + 16]",
        "adcx r10, rax",
        "mulx r12, rax, qword ptr [rsi + 24]",
        "adcx r11, rax",
        "mulx r13, rax, qword ptr [rsi + 32]",
        "adcx r12, rax",
        "mulx r14, rax, qword ptr [rsi + 40]",
        "adcx r13, rax",
        "adc r14, 0",
        "mov rdx, qword ptr [rcx + 0]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r13, rax",
        "adox r14, r15",
        "adc r14, 0",
        "mov rdx, r8",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r13, rax",
        "adox r14, r15",
        "mov rdx, qword ptr [rcx + 56]",
        "xor r8d, r8d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r14, rax",
        "adox r8, r15",
        "adc r8, 0",
        "mov rdx, qword ptr [rcx + 8]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r14, rax",
        "adox r8, r15",
        "adc r8, 0",
        "mov rdx, r9",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r14, rax",
        "adox r8, r15",
        "mov rdx, qword ptr [rcx + 64]",
        "xor r9d, r9d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r8, rax",
        "adox r9, r15",
        "adc r9, 0",
        "mov rdx, qword ptr [rcx + 16]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r8, rax",
        "adox r9, r15",
        "adc r9, 0",
        "mov rdx, r10",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r8, rax",
        "adox r9, r15",
        "mov rdx, qword ptr [rcx + 72]",
        "xor r10d, r10d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r9, rax",
        "adox r10, r15",
        "adc r10, 0",
        "mov rdx, qword ptr [rcx + 24]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r11, rax",
        "adox r12, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r9, rax",
        "adox r10, r15",
        "adc r10, 0",
        "mov rdx, r11",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r9, rax",
        "adox r10, r15",
        "mov rdx, qword ptr [rcx + 80]",
        "xor r11d, r11d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r10, rax",
        "adox r11, r15",
        "adc r11, 0",
        "mov rdx, qword ptr [rcx + 32]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r12, rax",
        "adox r13, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r10, rax",
        "adox r11, r15",
        "adc r11, 0",
        "mov rdx, r12",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r10, rax",
        "adox r11, r15",
        "mov rdx, qword ptr [rcx + 88]",
        "xor r12d, r12d",
        "mulx r15, rax, qword ptr [rsi + 0]",
        "adox r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 8]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 16]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 24]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 32]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 40]",
        "adcx r11, rax",
        "adox r12, r15",
        "adc r12, 0",
        "mov rdx, qword ptr [rcx + 40]",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rsi + 48]",
        "adox r13, rax",
        "adox r14, r15",
        "mulx r15, rax, qword ptr [rsi + 56]",
        "adcx r14, rax",
        "adox r8, r15",
        "mulx r15, rax, qword ptr [rsi + 64]",
        "adcx r8, rax",
        "adox r9, r15",
        "mulx r15, rax, qword ptr [rsi + 72]",
        "adcx r9, rax",
        "adox r10, r15",
        "mulx r15, rax, qword ptr [rsi + 80]",
        "adcx r10, rax",
        "adox r11, r15",
        "mulx r15, rax, qword ptr [rsi + 88]",
        "adcx r11, rax",
        "adox r12, r15",
        "adc r12, 0",
        "mov rdx, r13",
        "xor r15d, r15d",
        "mulx r15, rax, qword ptr [rip + {pp1}]",
        "adox r11, rax",
        "adox r12, r15",
        pp1 = sym P_PLUS_1_TOP,
        lateout("r14") c0,
        lateout("r8") c1,
        lateout("r9") c2,
        lateout("r10") c3,
        lateout("r11") c4,
        lateout("r12") c5,
        in("rsi") a,
        in("rcx") b,
        out("rax") _,
        out("rdx") _,
        out("r13") _,
        out("r15") _,
        options(nostack),
    );
    [c0, c1, c2, c3, c4, c5]
}

/// `c <- a b / R mod p` in portable Rust: operand scanning with `u128`
/// products and the same one-limb fold per word as the assembly
/// (`-p^-1 = 1 mod 2^64`, so the Montgomery multiplier is the low limb
/// itself). Inputs below `2^(BITS + 1)`, output below `p + 2^(2 BITS + 2 - 64 NLIMBS)`.
#[inline]
fn mont_mul_portable(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    let mut t = [0u64; NLIMBS + 2];
    for bi in b.iter() {
        let mut carry = 0u128;
        for j in 0..NLIMBS {
            let p = (t[j] as u128) + (a[j] as u128) * (*bi as u128) + carry;
            t[j] = p as u64;
            carry = p >> 64;
        }
        let s = (t[NLIMBS] as u128) + carry;
        t[NLIMBS] = s as u64;
        t[NLIMBS + 1] = (s >> 64) as u64;
        fold_and_shift(&mut t);
    }
    debug_assert_eq!(t[NLIMBS], 0);
    c.copy_from_slice(&t[..NLIMBS]);
}

/// `c <- (a0 b0 + a1 b1) / R mod p` in portable Rust, the schedule of the
/// fused assembly kernels: per word `i`, the two rows `a0 b0[i]` and
/// `a1 b1[i]`, then one fold. Bit for bit the assembly's result.
#[inline]
fn mont_mul2_portable(
    c: &mut [u64; NLIMBS],
    a0: &[u64; NLIMBS],
    b0: &[u64; NLIMBS],
    a1: &[u64; NLIMBS],
    b1: &[u64; NLIMBS],
) {
    let mut t = [0u64; NLIMBS + 2];
    for i in 0..NLIMBS {
        for (a, bi) in [(a0, b0[i]), (a1, b1[i])] {
            let mut carry = 0u128;
            for j in 0..NLIMBS {
                let p = (t[j] as u128) + (a[j] as u128) * (bi as u128) + carry;
                t[j] = p as u64;
                carry = p >> 64;
            }
            let s = (t[NLIMBS] as u128) + carry;
            t[NLIMBS] = s as u64;
            t[NLIMBS + 1] = t[NLIMBS + 1].wrapping_add((s >> 64) as u64);
        }
        fold_and_shift(&mut t);
    }
    debug_assert_eq!(t[NLIMBS], 0);
    c.copy_from_slice(&t[..NLIMBS]);
}

/// One Montgomery fold of the accumulator and the division by `2^64`:
/// `m = t[0]`, `t <- (t + m p) / 2^64`, where `m p = m K 2^(64 FOLD) - m`
/// and `t[0] - m = 0`.
#[inline(always)]
fn fold_and_shift(t: &mut [u64; NLIMBS + 2]) {
    let m = t[0];
    let prod = (m as u128) * (P_PLUS_1_TOP as u128);
    let s = (t[FOLD] as u128) + (prod as u64 as u128);
    t[FOLD] = s as u64;
    let s = (t[FOLD + 1] as u128) + ((prod >> 64) as u64 as u128) + (s >> 64);
    t[FOLD + 1] = s as u64;
    let mut carry = s >> 64;
    for w in t.iter_mut().skip(FOLD + 2) {
        let s = (*w as u128) + carry;
        *w = s as u64;
        carry = s >> 64;
    }
    for j in 0..NLIMBS + 1 {
        t[j] = t[j + 1];
    }
    t[NLIMBS + 1] = 0;
}

/// The portable real part: `(a_re b_re + a_im (2p - b_im)) / R`.
#[inline]
fn fp2_mul_re_portable(
    c: &mut [u64; NLIMBS],
    a_re: &[u64; NLIMBS],
    a_im: &[u64; NLIMBS],
    b_re: &[u64; NLIMBS],
    b_im: &[u64; NLIMBS],
) {
    let mut s = [0u64; NLIMBS];
    let mut borrow = 0u64;
    for i in 0..NLIMBS {
        let (r, bw) = sbb(P2[i], b_im[i], borrow);
        s[i] = r;
        borrow = bw;
    }
    mont_mul2_portable(c, a_re, b_re, a_im, &s);
}

#[inline(always)]
fn mont_mul(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    if dispatch::asm_available() {
        // SAFETY: live arrays; BMI2 and ADX detected.
        *c = unsafe { mont_mul_asm(a.as_ptr(), b.as_ptr()) };
    } else {
        mont_mul_portable(c, a, b)
    }
}

/// The fused product on two `Fp2` values in memory (`re` then `im`, the
/// `repr(C)` layout of [`crate::fp::Fp2`]): no copies of the operands.
#[inline(always)]
fn fp2_mul_contiguous(
    out_re: &mut [u64; NLIMBS],
    out_im: &mut [u64; NLIMBS],
    a: *const u64,
    b: *const u64,
) {
    let mut scratch = [0u64; NLIMBS];
    // SAFETY: the caller passes `2 NLIMBS` live limbs per operand; BMI2 and
    // ADX detected by the caller.
    unsafe {
        *out_re = fp2_mul_re_asm(a, b, scratch.as_mut_ptr());
        *out_im = fp2_mul_im_asm(a, b);
    }
}

#[inline]
fn adc(a: u64, b: u64, carry: u64) -> (u64, u64) {
    let t = (a as u128) + (b as u128) + (carry as u128);
    (t as u64, (t >> 64) as u64)
}

#[inline]
fn sbb(a: u64, b: u64, borrow: u64) -> (u64, u64) {
    let t = (a as u128)
        .wrapping_sub(b as u128)
        .wrapping_sub(borrow as u128);
    (t as u64, (t >> 127) as u64)
}

#[inline]
fn sub_p_masked(a: &mut [u64; NLIMBS], mask: u64) {
    let mut borrow = 0u64;
    for i in 0..NLIMBS {
        let (r, b) = sbb(a[i], P[i] & mask, borrow);
        a[i] = r;
        borrow = b;
    }
}

/// `a + b`, below `2^BITS` for inputs below `2^BITS`: the sum, then twice `-p` when the result is at or above `2^BITS`. The result leaves in registers.
///
/// # Safety
/// Live `NLIMBS`-limb arrays.
#[inline(always)]
unsafe fn add_asm(a: *const u64, b: *const u64) -> [u64; NLIMBS] {
    let c0: u64;
    let c1: u64;
    let c2: u64;
    let c3: u64;
    let c4: u64;
    let c5: u64;
    core::arch::asm!(
        "mov r8, qword ptr [rsi + 0]",
        "mov r9, qword ptr [rsi + 8]",
        "mov r10, qword ptr [rsi + 16]",
        "mov r11, qword ptr [rsi + 24]",
        "mov r12, qword ptr [rsi + 32]",
        "mov r13, qword ptr [rsi + 40]",
        "add r8, qword ptr [rcx]",
        "adc r9, qword ptr [rcx + 8]",
        "adc r10, qword ptr [rcx + 16]",
        "adc r11, qword ptr [rcx + 24]",
        "adc r12, qword ptr [rcx + 32]",
        "adc r13, qword ptr [rcx + 40]",
        "mov rax, r13",
        "shr rax, 6",
        "neg rax",
        "mov rdx, 0x2f",
        "and rdx, rax",
        "sub r8, rax",
        "sbb r9, rax",
        "sbb r10, rax",
        "sbb r11, rax",
        "sbb r12, rax",
        "sbb r13, rdx",
        "mov rax, r13",
        "shr rax, 6",
        "neg rax",
        "mov rdx, 0x2f",
        "and rdx, rax",
        "sub r8, rax",
        "sbb r9, rax",
        "sbb r10, rax",
        "sbb r11, rax",
        "sbb r12, rax",
        "sbb r13, rdx",
        in("rsi") a,
        in("rcx") b,
        lateout("r8") c0,
        lateout("r9") c1,
        lateout("r10") c2,
        lateout("r11") c3,
        lateout("r12") c4,
        lateout("r13") c5,
        out("rax") _,
        out("rdx") _,
        options(nostack),
    );
    [c0, c1, c2, c3, c4, c5]
}

/// `a - b`, non-negative and below `2^BITS` for inputs below `2^BITS`: `+p` on borrow, `+p` again when still negative. The result leaves in registers.
///
/// # Safety
/// Live `NLIMBS`-limb arrays.
#[inline(always)]
unsafe fn sub_asm(a: *const u64, b: *const u64) -> [u64; NLIMBS] {
    let c0: u64;
    let c1: u64;
    let c2: u64;
    let c3: u64;
    let c4: u64;
    let c5: u64;
    core::arch::asm!(
        "mov r8, qword ptr [rsi + 0]",
        "mov r9, qword ptr [rsi + 8]",
        "mov r10, qword ptr [rsi + 16]",
        "mov r11, qword ptr [rsi + 24]",
        "mov r12, qword ptr [rsi + 32]",
        "mov r13, qword ptr [rsi + 40]",
        "xor eax, eax",
        "sub r8, qword ptr [rcx]",
        "sbb r9, qword ptr [rcx + 8]",
        "sbb r10, qword ptr [rcx + 16]",
        "sbb r11, qword ptr [rcx + 24]",
        "sbb r12, qword ptr [rcx + 32]",
        "sbb r13, qword ptr [rcx + 40]",
        "sbb rax, 0",
        "mov rdx, 0x2f",
        "and rdx, rax",
        "add r8, rax",
        "adc r9, rax",
        "adc r10, rax",
        "adc r11, rax",
        "adc r12, rax",
        "adc r13, rdx",
        "mov rax, r13",
        "sar rax, 6",
        "mov rdx, 0x2f",
        "and rdx, rax",
        "add r8, rax",
        "adc r9, rax",
        "adc r10, rax",
        "adc r11, rax",
        "adc r12, rax",
        "adc r13, rdx",
        in("rsi") a,
        in("rcx") b,
        lateout("r8") c0,
        lateout("r9") c1,
        lateout("r10") c2,
        lateout("r11") c3,
        lateout("r12") c4,
        lateout("r13") c5,
        out("rax") _,
        out("rdx") _,
        options(nostack),
    );
    [c0, c1, c2, c3, c4, c5]
}

/// unreduced `a + b`, an input of the multiplication only. The result leaves in registers.
///
/// # Safety
/// Live `NLIMBS`-limb arrays.
#[inline(always)]
unsafe fn add_lazy_asm(a: *const u64, b: *const u64) -> [u64; NLIMBS] {
    let c0: u64;
    let c1: u64;
    let c2: u64;
    let c3: u64;
    let c4: u64;
    let c5: u64;
    core::arch::asm!(
        "mov r8, qword ptr [rsi + 0]",
        "mov r9, qword ptr [rsi + 8]",
        "mov r10, qword ptr [rsi + 16]",
        "mov r11, qword ptr [rsi + 24]",
        "mov r12, qword ptr [rsi + 32]",
        "mov r13, qword ptr [rsi + 40]",
        "add r8, qword ptr [rcx]",
        "adc r9, qword ptr [rcx + 8]",
        "adc r10, qword ptr [rcx + 16]",
        "adc r11, qword ptr [rcx + 24]",
        "adc r12, qword ptr [rcx + 32]",
        "adc r13, qword ptr [rcx + 40]",
        in("rsi") a,
        in("rcx") b,
        lateout("r8") c0,
        lateout("r9") c1,
        lateout("r10") c2,
        lateout("r11") c3,
        lateout("r12") c4,
        lateout("r13") c5,
        out("rax") _,
        out("rdx") _,
        options(nostack),
    );
    [c0, c1, c2, c3, c4, c5]
}

/// unreduced `a - b + 2p` (positive), an input of the multiplication only. The result leaves in registers.
///
/// # Safety
/// Live `NLIMBS`-limb arrays.
#[inline(always)]
unsafe fn sub_lazy_2p_asm(a: *const u64, b: *const u64) -> [u64; NLIMBS] {
    let c0: u64;
    let c1: u64;
    let c2: u64;
    let c3: u64;
    let c4: u64;
    let c5: u64;
    core::arch::asm!(
        "mov r8, qword ptr [rsi + 0]",
        "mov r9, qword ptr [rsi + 8]",
        "mov r10, qword ptr [rsi + 16]",
        "mov r11, qword ptr [rsi + 24]",
        "mov r12, qword ptr [rsi + 32]",
        "mov r13, qword ptr [rsi + 40]",
        "sub r8, qword ptr [rcx]",
        "sbb r9, qword ptr [rcx + 8]",
        "sbb r10, qword ptr [rcx + 16]",
        "sbb r11, qword ptr [rcx + 24]",
        "sbb r12, qword ptr [rcx + 32]",
        "sbb r13, qword ptr [rcx + 40]",
        "add r8, -2",
        "adc r9, -1",
        "adc r10, -1",
        "adc r11, -1",
        "adc r12, -1",
        "mov rax, 0x5f",
        "adc r13, rax",
        in("rsi") a,
        in("rcx") b,
        lateout("r8") c0,
        lateout("r9") c1,
        lateout("r10") c2,
        lateout("r11") c3,
        lateout("r12") c4,
        lateout("r13") c5,
        out("rax") _,
        out("rdx") _,
        options(nostack),
    );
    [c0, c1, c2, c3, c4, c5]
}

/// `c <- a + b`, below `2^BITS` for inputs below `2^BITS`.
#[inline(always)]
fn fp_add(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    // SAFETY: live arrays of NLIMBS limbs.
    *c = unsafe { add_asm(a.as_ptr(), b.as_ptr()) };
}

/// `c <- a - b`, non-negative and below `2^BITS` for inputs below `2^BITS`.
#[inline(always)]
fn fp_sub(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    // SAFETY: live arrays of NLIMBS limbs.
    *c = unsafe { sub_asm(a.as_ptr(), b.as_ptr()) };
}

/// Unreduced `a + b`, an input of the multiplication only.
#[inline(always)]
fn add_lazy(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    // SAFETY: live arrays of NLIMBS limbs.
    *c = unsafe { add_lazy_asm(a.as_ptr(), b.as_ptr()) };
}

/// Unreduced `a - b + 2p` (positive), an input of the multiplication only.
#[inline(always)]
fn sub_lazy_2p(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    // SAFETY: live arrays of NLIMBS limbs.
    *c = unsafe { sub_lazy_2p_asm(a.as_ptr(), b.as_ptr()) };
}

/// All ones when `a >= b` as `NLIMBS`-limb integers.
#[inline]
fn ge_mask(a: &[u64; NLIMBS], b: &[u64; NLIMBS]) -> u64 {
    let mut borrow = 0u64;
    for i in 0..NLIMBS {
        let (_, bw) = sbb(a[i], b[i], borrow);
        borrow = bw;
    }
    borrow.wrapping_sub(1)
}

/// Fully reduce a stored value (below `2^BITS < 2p`) to `[0, p)`.
#[inline]
fn canonical(a: &[u64; NLIMBS]) -> [u64; NLIMBS] {
    let mut c = *a;
    let m = ge_mask(&c, &P);
    sub_p_masked(&mut c, m);
    let m = ge_mask(&c, &P);
    sub_p_masked(&mut c, m);
    c
}

#[inline]
fn is_zero_limbs(a: &[u64; NLIMBS]) -> Choice {
    let mut acc = 0u64;
    for &w in a {
        acc |= w;
    }
    Choice::from((((acc | acc.wrapping_neg()) >> 63) ^ 1) as u8)
}

#[inline]
fn eq_limbs(a: &[u64; NLIMBS], b: &[u64; NLIMBS]) -> Choice {
    let mut acc = 0u64;
    for i in 0..NLIMBS {
        acc |= a[i] ^ b[i];
    }
    Choice::from((((acc | acc.wrapping_neg()) >> 63) ^ 1) as u8)
}

#[inline]
fn sqr_n(x: &mut [u64; NLIMBS], n: u32) {
    for _ in 0..n {
        let t = *x;
        mont_mul(x, &t, &t);
    }
}

/// `w^(2^k - 1)` by the binary all-ones chain: about `k` squarings and
/// `2 log2 k` multiplications.
fn ones(w: &[u64; NLIMBS], k: u32) -> [u64; NLIMBS] {
    let mut acc = *w;
    let mut cur = 1u32;
    for bit in (0..(31 - k.leading_zeros())).rev() {
        // acc = w^(2^cur - 1) -> w^(2^(2 cur) - 1)
        let prev = acc;
        sqr_n(&mut acc, cur);
        let t = acc;
        mont_mul(&mut acc, &t, &prev);
        cur *= 2;
        if (k >> bit) & 1 == 1 {
            let t = acc;
            let mut sq = [0u64; NLIMBS];
            mont_mul(&mut sq, &t, &t);
            mont_mul(&mut acc, &sq, w);
            cur += 1;
        }
    }
    debug_assert_eq!(cur, k);
    acc
}

/// `z <- w^((p-3)/4)` with `(p-3)/4 = TAIL 2^ONES_BITS + (2^ONES_BITS - 1)`.
fn exp3div4(z: &mut [u64; NLIMBS], w: &[u64; NLIMBS]) {
    let t = ones(w, ONES_BITS);
    // u = w^(2^ONES_BITS) = t w; v = u^TAIL; z = v t
    let mut u = [0u64; NLIMBS];
    mont_mul(&mut u, &t, w);
    let mut v = ONE;
    for bit in (0..(64 - TAIL.leading_zeros())).rev() {
        let s = v;
        mont_mul(&mut v, &s, &s);
        if (TAIL >> bit) & 1 == 1 {
            let s = v;
            mont_mul(&mut v, &s, &u);
        }
    }
    mont_mul(z, &v, &t);
}

/// Little-endian bytes to limbs, `Choice(1)` iff the value is below `p`;
/// the value itself (not yet in Montgomery form), zero on failure.
#[inline]
fn bytes_to_int(out: &mut [u64; NLIMBS], bytes: &[u8]) -> Choice {
    *out = [0; NLIMBS];
    let mut buf = [0u8; 8 * NLIMBS];
    buf[..ENCODED_BYTES].copy_from_slice(&bytes[..ENCODED_BYTES]);
    for i in 0..NLIMBS {
        out[i] = u64::from_le_bytes(buf[8 * i..8 * i + 8].try_into().expect("8 bytes"));
    }
    let lt = Choice::from(((!ge_mask(out, &P)) & 1) as u8);
    let keep = 0u64.wrapping_sub(lt.unwrap_u8() as u64);
    for w in out.iter_mut() {
        *w &= keep;
    }
    lt
}

impl FpBackend for P324_3 {
    #[inline]
    fn set_zero(out: &mut Limbs) {
        *as_arr_mut(out) = [0; NLIMBS];
    }

    #[inline]
    fn set_one(out: &mut Limbs) {
        *as_arr_mut(out) = ONE;
    }

    #[inline]
    fn set_small(out: &mut Limbs, val: u64) {
        let mut v = [0u64; NLIMBS];
        v[0] = val;
        mont_mul(as_arr_mut(out), &v, &R2);
    }

    #[inline]
    fn is_equal(a: &Limbs, b: &Limbs) -> Choice {
        eq_limbs(&canonical(as_arr(a)), &canonical(as_arr(b)))
    }

    #[inline]
    fn is_zero(a: &Limbs) -> Choice {
        is_zero_limbs(&canonical(as_arr(a)))
    }

    #[inline]
    fn copy(out: &mut Limbs, a: &Limbs) {
        *as_arr_mut(out) = *as_arr(a);
    }

    #[inline]
    fn add(out: &mut Limbs, a: &Limbs, b: &Limbs) {
        fp_add(as_arr_mut(out), as_arr(a), as_arr(b));
    }

    #[inline]
    fn sub(out: &mut Limbs, a: &Limbs, b: &Limbs) {
        fp_sub(as_arr_mut(out), as_arr(a), as_arr(b));
    }

    #[inline]
    fn neg(out: &mut Limbs, a: &Limbs) {
        fp_sub(as_arr_mut(out), &[0; NLIMBS], as_arr(a));
    }

    #[inline]
    fn mul(out: &mut Limbs, a: &Limbs, b: &Limbs) {
        mont_mul(as_arr_mut(out), as_arr(a), as_arr(b));
    }

    #[inline]
    fn sqr(out: &mut Limbs, a: &Limbs) {
        let a = as_arr(a);
        mont_mul(as_arr_mut(out), a, a);
    }

    #[inline]
    fn fp2_mul(
        out_re: &mut Limbs,
        out_im: &mut Limbs,
        a_re: &Limbs,
        a_im: &Limbs,
        b_re: &Limbs,
        b_im: &Limbs,
    ) {
        if dispatch::asm_available() {
            let mut a = [0u64; 2 * NLIMBS];
            let mut b = [0u64; 2 * NLIMBS];
            a[..NLIMBS].copy_from_slice(&a_re[..]);
            a[NLIMBS..].copy_from_slice(&a_im[..]);
            b[..NLIMBS].copy_from_slice(&b_re[..]);
            b[NLIMBS..].copy_from_slice(&b_im[..]);
            fp2_mul_contiguous(
                as_arr_mut(out_re),
                as_arr_mut(out_im),
                a.as_ptr(),
                b.as_ptr(),
            );
        } else {
            let (a_re, a_im, b_re, b_im) = (as_arr(a_re), as_arr(a_im), as_arr(b_re), as_arr(b_im));
            fp2_mul_re_portable(as_arr_mut(out_re), a_re, a_im, b_re, b_im);
            mont_mul2_portable(as_arr_mut(out_im), a_re, b_im, a_im, b_re);
        }
    }

    /// `a <- a b` with the product stored straight into `a` (P28): the
    /// kernel reads `a` through a raw pointer while it runs and the store
    /// follows it, so no temporary is copied.
    #[inline]
    fn mul_assign(a: &mut Limbs, b: &Limbs) {
        if dispatch::asm_available() {
            let dst = as_arr_mut(a);
            let pa = dst.as_mut_ptr() as *const u64;
            // SAFETY: live arrays; `pa` is read by the kernel before `dst`
            // is written; BMI2 and ADX detected.
            let r = unsafe { mont_mul_asm(pa, b.as_ptr()) };
            *dst = r;
        } else {
            let mut t = [0u64; NLIMBS];
            mont_mul_portable(&mut t, as_arr(a), as_arr(b));
            *as_arr_mut(a) = t;
        }
    }

    #[inline]
    fn sqr_assign(a: &mut Limbs) {
        if dispatch::asm_available() {
            let dst = as_arr_mut(a);
            let pa = dst.as_mut_ptr() as *const u64;
            // SAFETY: as `mul_assign`.
            let r = unsafe { mont_mul_asm(pa, pa) };
            *dst = r;
        } else {
            let mut t = [0u64; NLIMBS];
            let x = *as_arr(a);
            mont_mul_portable(&mut t, &x, &x);
            *as_arr_mut(a) = t;
        }
    }

    #[inline]
    fn add_assign(a: &mut Limbs, b: &Limbs) {
        let dst = as_arr_mut(a);
        let pa = dst.as_mut_ptr() as *const u64;
        // SAFETY: live arrays; the kernel reads `pa` before `dst` is written.
        let r = unsafe { add_asm(pa, b.as_ptr()) };
        *dst = r;
    }

    #[inline]
    fn sub_assign(a: &mut Limbs, b: &Limbs) {
        let dst = as_arr_mut(a);
        let pa = dst.as_mut_ptr() as *const u64;
        // SAFETY: as `add_assign`.
        let r = unsafe { sub_asm(pa, b.as_ptr()) };
        *dst = r;
    }

    #[inline]
    fn fp2_mul_assign(a: &mut Fp2<Self>, b: &Fp2<Self>) {
        if dispatch::asm_available() {
            let pa = a as *mut Fp2<Self> as *mut u64;
            let pb = b as *const Fp2<Self> as *const u64;
            let mut scratch = [0u64; NLIMBS];
            // SAFETY: `2 NLIMBS` live limbs behind each pointer (the layout
            // assertion of `fp2_mul_pair`); both kernels read `a` before
            // either half is stored; BMI2 and ADX detected.
            unsafe {
                let re = fp2_mul_re_asm(pa as *const u64, pb, scratch.as_mut_ptr());
                let im = fp2_mul_im_asm(pa as *const u64, pb);
                *as_arr_mut(&mut a.re.limbs) = re;
                *as_arr_mut(&mut a.im.limbs) = im;
            }
        } else {
            let (a_re, a_im) = (*as_arr(&a.re.limbs), *as_arr(&a.im.limbs));
            let (b_re, b_im) = (as_arr(&b.re.limbs), as_arr(&b.im.limbs));
            fp2_mul_re_portable(as_arr_mut(&mut a.re.limbs), &a_re, &a_im, b_re, b_im);
            mont_mul2_portable(as_arr_mut(&mut a.im.limbs), &a_re, b_im, &a_im, b_re);
        }
    }

    #[inline]
    fn fp2_sqr_assign(a: &mut Fp2<Self>) {
        let (a_re, a_im) = (*as_arr(&a.re.limbs), *as_arr(&a.im.limbs));
        let mut sum = [0u64; NLIMBS];
        let mut diff = [0u64; NLIMBS];
        add_lazy(&mut sum, &a_re, &a_im);
        sub_lazy_2p(&mut diff, &a_re, &a_im);
        mont_mul(as_arr_mut(&mut a.re.limbs), &sum, &diff);
        let mut twice = [0u64; NLIMBS];
        add_lazy(&mut twice, &a_re, &a_re);
        mont_mul(as_arr_mut(&mut a.im.limbs), &twice, &a_im);
    }

    #[inline]
    fn fp2_mul_pair(out: &mut Fp2<Self>, a: &Fp2<Self>, b: &Fp2<Self>) {
        const _: () = assert!(core::mem::size_of::<Fp2<P324_3>>() == 16 * NLIMBS);
        if dispatch::asm_available() {
            // `Fp2` is `repr(C)` of two `repr(transparent)` limb arrays: `2
            // NLIMBS` contiguous limbs, `re` first (the assertion above)
            let pa = a as *const Fp2<Self> as *const u64;
            let pb = b as *const Fp2<Self> as *const u64;
            let (re, im) = (&mut out.re.limbs, &mut out.im.limbs);
            fp2_mul_contiguous(as_arr_mut(re), as_arr_mut(im), pa, pb);
        } else {
            let (a_re, a_im) = (as_arr(&a.re.limbs), as_arr(&a.im.limbs));
            let (b_re, b_im) = (as_arr(&b.re.limbs), as_arr(&b.im.limbs));
            fp2_mul_re_portable(as_arr_mut(&mut out.re.limbs), a_re, a_im, b_re, b_im);
            mont_mul2_portable(as_arr_mut(&mut out.im.limbs), a_re, b_im, a_im, b_re);
        }
    }

    #[inline]
    fn fp2_sqr(out_re: &mut Limbs, out_im: &mut Limbs, a_re: &Limbs, a_im: &Limbs) {
        let (a_re, a_im) = (as_arr(a_re), as_arr(a_im));
        let mut sum = [0u64; NLIMBS];
        let mut diff = [0u64; NLIMBS];
        add_lazy(&mut sum, a_re, a_im);
        sub_lazy_2p(&mut diff, a_re, a_im);
        mont_mul(as_arr_mut(out_re), &sum, &diff);
        let mut twice = [0u64; NLIMBS];
        add_lazy(&mut twice, a_re, a_re);
        mont_mul(as_arr_mut(out_im), &twice, a_im);
    }

    #[inline]
    fn inv(out: &mut Limbs, a: &Limbs) {
        let a = *as_arr(a);
        let mut z = [0u64; NLIMBS];
        exp3div4(&mut z, &a);
        let mut z2 = [0u64; NLIMBS];
        mont_mul(&mut z2, &z, &z);
        let mut z4 = [0u64; NLIMBS];
        mont_mul(&mut z4, &z2, &z2);
        mont_mul(as_arr_mut(out), &a, &z4);
    }

    #[inline]
    fn sqrt(out: &mut Limbs, a: &Limbs) {
        let a = *as_arr(a);
        let mut z = [0u64; NLIMBS];
        exp3div4(&mut z, &a);
        mont_mul(as_arr_mut(out), &a, &z);
    }

    #[inline]
    fn is_square(a: &Limbs) -> Choice {
        let a = *as_arr(a);
        let mut z = [0u64; NLIMBS];
        exp3div4(&mut z, &a);
        let mut z2 = [0u64; NLIMBS];
        mont_mul(&mut z2, &z, &z);
        let mut s = [0u64; NLIMBS];
        mont_mul(&mut s, &a, &z2);
        eq_limbs(&canonical(&s), &ONE) | is_zero_limbs(&canonical(&a))
    }

    #[inline]
    fn half(out: &mut Limbs, a: &Limbs) {
        let mut c = *as_arr(a);
        let odd = 0u64.wrapping_sub(c[0] & 1);
        let mut carry = 0u64;
        for i in 0..NLIMBS {
            let (r, cy) = adc(c[i], P[i] & odd, carry);
            c[i] = r;
            carry = cy;
        }
        let out = as_arr_mut(out);
        for i in 0..NLIMBS - 1 {
            out[i] = (c[i] >> 1) | (c[i + 1] << 63);
        }
        out[NLIMBS - 1] = (c[NLIMBS - 1] >> 1) | (carry << 63);
    }

    #[inline]
    fn div3(out: &mut Limbs, a: &Limbs) {
        mont_mul(as_arr_mut(out), as_arr(a), &THREE_INV);
    }

    #[inline]
    fn exp3div4(out: &mut Limbs, a: &Limbs) {
        let a = *as_arr(a);
        exp3div4(as_arr_mut(out), &a);
    }

    #[inline]
    fn mul_small(out: &mut Limbs, a: &Limbs, val: u32) {
        let mut v = [0u64; NLIMBS];
        let mut vi = [0u64; NLIMBS];
        vi[0] = val as u64;
        mont_mul(&mut v, &vi, &R2);
        mont_mul(as_arr_mut(out), as_arr(a), &v);
    }

    #[inline]
    fn encode(out: &mut [u8], a: &Limbs) {
        let mut one = [0u64; NLIMBS];
        one[0] = 1;
        let mut x = [0u64; NLIMBS];
        mont_mul(&mut x, as_arr(a), &one);
        let x = canonical(&x);
        let mut buf = [0u8; 8 * NLIMBS];
        for i in 0..NLIMBS {
            buf[8 * i..8 * i + 8].copy_from_slice(&x[i].to_le_bytes());
        }
        out[..ENCODED_BYTES].copy_from_slice(&buf[..ENCODED_BYTES]);
    }

    #[inline]
    fn decode(out: &mut Limbs, bytes: &[u8]) -> Choice {
        let mut x = [0u64; NLIMBS];
        let ok = bytes_to_int(&mut x, bytes);
        mont_mul(as_arr_mut(out), &x, &R2);
        ok
    }

    #[inline]
    fn decode_reduce(out: &mut Limbs, bytes: &[u8]) {
        let out = as_arr_mut(out);
        *out = [0; NLIMBS];
        let mut len = bytes.len();
        let rem = len % CHUNK_BYTES;
        if rem != 0 {
            let mut tmp = [0u8; ENCODED_BYTES];
            tmp[..rem].copy_from_slice(&bytes[len - rem..]);
            let mut x = [0u64; NLIMBS];
            let _ = bytes_to_int(&mut x, &tmp);
            mont_mul(out, &x, &R2);
            len -= rem;
        }
        while len > 0 {
            len -= CHUNK_BYTES;
            let acc = *out;
            mont_mul(out, &acc, &CHUNK_R);
            let mut tmp = [0u8; ENCODED_BYTES];
            tmp[..CHUNK_BYTES].copy_from_slice(&bytes[len..len + CHUNK_BYTES]);
            let mut x = [0u64; NLIMBS];
            let _ = bytes_to_int(&mut x, &tmp);
            let mut chunk = [0u64; NLIMBS];
            mont_mul(&mut chunk, &x, &R2);
            let acc = *out;
            fp_add(out, &acc, &chunk);
        }
    }

    #[inline]
    fn cswap(a: &mut Limbs, b: &mut Limbs, ctl: Choice) {
        let m = 0u64.wrapping_sub(ctl.unwrap_u8() as u64);
        let (a, b) = (as_arr_mut(a), as_arr_mut(b));
        for i in 0..NLIMBS {
            let t = m & (a[i] ^ b[i]);
            a[i] ^= t;
            b[i] ^= t;
        }
    }

    #[inline]
    fn select(out: &mut Limbs, a0: &Limbs, a1: &Limbs, ctl: Choice) {
        let cw = 0u64.wrapping_sub(ctl.unwrap_u8() as u64);
        let (a0, a1, out) = (as_arr(a0), as_arr(a1), as_arr_mut(out));
        for i in 0..NLIMBS {
            out[i] = a0[i] ^ (cw & (a0[i] ^ a1[i]));
        }
    }
}
