//! Field arithmetic modulo `p = 17 * 2^664 - 1` (669 bits).
//!
//! Origin: SQIsign round 3, NIST level V.
//!
//! Elements are 11 limbs of 61 bits (unsaturated, 671 bits of
//! storage) in Montgomery form with `R = 2^671`. Arithmetic results
//! are lazily reduced to `[0, 2p)`; encoding and comparison reduce
//! fully. `2^610` divides `p + 1`, so the Montgomery reduction folds
//! each emitted low limb `v` back in as `v * 17 * 2^54` at limb
//! position 10.
//!
//! GENERATED by `tools/gen-fp`. Do not edit; change the generator.
//!
//! On x86-64 the trait implementation lives in `p664_17_asm.rs` (saturated
//! limbs; `mulx`/`adcx`/`adox` or portable kernels chosen at run time), and
//! this module is compiled but unused; elsewhere it is the implementation.
#![cfg_attr(target_arch = "x86_64", allow(dead_code, unused_imports))]

use super::FpBackend;
use crate::params::P664_17;
use hybrid_array::Array;
use subtle::Choice;

/// Number of 64-bit limbs in an `Fp` element.
pub const NLIMBS: usize = 11;

/// Bit width of each unsaturated limb.
pub const RADIX: u32 = 61;

/// `2^RADIX - 1`.
pub const MASK: u64 = (1u64 << RADIX) - 1;

/// Canonical encoding length in bytes.
pub const ENCODED_BYTES: usize = 84;

/// `(p + 1) / 2^610`: the contribution of `p + 1` to the top limb.
/// Montgomery folding constant in `modmul` and `modsqr`.
pub const PTOP: u64 = 0x440000000000000;

/// `2 * PTOP`, used to add or subtract `2p` in the lazy reductions.
pub const TWO_PTOP: u64 = 0x880000000000000;

/// The prime `p` as canonical little-endian bytes.
pub const PRIME_LE_BYTES: [u8; ENCODED_BYTES] = [
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0x10,
];

/// `0`.
pub const ZERO: [u64; NLIMBS] = [0; NLIMBS];

/// Montgomery form of `1` (`R mod p`).
pub const ONE: [u64; NLIMBS] = [
    0x0000000000000007,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0240000000000000,
];

/// Montgomery form of `2^-1 mod p`.
pub const TWO_INV: [u64; NLIMBS] = [
    0x0000000000000003,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0000000000000000,
    0x0340000000000000,
];

/// Montgomery form of `3^-1 mod p`.
pub const THREE_INV: [u64; NLIMBS] = [
    0x1555555555555557,
    0x0aaaaaaaaaaaaaaa,
    0x1555555555555555,
    0x0aaaaaaaaaaaaaaa,
    0x1555555555555555,
    0x0aaaaaaaaaaaaaaa,
    0x1555555555555555,
    0x0aaaaaaaaaaaaaaa,
    0x1555555555555555,
    0x0aaaaaaaaaaaaaaa,
    0x0395555555555555,
];

/// `R^2 mod p`: multiplying a canonical integer by this in Montgomery
/// multiplication converts it to Montgomery form.
pub const R2_NRES: [u64; NLIMBS] = [
    0x03c3c3c3c3c3c3fc,
    0x1e1e1e1e1e1e1e1e,
    0x10f0f0f0f0f0f0f0,
    0x0787878787878787,
    0x1c3c3c3c3c3c3c3c,
    0x01e1e1e1e1e1e1e1,
    0x0f0f0f0f0f0f0f0f,
    0x1878787878787878,
    0x03c3c3c3c3c3c3c3,
    0x1e1e1e1e1e1e1e1e,
    0x01f0f0f0f0f0f0f0,
];

/// Montgomery form of `2^664`: shifts the accumulator by one
/// 83-byte chunk in `fp_decode_reduce`.
pub const CHUNK_R: [u64; NLIMBS] = [
    0x0787878787878787,
    0x1c3c3c3c3c3c3c3c,
    0x01e1e1e1e1e1e1e1,
    0x0f0f0f0f0f0f0f0f,
    0x1878787878787878,
    0x03c3c3c3c3c3c3c3,
    0x1e1e1e1e1e1e1e1e,
    0x10f0f0f0f0f0f0f0,
    0x0787878787878787,
    0x1c3c3c3c3c3c3c3c,
    0x0421e1e1e1e1e1e1,
];

/// Propagate carries so limbs `0..10` are in `[0, 2^RADIX)` and the top
/// limb holds the overflow. Returns all-ones if the value is negative
/// (top bit of the top limb set), else zero.
#[inline]
pub(crate) fn prop(n: &mut [u64; NLIMBS]) -> u64 {
    let mut carry: i64 = n[0] as i64;
    carry >>= RADIX;
    n[0] &= MASK;
    for limb in n.iter_mut().take(10).skip(1) {
        carry = carry.wrapping_add(*limb as i64);
        *limb = (carry as u64) & MASK;
        carry >>= RADIX;
    }
    n[10] = n[10].wrapping_add(carry as u64);
    0u64.wrapping_sub(n[10] >> 63)
}

/// [`prop`], then add `p` back if the value went negative, then [`prop`]
/// again. Returns `1` if the fix-up happened.
#[inline]
pub(crate) fn flatten(n: &mut [u64; NLIMBS]) -> u32 {
    let carry = prop(n);
    n[0] = n[0].wrapping_sub(1 & carry);
    n[10] = n[10].wrapping_add(PTOP & carry);
    let _ = prop(n);
    (carry & 1) as u32
}

/// Final subtraction of `p`: `n -= p`, undone if that went negative.
/// Returns `1` if the input was already `< p`.
#[inline]
pub(crate) fn modfsb(n: &mut [u64; NLIMBS]) -> u32 {
    n[0] = n[0].wrapping_add(1);
    n[10] = n[10].wrapping_sub(PTOP);
    flatten(n)
}

/// `n <- a + b mod 2p` (lazily reduced).
#[inline]
pub(crate) fn modadd(n: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    n[0] = a[0].wrapping_add(b[0]);
    n[1] = a[1].wrapping_add(b[1]);
    n[2] = a[2].wrapping_add(b[2]);
    n[3] = a[3].wrapping_add(b[3]);
    n[4] = a[4].wrapping_add(b[4]);
    n[5] = a[5].wrapping_add(b[5]);
    n[6] = a[6].wrapping_add(b[6]);
    n[7] = a[7].wrapping_add(b[7]);
    n[8] = a[8].wrapping_add(b[8]);
    n[9] = a[9].wrapping_add(b[9]);
    n[10] = a[10].wrapping_add(b[10]);
    n[0] = n[0].wrapping_add(2);
    n[10] = n[10].wrapping_sub(TWO_PTOP);
    let carry = prop(n);
    n[0] = n[0].wrapping_sub(2 & carry);
    n[10] = n[10].wrapping_add(TWO_PTOP & carry);
    let _ = prop(n);
}

/// `n <- a - b mod 2p` (lazily reduced).
#[inline]
pub(crate) fn modsub(n: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    n[0] = a[0].wrapping_sub(b[0]);
    n[1] = a[1].wrapping_sub(b[1]);
    n[2] = a[2].wrapping_sub(b[2]);
    n[3] = a[3].wrapping_sub(b[3]);
    n[4] = a[4].wrapping_sub(b[4]);
    n[5] = a[5].wrapping_sub(b[5]);
    n[6] = a[6].wrapping_sub(b[6]);
    n[7] = a[7].wrapping_sub(b[7]);
    n[8] = a[8].wrapping_sub(b[8]);
    n[9] = a[9].wrapping_sub(b[9]);
    n[10] = a[10].wrapping_sub(b[10]);
    let carry = prop(n);
    n[0] = n[0].wrapping_sub(2 & carry);
    n[10] = n[10].wrapping_add(TWO_PTOP & carry);
    let _ = prop(n);
}

/// `n <- -b mod 2p` (lazily reduced).
#[inline]
pub(crate) fn modneg(n: &mut [u64; NLIMBS], b: &[u64; NLIMBS]) {
    n[0] = 0u64.wrapping_sub(b[0]);
    n[1] = 0u64.wrapping_sub(b[1]);
    n[2] = 0u64.wrapping_sub(b[2]);
    n[3] = 0u64.wrapping_sub(b[3]);
    n[4] = 0u64.wrapping_sub(b[4]);
    n[5] = 0u64.wrapping_sub(b[5]);
    n[6] = 0u64.wrapping_sub(b[6]);
    n[7] = 0u64.wrapping_sub(b[7]);
    n[8] = 0u64.wrapping_sub(b[8]);
    n[9] = 0u64.wrapping_sub(b[9]);
    n[10] = 0u64.wrapping_sub(b[10]);
    let carry = prop(n);
    n[0] = n[0].wrapping_sub(2 & carry);
    n[10] = n[10].wrapping_add(TWO_PTOP & carry);
    let _ = prop(n);
}

/// `c <- a * b * R^-1 mod 2p`. Schoolbook 11x11 product in radix `2^61`
/// with interleaved Montgomery folding: each emitted low limb `v_i` is
/// added back at position `i + 10` as `v_i * PTOP`, which is
/// `v_i * (p + 1) = v_i (mod p)` and divides the result by `R`.
#[inline]
pub(crate) fn modmul(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], b: &[u64; NLIMBS]) {
    let ptop = PTOP as u128;
    let mut t: u128 = 0;
    t = t.wrapping_add((a[0] as u128) * (b[0] as u128));
    let v0 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[0] as u128));
    let v1 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[0] as u128));
    let v2 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[0] as u128));
    let v3 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[0] as u128));
    let v4 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[0] as u128));
    let v5 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[0] as u128));
    let v6 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[0] as u128));
    let v7 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[0] as u128));
    let v8 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[0] as u128));
    let v9 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[0] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[1] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[1] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[0] as u128));
    t = t.wrapping_add((v0 as u128) * ptop);
    let v10 = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[1] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[2] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[2] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[1] as u128));
    t = t.wrapping_add((v1 as u128) * ptop);
    c[0] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[2] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[3] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[3] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[2] as u128));
    t = t.wrapping_add((v2 as u128) * ptop);
    c[1] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[3] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[4] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[4] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[3] as u128));
    t = t.wrapping_add((v3 as u128) * ptop);
    c[2] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[4] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[5] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[5] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[4] as u128));
    t = t.wrapping_add((v4 as u128) * ptop);
    c[3] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[5] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[6] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[6] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[5] as u128));
    t = t.wrapping_add((v5 as u128) * ptop);
    c[4] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[6] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[7] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[7] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[6] as u128));
    t = t.wrapping_add((v6 as u128) * ptop);
    c[5] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[7] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[8] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[8] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[7] as u128));
    t = t.wrapping_add((v7 as u128) * ptop);
    c[6] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[8] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[9] as u128) * (b[9] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[8] as u128));
    t = t.wrapping_add((v8 as u128) * ptop);
    c[7] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[9] as u128) * (b[10] as u128));
    t = t.wrapping_add((a[10] as u128) * (b[9] as u128));
    t = t.wrapping_add((v9 as u128) * ptop);
    c[8] = (t as u64) & MASK;
    t >>= RADIX;
    t = t.wrapping_add((a[10] as u128) * (b[10] as u128));
    t = t.wrapping_add((v10 as u128) * ptop);
    c[9] = (t as u64) & MASK;
    t >>= RADIX;
    c[10] = t as u64;
}

/// `c <- a * a * R^-1 mod 2p`. Each cross term `a_i * a_j`, `i != j`, is
/// computed once and doubled.
#[inline]
pub(crate) fn modsqr(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS]) {
    let ptop = PTOP as u128;
    let mut t: u128 = 0;
    let mut tot: u128;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[0] as u128));
    t = t.wrapping_add(tot);
    let v0 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[1] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    let v1 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[2] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[1] as u128) * (a[1] as u128));
    t = t.wrapping_add(tot);
    let v2 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[3] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[2] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    let v3 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[4] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[3] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[2] as u128) * (a[2] as u128));
    t = t.wrapping_add(tot);
    let v4 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[5] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[4] as u128));
    tot = tot.wrapping_add((a[2] as u128) * (a[3] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    let v5 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[6] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[5] as u128));
    tot = tot.wrapping_add((a[2] as u128) * (a[4] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[3] as u128) * (a[3] as u128));
    t = t.wrapping_add(tot);
    let v6 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[7] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[6] as u128));
    tot = tot.wrapping_add((a[2] as u128) * (a[5] as u128));
    tot = tot.wrapping_add((a[3] as u128) * (a[4] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    let v7 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[8] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[7] as u128));
    tot = tot.wrapping_add((a[2] as u128) * (a[6] as u128));
    tot = tot.wrapping_add((a[3] as u128) * (a[5] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[4] as u128) * (a[4] as u128));
    t = t.wrapping_add(tot);
    let v8 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[9] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[8] as u128));
    tot = tot.wrapping_add((a[2] as u128) * (a[7] as u128));
    tot = tot.wrapping_add((a[3] as u128) * (a[6] as u128));
    tot = tot.wrapping_add((a[4] as u128) * (a[5] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    let v9 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[0] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[1] as u128) * (a[9] as u128));
    tot = tot.wrapping_add((a[2] as u128) * (a[8] as u128));
    tot = tot.wrapping_add((a[3] as u128) * (a[7] as u128));
    tot = tot.wrapping_add((a[4] as u128) * (a[6] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[5] as u128) * (a[5] as u128));
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v0 as u128) * ptop);
    let v10 = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[1] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[2] as u128) * (a[9] as u128));
    tot = tot.wrapping_add((a[3] as u128) * (a[8] as u128));
    tot = tot.wrapping_add((a[4] as u128) * (a[7] as u128));
    tot = tot.wrapping_add((a[5] as u128) * (a[6] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v1 as u128) * ptop);
    c[0] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[2] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[3] as u128) * (a[9] as u128));
    tot = tot.wrapping_add((a[4] as u128) * (a[8] as u128));
    tot = tot.wrapping_add((a[5] as u128) * (a[7] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[6] as u128) * (a[6] as u128));
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v2 as u128) * ptop);
    c[1] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[3] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[4] as u128) * (a[9] as u128));
    tot = tot.wrapping_add((a[5] as u128) * (a[8] as u128));
    tot = tot.wrapping_add((a[6] as u128) * (a[7] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v3 as u128) * ptop);
    c[2] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[4] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[5] as u128) * (a[9] as u128));
    tot = tot.wrapping_add((a[6] as u128) * (a[8] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[7] as u128) * (a[7] as u128));
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v4 as u128) * ptop);
    c[3] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[5] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[6] as u128) * (a[9] as u128));
    tot = tot.wrapping_add((a[7] as u128) * (a[8] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v5 as u128) * ptop);
    c[4] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[6] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[7] as u128) * (a[9] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[8] as u128) * (a[8] as u128));
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v6 as u128) * ptop);
    c[5] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[7] as u128) * (a[10] as u128));
    tot = tot.wrapping_add((a[8] as u128) * (a[9] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v7 as u128) * ptop);
    c[6] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[8] as u128) * (a[10] as u128));
    tot = tot.wrapping_mul(2);
    tot = tot.wrapping_add((a[9] as u128) * (a[9] as u128));
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v8 as u128) * ptop);
    c[7] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[9] as u128) * (a[10] as u128));
    tot = tot.wrapping_mul(2);
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v9 as u128) * ptop);
    c[8] = (t as u64) & MASK;
    t >>= RADIX;
    tot = 0;
    tot = tot.wrapping_add((a[10] as u128) * (a[10] as u128));
    t = t.wrapping_add(tot);
    t = t.wrapping_add((v10 as u128) * ptop);
    c[9] = (t as u64) & MASK;
    t >>= RADIX;
    c[10] = t as u64;
}

/// Square `a` in place `n` times.
#[inline]
pub(crate) fn modnsqr(a: &mut [u64; NLIMBS], n: u32) {
    for _ in 0..n {
        let mut tmp = [0u64; NLIMBS];
        modsqr(&mut tmp, a);
        *a = tmp;
    }
}

/// `a <- a * b`.
#[inline]
fn mul_assign(a: &mut [u64; NLIMBS], b: &[u64; NLIMBS]) {
    let mut tmp = [0u64; NLIMBS];
    modmul(&mut tmp, a, b);
    *a = tmp;
}

/// Square-root progenitor: `z <- w^((p-3)/4) mod p`, computed with a
/// fixed 5-bit sliding-window chain over the public exponent
/// (666 squarings, 134 multiplications after a 16-entry table).
/// Since `p = 3 mod 4`, `sqrt(w) = w * z` and `1/w = w * z^4`.
#[inline]
pub(crate) fn modpro(z: &mut [u64; NLIMBS], w: &[u64; NLIMBS]) {
    // tab[j] = w^(2j + 1)
    let mut tab = [[0u64; NLIMBS]; 16];
    let mut w2 = [0u64; NLIMBS];
    modsqr(&mut w2, w);
    tab[0] = *w;
    for j in 1..16 {
        let prev = tab[j - 1];
        modmul(&mut tab[j], &prev, &w2);
    }
    *z = tab[0];
    modnsqr(z, 9);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 5);
    mul_assign(z, &tab[15]);
    modnsqr(z, 2);
    mul_assign(z, &tab[1]);
}

/// `z <- 1 / x mod p` (`0` for `x = 0`). `h`, if given, is the precomputed
/// progenitor `x^((p-3)/4)`.
#[inline]
pub(crate) fn modinv(z: &mut [u64; NLIMBS], x: &[u64; NLIMBS], h: Option<&[u64; NLIMBS]>) {
    let mut t = [0u64; NLIMBS];
    match h {
        None => modpro(&mut t, x),
        Some(h) => t = *h,
    }
    modnsqr(&mut t, 2);
    modmul(z, x, &t);
}

/// Canonical integer to Montgomery form.
#[inline]
pub(crate) fn nres(n: &mut [u64; NLIMBS], m: &[u64; NLIMBS]) {
    modmul(n, m, &R2_NRES);
}

/// Montgomery form to canonical integer in `[0, p)`.
#[inline]
pub(crate) fn redc(m: &mut [u64; NLIMBS], n: &[u64; NLIMBS]) {
    let mut c = [0u64; NLIMBS];
    c[0] = 1;
    modmul(m, n, &c);
    let _ = modfsb(m);
}

/// `1` if `a == 0 mod p`, else `0`.
#[inline]
pub(crate) fn modis0(a: &[u64; NLIMBS]) -> u32 {
    let mut c = [0u64; NLIMBS];
    redc(&mut c, a);
    let mut d: u64 = 0;
    for limb in c.iter() {
        d |= *limb;
    }
    (1 & (d.wrapping_sub(1) >> RADIX)) as u32
}

/// `1` if `a == 1 mod p`, else `0`.
#[inline]
pub(crate) fn modis1(a: &[u64; NLIMBS]) -> u32 {
    let mut c = [0u64; NLIMBS];
    redc(&mut c, a);
    let mut d: u64 = 0;
    for limb in c.iter().skip(1) {
        d |= *limb;
    }
    (1 & (d.wrapping_sub(1) >> RADIX) & ((c[0] ^ 1).wrapping_sub(1) >> RADIX)) as u32
}

/// `1` if `a == b mod p`, else `0`.
#[inline]
pub(crate) fn modcmp(a: &[u64; NLIMBS], b: &[u64; NLIMBS]) -> u32 {
    let mut c = [0u64; NLIMBS];
    let mut d = [0u64; NLIMBS];
    redc(&mut c, a);
    redc(&mut d, b);
    let mut eq: u64 = 1;
    for i in 0..NLIMBS {
        eq &= (c[i] ^ d[i]).wrapping_sub(1) >> RADIX;
    }
    (eq & 1) as u32
}

/// `1` if `x` is a square (or zero), else `0`. `h` is the optional
/// precomputed progenitor.
#[inline]
pub(crate) fn modqr(x: &[u64; NLIMBS], h: Option<&[u64; NLIMBS]>) -> u32 {
    let mut r = [0u64; NLIMBS];
    match h {
        None => {
            let mut pro = [0u64; NLIMBS];
            modpro(&mut pro, x);
            modsqr(&mut r, &pro);
        }
        Some(h) => modsqr(&mut r, h),
    }
    mul_assign(&mut r, x);
    modis1(&r) | modis0(x)
}

/// `r <- sqrt(x)` for square `x` (`x^((p+1)/4)`), defined up to sign.
#[inline]
pub(crate) fn modsqrt(r: &mut [u64; NLIMBS], x: &[u64; NLIMBS], h: Option<&[u64; NLIMBS]>) {
    let mut y = [0u64; NLIMBS];
    match h {
        None => modpro(&mut y, x),
        Some(h) => y = *h,
    }
    modmul(r, &y, x);
}

/// `a <- x` in Montgomery form.
#[inline]
pub(crate) fn modint(a: &mut [u64; NLIMBS], x: u64) {
    let mut m = [0u64; NLIMBS];
    m[0] = x;
    nres(a, &m);
}

/// `c <- a * x mod 2p` for a small integer `x`.
#[inline]
pub(crate) fn modmli(c: &mut [u64; NLIMBS], a: &[u64; NLIMBS], x: u64) {
    let mut t = [0u64; NLIMBS];
    modint(&mut t, x);
    modmul(c, a, &t);
}

/// Shift left by `n < RADIX` bits, carrying into the next limb.
#[inline]
pub(crate) fn modshl(a: &mut [u64; NLIMBS], n: u32) {
    a[10] = (a[10] << n) | (a[9] >> (RADIX - n));
    for i in (1..10).rev() {
        a[i] = ((a[i] << n) & MASK) | (a[i - 1] >> (RADIX - n));
    }
    a[0] = (a[0] << n) & MASK;
}

/// Shift right by `n < RADIX` bits, returning the bits shifted out.
#[inline]
pub(crate) fn modshr(a: &mut [u64; NLIMBS], n: u32) -> u64 {
    let r = a[0] & ((1u64 << n) - 1);
    for i in 0..10 {
        a[i] = (a[i] >> n) | ((a[i + 1] << (RADIX - n)) & MASK);
    }
    a[10] >>= n;
    r
}

/// Constant-time conditional swap of `f` and `g` when `b == 1`.
#[inline]
pub(crate) fn modcsw(b: u64, g: &mut [u64; NLIMBS], f: &mut [u64; NLIMBS]) {
    let r: u64 = 0x3cc3_c33c_5aa5_a55a;
    let c0 = (1u64.wrapping_sub(b)).wrapping_add(r);
    let c1 = b.wrapping_add(r);
    for i in 0..NLIMBS {
        let s = g[i];
        let t = f[i];
        let w = r.wrapping_mul(t.wrapping_add(s));
        f[i] = c0
            .wrapping_mul(t)
            .wrapping_add(c1.wrapping_mul(s))
            .wrapping_sub(w);
        g[i] = c0
            .wrapping_mul(s)
            .wrapping_add(c1.wrapping_mul(t))
            .wrapping_sub(w);
    }
}

/// Canonical little-endian encoding of `a` into `ENCODED_BYTES` bytes.
#[inline]
pub(crate) fn fp_encode(out: &mut [u8], a: &[u64; NLIMBS]) {
    debug_assert!(out.len() >= ENCODED_BYTES);
    let mut c = [0u64; NLIMBS];
    redc(&mut c, a);
    for byte in out.iter_mut().take(ENCODED_BYTES) {
        *byte = (c[0] & 0xff) as u8;
        let _ = modshr(&mut c, 8);
    }
}

/// Decode `ENCODED_BYTES` canonical little-endian bytes. Returns all-ones
/// if the value was in `[0, p)`, else zero with `out` zeroed.
#[inline]
pub(crate) fn fp_decode(out: &mut [u64; NLIMBS], bytes: &[u8]) -> u32 {
    *out = [0; NLIMBS];
    if bytes.len() < ENCODED_BYTES {
        return 0;
    }
    for i in (0..ENCODED_BYTES).rev() {
        modshl(out, 8);
        out[0] = out[0].wrapping_add(bytes[i] as u64);
    }
    let ok = 0u64.wrapping_sub(modfsb(out) as u64);
    let canonical = *out;
    nres(out, &canonical);
    for limb in out.iter_mut() {
        *limb &= ok;
    }
    ok as u32
}

/// Bytes consumed per step of [`fp_decode_reduce`]. One byte short of the
/// encoding length, so every chunk is below `p` and decodes without
/// reduction.
const CHUNK_BYTES: usize = ENCODED_BYTES - 1;

/// Decode a little-endian byte string of any length modulo `p`. Never
/// fails; used to map hash output into the field.
#[inline]
pub(crate) fn fp_decode_reduce(out: &mut [u64; NLIMBS], bytes: &[u8]) {
    *out = [0; NLIMBS];
    let mut len = bytes.len();
    let rem = len % CHUNK_BYTES;
    if rem != 0 {
        let mut tmp = [0u8; ENCODED_BYTES];
        tmp[..rem].copy_from_slice(&bytes[len - rem..]);
        let _ = fp_decode(out, &tmp);
        len -= rem;
    }
    while len > 0 {
        len -= CHUNK_BYTES;
        mul_assign(out, &CHUNK_R);
        let mut tmp = [0u8; ENCODED_BYTES];
        tmp[..CHUNK_BYTES].copy_from_slice(&bytes[len..len + CHUNK_BYTES]);
        let mut chunk = [0u64; NLIMBS];
        let _ = fp_decode(&mut chunk, &tmp);
        let acc = *out;
        modadd(out, &acc, &chunk);
    }
}

type Limbs = Array<u64, <P664_17 as crate::params::Prime>::FpLimbs>;

#[inline]
fn as_arr(a: &Limbs) -> &[u64; NLIMBS] {
    <&[u64; NLIMBS]>::try_from(&a[..]).expect("invariant: FpLimbs == NLIMBS")
}

#[inline]
fn as_arr_mut(a: &mut Limbs) -> &mut [u64; NLIMBS] {
    <&mut [u64; NLIMBS]>::try_from(&mut a[..]).expect("invariant: FpLimbs == NLIMBS")
}

#[cfg(not(target_arch = "x86_64"))]
impl FpBackend for P664_17 {
    #[inline]
    fn set_zero(out: &mut Limbs) {
        *as_arr_mut(out) = ZERO;
    }

    #[inline]
    fn set_one(out: &mut Limbs) {
        *as_arr_mut(out) = ONE;
    }

    #[inline]
    fn set_small(out: &mut Limbs, val: u64) {
        modint(as_arr_mut(out), val);
    }

    #[inline]
    fn is_equal(a: &Limbs, b: &Limbs) -> Choice {
        Choice::from(modcmp(as_arr(a), as_arr(b)) as u8)
    }

    #[inline]
    fn is_zero(a: &Limbs) -> Choice {
        Choice::from(modis0(as_arr(a)) as u8)
    }

    #[inline]
    fn copy(out: &mut Limbs, a: &Limbs) {
        *as_arr_mut(out) = *as_arr(a);
    }

    #[inline]
    fn add(out: &mut Limbs, a: &Limbs, b: &Limbs) {
        modadd(as_arr_mut(out), as_arr(a), as_arr(b));
    }

    #[inline]
    fn sub(out: &mut Limbs, a: &Limbs, b: &Limbs) {
        modsub(as_arr_mut(out), as_arr(a), as_arr(b));
    }

    #[inline]
    fn neg(out: &mut Limbs, a: &Limbs) {
        modneg(as_arr_mut(out), as_arr(a));
    }

    #[inline]
    fn mul(out: &mut Limbs, a: &Limbs, b: &Limbs) {
        modmul(as_arr_mut(out), as_arr(a), as_arr(b));
    }

    #[inline]
    fn sqr(out: &mut Limbs, a: &Limbs) {
        modsqr(as_arr_mut(out), as_arr(a));
    }

    #[inline]
    fn inv(out: &mut Limbs, a: &Limbs) {
        let a = *as_arr(a);
        modinv(as_arr_mut(out), &a, None);
    }

    #[inline]
    fn sqrt(out: &mut Limbs, a: &Limbs) {
        let a = *as_arr(a);
        modsqrt(as_arr_mut(out), &a, None);
    }

    #[inline]
    fn is_square(a: &Limbs) -> Choice {
        Choice::from(modqr(as_arr(a), None) as u8)
    }

    #[inline]
    fn half(out: &mut Limbs, a: &Limbs) {
        modmul(as_arr_mut(out), &TWO_INV, as_arr(a));
    }

    #[inline]
    fn div3(out: &mut Limbs, a: &Limbs) {
        modmul(as_arr_mut(out), &THREE_INV, as_arr(a));
    }

    #[inline]
    fn exp3div4(out: &mut Limbs, a: &Limbs) {
        let a = *as_arr(a);
        modpro(as_arr_mut(out), &a);
    }

    #[inline]
    fn mul_small(out: &mut Limbs, a: &Limbs, val: u32) {
        modmli(as_arr_mut(out), as_arr(a), val as u64);
    }

    #[inline]
    fn encode(out: &mut [u8], a: &Limbs) {
        fp_encode(out, as_arr(a));
    }

    #[inline]
    fn decode(out: &mut Limbs, bytes: &[u8]) -> Choice {
        Choice::from((fp_decode(as_arr_mut(out), bytes) & 1) as u8)
    }

    #[inline]
    fn decode_reduce(out: &mut Limbs, bytes: &[u8]) {
        fp_decode_reduce(as_arr_mut(out), bytes);
    }

    #[inline]
    fn cswap(a: &mut Limbs, b: &mut Limbs, ctl: Choice) {
        modcsw(ctl.unwrap_u8() as u64, as_arr_mut(a), as_arr_mut(b));
    }

    #[inline]
    fn select(out: &mut Limbs, a0: &Limbs, a1: &Limbs, ctl: Choice) {
        let cw = 0u64.wrapping_sub(ctl.unwrap_u8() as u64);
        let a0 = as_arr(a0);
        let a1 = as_arr(a1);
        let out = as_arr_mut(out);
        for i in 0..NLIMBS {
            out[i] = a0[i] ^ (cw & (a0[i] ^ a1[i]));
        }
    }
}
