#!/usr/bin/env sage
"""
Generate Rust precomputed constants for all SQIsign security levels.

This script runs the same mathematical computations as the C reference's
precompute scripts but outputs Rust source instead of C source.

Usage:
    sage generate_rust_constants.sage <level> <output_dir>

where <level> is 1, 3, or 5 and <output_dir> is the target directory
(e.g., ../../crates/precomp/src/level1/)
"""


# This file was *autogenerated* from the file /home/user/sqisign-rs/scripts/precomp/generate_rust_constants.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_128 = Integer(128); _sage_const_64 = Integer(64); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_0xFFFFFFFFFFFFFFFF = Integer(0xFFFFFFFFFFFFFFFF)
proof.all(False)  # faster

import sys
import os

if len(sys.argv) < _sage_const_3 :
    print('Usage: sage generate_rust_constants.sage <level> <output_dir>')
    sys.exit(_sage_const_1 )

level = int(sys.argv[_sage_const_1 ])
output_dir = sys.argv[_sage_const_2 ]

os.makedirs(output_dir, exist_ok=True)

# Set up the working directory to find parameters.py etc.
ref_precomp_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', 'reference', 'src', 'precomp', 'ref', f'lvl{level}')
ref_precomp_dir = os.path.realpath(ref_precomp_dir)
print(f'Reference precomp dir: {ref_precomp_dir}')

# Add the reference scripts dir to path so we can import cformat etc.
ref_scripts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', 'reference', 'scripts', 'precomp')
ref_scripts_dir = os.path.realpath(ref_scripts_dir)
sys.path.insert(_sage_const_0 , ref_scripts_dir)

# Change to the reference precomp level dir so parameters.py can find sqisign_parameters.txt
orig_dir = os.getcwd()
os.chdir(ref_precomp_dir)

from parameters import p, f, num_orders

print(f'Level {level}: p = {hex(p)}, f = {f}, num_orders = {num_orders}')

# ============================================================
# 1. torsion_constants.rs
# ============================================================
print('\n--- Generating torsion_constants.rs ---')

tors2part = (p+_sage_const_1 ).p_primary_part(_sage_const_2 )
lambda_security = round(p.bit_length() / _sage_const_128 ) * _sage_const_64 
N_sec = next_prime(_sage_const_1  << (_sage_const_4 *lambda_security))
N_com = N_sec

with open(os.path.join(output_dir, 'torsion_constants.rs'), 'w') as out:
    out.write('//! Torsion degree constants.\n')
    out.write('//!\n')
    out.write('//! Generated by SageMath precompute scripts. DO NOT EDIT.\n\n')
    out.write('use num_bigint::BigInt;\n')
    out.write('use once_cell::sync::Lazy;\n\n')
    out.write('type Ibz = BigInt;\n\n')
    out.write('fn ibz(s: &str) -> Ibz {\n')
    out.write('    s.parse::<Ibz>().unwrap()\n')
    out.write('}\n\n')
    out.write(f'pub const TORSION_2POWER_BYTES: usize = {(int(tors2part).bit_length() + _sage_const_7 ) // _sage_const_8 };\n\n')
    out.write('lazy_static::lazy_static! {\n')
    out.write(f'    pub static ref TWO_TO_SECURITY_BITS: Ibz = ibz("{_sage_const_1  << lambda_security}");\n')
    out.write(f'    pub static ref TORSION_PLUS_2POWER: Ibz = ibz("{tors2part}");\n')
    out.write(f'    pub static ref SEC_DEGREE: Ibz = ibz("{N_sec}");\n')
    out.write(f'    pub static ref COM_DEGREE: Ibz = ibz("{N_com}");\n')
    out.write('}\n')

print(f'  wrote torsion_constants.rs')


# ============================================================
# 2. quaternion_constants.rs
# ============================================================
print('\n--- Generating quaternion_constants.rs ---')

from cformat import Ibz as CIbz

# Read the constants from the C header to get the exact same values
# Actually, compute them the same way the C script does
with open(os.path.join(output_dir, 'quaternion_constants.rs'), 'w') as out:
    out.write('//! Quaternion algorithm parameters.\n')
    out.write('//!\n')
    out.write('//! Generated by SageMath precompute scripts. DO NOT EDIT.\n\n')
    out.write(f'pub const QUAT_PRIMALITY_NUM_ITER: u32 = 32;\n')
    out.write(f'pub const QUAT_REPRES_BOUND_INPUT: u32 = 20;\n')
    out.write(f'pub const QUAT_EQUIV_BOUND_COEFF: i32 = 64;\n')
    out.write(f'pub const FINDUV_BOX_SIZE: u32 = 2;\n')
    out.write(f'pub const FINDUV_CUBE_SIZE: u32 = 624;\n')
    out.write(f'pub const NUM_EXTREMAL_ORDERS: usize = {num_orders};\n')
    out.write(f'pub const NUM_ALTERNATE_EXTREMAL_ORDERS: usize = {num_orders - _sage_const_1 };\n')

print(f'  wrote quaternion_constants.rs')


# ============================================================
# 3. quaternion_data.rs
# ============================================================
print('\n--- Generating quaternion_data.rs ---')

from maxorders import orders

bitlength_p = int(p).bit_length()
prime_cofactor = next_prime(_sage_const_2 **bitlength_p)

with open(os.path.join(output_dir, 'quaternion_data.rs'), 'w') as out:
    out.write('//! Quaternion algebra precomputed data: extremal orders, connecting ideals,\n')
    out.write('//! and conjugating elements.\n')
    out.write('//!\n')
    out.write('//! Generated by SageMath precompute scripts. DO NOT EDIT.\n\n')
    out.write('use num_bigint::BigInt;\n')
    out.write('use once_cell::sync::Lazy;\n\n')
    out.write('type Ibz = BigInt;\n\n')
    out.write('fn ibz(s: &str) -> Ibz {\n')
    out.write('    s.parse::<Ibz>().unwrap()\n')
    out.write('}\n\n')

    # QUAT_prime_cofactor
    out.write(f'/// Prime cofactor for random ideal generation: next_prime(2^{bitlength_p})\n')
    out.write(f'pub static QUAT_PRIME_COFACTOR: Lazy<Ibz> = Lazy::new(|| ibz("{prime_cofactor}"));\n\n')

    # QUATALG_PINFTY (just the prime p)
    out.write(f'/// The quaternion algebra prime p.\n')
    out.write(f'pub static QUATALG_P: Lazy<Ibz> = Lazy::new(|| ibz("{p}"));\n\n')

    # EXTREMAL_ORDERS
    out.write(f'/// Number of precomputed extremal orders.\n')
    out.write(f'pub const NUM_ORDERS: usize = {len(orders)};\n\n')

    # Generate each extremal order
    out.write('/// Precomputed p-extremal maximal orders.\n')
    out.write('///\n')
    out.write('/// Each order is represented as:\n')
    out.write('/// - `q`: the level (1 for standard O0, prime q for alternates)\n')
    out.write('/// - `order_denom`: denominator of the order basis matrix\n')
    out.write('/// - `order_basis`: 4x4 basis matrix (column-major, transposed from math notation)\n')
    out.write('/// - `i_denom`: denominator of sqrt(-q) in the order\n')
    out.write('/// - `i_coord`: coordinates of sqrt(-q)\n')
    out.write('/// - `j_denom`: denominator of sqrt(-p) (always 1)\n')
    out.write('/// - `j_coord`: coordinates of sqrt(-p) (always [0,0,1,0])\n')

    for idx, (q, iso1q, mat, ii, idl, gamma) in enumerate(orders):
        out.write(f'\n// ---- Extremal order {idx} (q={q}) ----\n\n')

        # Order basis
        denom = mat.denominator()
        basis = (mat.transpose() * denom)
        out.write(f'pub static EXTREMAL_ORDER_{idx}_Q: i64 = {q};\n')
        out.write(f'pub static EXTREMAL_ORDER_{idx}_DENOM: Lazy<Ibz> = Lazy::new(|| ibz("{denom}"));\n')

        for i in range(_sage_const_4 ):
            for j in range(_sage_const_4 ):
                val = int(basis[i][j])
                out.write(f'pub static EXTREMAL_ORDER_{idx}_BASIS_{i}{j}: Lazy<Ibz> = Lazy::new(|| ibz("{val}"));\n')

        # sqrt(-q) element
        ii_denom = mat.denominator()
        ii_coords = [int(c) for c in ii * ii_denom]
        out.write(f'pub static EXTREMAL_ORDER_{idx}_I_DENOM: Lazy<Ibz> = Lazy::new(|| ibz("{ii_denom}"));\n')
        for k, c in enumerate(ii_coords):
            out.write(f'pub static EXTREMAL_ORDER_{idx}_I_COORD_{k}: Lazy<Ibz> = Lazy::new(|| ibz("{c}"));\n')

    # CONNECTING_IDEALS
    out.write(f'\n// ---- Connecting ideals ----\n\n')

    for idx, (q, iso1q, mat, ii, idl, gamma) in enumerate(orders):
        out.write(f'// Connecting ideal {idx} (q={q})\n')
        denom = idl.denominator()
        basis = (idl.transpose() * denom)
        out.write(f'pub static CONNECTING_IDEAL_{idx}_DENOM: Lazy<Ibz> = Lazy::new(|| ibz("{denom}"));\n')

        for i in range(_sage_const_4 ):
            for j in range(_sage_const_4 ):
                val = int(basis[i][j])
                out.write(f'pub static CONNECTING_IDEAL_{idx}_BASIS_{i}{j}: Lazy<Ibz> = Lazy::new(|| ibz("{val}"));\n')

        # Norm: |I ∩ Z| = first basis element divided to get generator
        norm_val = abs(int(idl.row_space(ZZ).intersection((ZZ**_sage_const_4 ).submodule([[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ]])).basis()[_sage_const_0 ][_sage_const_0 ]))
        out.write(f'pub static CONNECTING_IDEAL_{idx}_NORM: Lazy<Ibz> = Lazy::new(|| ibz("{norm_val}"));\n')
        out.write('\n')

    # CONJUGATING_ELEMENTS
    out.write(f'// ---- Conjugating elements ----\n\n')

    for idx, (q, iso1q, mat, ii, idl, gamma) in enumerate(orders):
        out.write(f'// Conjugating element {idx} (q={q})\n')
        denom = gamma.denominator()
        coords = [int(c) for c in gamma * denom]
        out.write(f'pub static CONJUGATING_ELEM_{idx}_DENOM: Lazy<Ibz> = Lazy::new(|| ibz("{denom}"));\n')
        for k, c in enumerate(coords):
            out.write(f'pub static CONJUGATING_ELEM_{idx}_COORD_{k}: Lazy<Ibz> = Lazy::new(|| ibz("{c}"));\n')
        out.write('\n')

print(f'  wrote quaternion_data.rs')


# ============================================================
# 4. ec_params.rs (basic curve parameters)
# ============================================================
print('\n--- Generating ec_params.rs ---')

cofactor = (p + _sage_const_1 ) // (_sage_const_1  << f)

with open(os.path.join(output_dir, 'ec_params.rs'), 'w') as out:
    out.write('//! Elliptic curve parameters.\n')
    out.write('//!\n')
    out.write('//! Generated by SageMath precompute scripts. DO NOT EDIT.\n\n')
    out.write(f'/// Exponent f such that the torsion subgroup is `Z/2^f x Z/2^f`.\n')
    out.write(f'pub const TORSION_EVEN_POWER: u32 = {f};\n\n')
    out.write(f'/// Bit-length of the odd cofactor `(p+1) / 2^f`.\n')
    out.write(f'pub const P_COFACTOR_FOR_2F_BITLENGTH: u32 = {int(cofactor).bit_length()};\n\n')
    out.write(f'/// The odd cofactor `(p+1) / 2^f` as 64-bit limbs (little-endian).\n')

    # Compute limbs
    val = int(cofactor)
    limbs = []
    while val > _sage_const_0 :
        limbs.append(val & _sage_const_0xFFFFFFFFFFFFFFFF )
        val >>= _sage_const_64 
    if not limbs:
        limbs = [_sage_const_0 ]

    formatted_limbs = ', '.join(f'0x{l:x}' for l in limbs)
    out.write(f'pub const P_COFACTOR_FOR_2F: &[u64] = &[{formatted_limbs}];\n')

print(f'  wrote ec_params.rs')


# ============================================================
# 5. hd_splitting_transforms.rs
# ============================================================
print('\n--- Generating hd_splitting_transforms.rs ---')

# These are level-independent (same for all levels), so just copy the existing data
# Actually, let me check the C source to confirm

# The hd_splitting_transforms.c files are identical across levels
# So we can just generate them once
# The data is in the existing level1.rs already — we just need it in the new module structure

os.chdir(orig_dir)
print(f'  hd_splitting_transforms are level-independent (already in level1.rs)')

print(f'\n=== Done generating constants for level {level} ===')

