#!/usr/bin/env python3
"""
Parse C precomputed constant files that contain fp_t and ibz_t values
(endomorphism_action.c, e0_basis.c) and output Rust source.

These files can't be regenerated from Sage scripts because they require
the deuring2d library. Instead, we parse the C output directly.

We extract:
- fp_t limb arrays from RADIX=64 non-broadwell blocks
- ibz_t values from GMP_LIMB_BITS=64 blocks

Usage: python3 parse_fp_constants.py <level>
"""

import re
import sys
import os


def extract_radix64_fp_limbs(content):
    """Extract all fp_t limb arrays from RADIX=64 non-broadwell blocks.

    Returns a list of lists of hex string limbs.
    """
    lines = content.split('\n')
    results = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if 'RADIX == 64' in line:
            i += 1
            if i < len(lines) and 'SQISIGN_GF_IMPL_BROADWELL' in lines[i]:
                # Skip broadwell block to #else
                while i < len(lines) and '#else' not in lines[i]:
                    i += 1
                i += 1  # skip #else
                if i < len(lines):
                    m = re.search(r'\{([^}]+)\}', lines[i])
                    if m:
                        limbs = [l.strip() for l in m.group(1).split(',')]
                        results.append(limbs)
            # Skip to #endif
            while i < len(lines) and '#endif' not in lines[i]:
                i += 1
        i += 1
    return results


def extract_gmp64_ibz_values(content):
    """Extract all ibz_t values from GMP_LIMB_BITS=64 blocks.

    Returns a list of (mp_size, [limb_hex_strings]) tuples.
    """
    lines = content.split('\n')
    results = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if 'GMP_LIMB_BITS == 64' in line:
            i += 1
            if i < len(lines):
                val_line = lines[i].strip()
                size_m = re.search(r'_mp_size\s*=\s*(-?\d+)', val_line)
                limbs_m = re.search(r'_mp_d\s*=\s*\(mp_limb_t\[\]\)\s*\{([^}]+)\}', val_line)
                if size_m and limbs_m:
                    mp_size = int(size_m.group(1))
                    limbs = [l.strip() for l in limbs_m.group(1).split(',')]
                    results.append((mp_size, limbs))
        i += 1
    return results


def gmp_limbs_to_decimal(mp_size, limbs):
    """Convert GMP 64-bit limbs to a decimal string."""
    if mp_size == 0:
        return "0"
    value = 0
    n = abs(mp_size)
    for i in range(n):
        limb = int(limbs[i], 0)
        value += limb << (64 * i)
    if mp_size < 0:
        return f"-{value}"
    return str(value)


def generate_endomorphism_action_rs(c_filepath, out_filepath, level, nwords):
    """Parse endomorphism_action.c and generate Rust source.

    The C struct is:
    typedef struct curve_with_endomorphism_ring {
        ec_curve_t curve;           // A (fp2), C (fp2), A24 (fp2), is_A24_computed
        ec_basis_t basis_even;      // 3 points, each (x: fp2, z: fp2)
        ibz_mat_2x2_t action_i, action_j, action_k;    // each 2x2 of ibz_t
        ibz_mat_2x2_t action_gen2, action_gen3, action_gen4;
    } curve_with_endomorphism_ring_t;

    fp2_t = {fp_t re, fp_t im}
    ec_curve_t = {fp2_t A, fp2_t C, ec_point_t A24, bool is_A24_computed_and_normalized}
    ec_point_t = {fp2_t x, fp2_t z}
    ec_basis_t = {ec_point_t P, ec_point_t Q, ec_point_t PmQ}
    """
    with open(c_filepath) as f:
        content = f.read()

    fp_values = extract_radix64_fp_limbs(content)
    ibz_values = extract_gmp64_ibz_values(content)

    # Count fp values per curve_with_endomorphism_ring_t:
    # curve: A(2 fp), C(2 fp), A24.x(2 fp), A24.z(2 fp) = 8 fp values
    # basis: P.x(2), P.z(2), Q.x(2), Q.z(2), PmQ.x(2), PmQ.z(2) = 12 fp values
    # Total per entry: 20 fp values
    fp_per_entry = 20
    num_entries = len(fp_values) // fp_per_entry

    # ibz_t values: 6 matrices of 2x2 = 24 ibz values per entry
    ibz_per_entry = 24

    assert len(fp_values) == num_entries * fp_per_entry, \
        f"Expected {num_entries * fp_per_entry} fp values, got {len(fp_values)}"
    assert len(ibz_values) == num_entries * ibz_per_entry, \
        f"Expected {num_entries * ibz_per_entry} ibz values, got {len(ibz_values)}"

    with open(out_filepath, 'w') as out:
        out.write('//! Endomorphism action precomputed data: curves with endomorphism rings.\n')
        out.write('//!\n')
        out.write('//! Contains curves, torsion bases, and endomorphism action matrices\n')
        out.write('//! for the standard and alternate starting curves.\n')
        out.write('//!\n')
        out.write('//! Fp elements are stored as Montgomery-form limb arrays.\n')
        out.write('//! Generated by parsing the C reference output. DO NOT EDIT.\n\n')
        out.write('use num_bigint::BigInt;\n')
        out.write('use once_cell::sync::Lazy;\n\n')
        out.write('type Ibz = BigInt;\n\n')
        out.write('fn ibz(s: &str) -> Ibz {\n')
        out.write('    s.parse::<Ibz>().unwrap()\n')
        out.write('}\n\n')
        out.write(f'pub const NWORDS_FIELD: usize = {nwords};\n')
        out.write(f'pub const NUM_CURVES_WITH_ENDOMORPHISMS: usize = {num_entries};\n\n')

        for entry_idx in range(num_entries):
            fp_base = entry_idx * fp_per_entry
            ibz_base = entry_idx * ibz_per_entry

            out.write(f'// ==== Curve {entry_idx} ====\n\n')

            # Curve: A.re, A.im, C.re, C.im, A24.x.re, A24.x.im, A24.z.re, A24.z.im
            fp_names = [
                ('CURVE_A_RE', 'Curve coefficient A, real part'),
                ('CURVE_A_IM', 'Curve coefficient A, imaginary part'),
                ('CURVE_C_RE', 'Curve coefficient C, real part'),
                ('CURVE_C_IM', 'Curve coefficient C, imaginary part'),
                ('CURVE_A24_X_RE', 'Curve A24 point, x-coordinate, real part'),
                ('CURVE_A24_X_IM', 'Curve A24 point, x-coordinate, imaginary part'),
                ('CURVE_A24_Z_RE', 'Curve A24 point, z-coordinate, real part'),
                ('CURVE_A24_Z_IM', 'Curve A24 point, z-coordinate, imaginary part'),
            ]
            for k, (name, doc) in enumerate(fp_names):
                limbs = fp_values[fp_base + k]
                formatted = ', '.join(limbs)
                out.write(f'/// {doc}\n')
                out.write(f'pub const ENDOMORPHISM_{entry_idx}_{name}: [u64; {nwords}] = [{formatted}];\n')

            out.write('\n')

            # Basis: P.x.re, P.x.im, P.z.re, P.z.im, Q.x.re, Q.x.im, Q.z.re, Q.z.im,
            #         PmQ.x.re, PmQ.x.im, PmQ.z.re, PmQ.z.im
            basis_names = [
                ('BASIS_P_X_RE', 'Basis P, x-coordinate, real part'),
                ('BASIS_P_X_IM', 'Basis P, x-coordinate, imaginary part'),
                ('BASIS_P_Z_RE', 'Basis P, z-coordinate, real part'),
                ('BASIS_P_Z_IM', 'Basis P, z-coordinate, imaginary part'),
                ('BASIS_Q_X_RE', 'Basis Q, x-coordinate, real part'),
                ('BASIS_Q_X_IM', 'Basis Q, x-coordinate, imaginary part'),
                ('BASIS_Q_Z_RE', 'Basis Q, z-coordinate, real part'),
                ('BASIS_Q_Z_IM', 'Basis Q, z-coordinate, imaginary part'),
                ('BASIS_PMQ_X_RE', 'Basis P-Q, x-coordinate, real part'),
                ('BASIS_PMQ_X_IM', 'Basis P-Q, x-coordinate, imaginary part'),
                ('BASIS_PMQ_Z_RE', 'Basis P-Q, z-coordinate, real part'),
                ('BASIS_PMQ_Z_IM', 'Basis P-Q, z-coordinate, imaginary part'),
            ]
            for k, (name, doc) in enumerate(basis_names):
                limbs = fp_values[fp_base + 8 + k]
                formatted = ', '.join(limbs)
                out.write(f'/// {doc}\n')
                out.write(f'pub const ENDOMORPHISM_{entry_idx}_{name}: [u64; {nwords}] = [{formatted}];\n')

            out.write('\n')

            # Action matrices: i, j, k, gen2, gen3, gen4
            matrix_names = ['ACTION_I', 'ACTION_J', 'ACTION_K',
                          'ACTION_GEN2', 'ACTION_GEN3', 'ACTION_GEN4']
            for mat_idx, mat_name in enumerate(matrix_names):
                # Each matrix is 2x2, stored column-major (transposed)
                # So entries are [0][0], [1][0], [0][1], [1][1]
                base = ibz_base + mat_idx * 4
                entries = []
                for k in range(4):
                    mp_size, limbs = ibz_values[base + k]
                    dec = gmp_limbs_to_decimal(mp_size, limbs)
                    entries.append(dec)
                out.write(f'/// {mat_name} matrix (column-major: [0][0], [1][0], [0][1], [1][1])\n')
                out.write(f'pub static ENDOMORPHISM_{entry_idx}_{mat_name}: [Lazy<Ibz>; 4] = [\n')
                for dec in entries:
                    out.write(f'    Lazy::new(|| ibz("{dec}")),\n')
                out.write(f'];\n')

            out.write('\n')

    print(f'  wrote {out_filepath} ({num_entries} curves, {len(fp_values)} fp values, {len(ibz_values)} ibz values)')


def generate_e0_basis_rs(c_filepath, out_filepath, level, nwords):
    """Parse e0_basis.c and generate Rust source.

    The C file contains fp_t arrays for the torsion basis point coordinates.
    """
    with open(c_filepath) as f:
        content = f.read()

    fp_values = extract_radix64_fp_limbs(content)

    # e0_basis.c contains fp2_t values for basis point x-coordinates:
    # BASIS_E0_PX = {fp_t re, fp_t im}  -> 2 fp values
    # BASIS_E0_QX = {fp_t re, fp_t im}  -> 2 fp values
    # Total: 4 fp values

    with open(out_filepath, 'w') as out:
        out.write('//! E0 torsion basis point coordinates.\n')
        out.write('//!\n')
        out.write('//! Fp elements are stored as Montgomery-form limb arrays.\n')
        out.write('//! Generated by parsing the C reference output. DO NOT EDIT.\n\n')
        out.write(f'pub const NWORDS_FIELD: usize = {nwords};\n\n')

        names = [
            'BASIS_E0_P_X_RE', 'BASIS_E0_P_X_IM',
            'BASIS_E0_Q_X_RE', 'BASIS_E0_Q_X_IM',
        ]

        assert len(fp_values) == len(names), \
            f"Expected {len(names)} fp values in e0_basis.c, got {len(fp_values)}"

        for i, name in enumerate(names):
            limbs = fp_values[i]
            formatted = ', '.join(limbs)
            out.write(f'pub const {name}: [u64; {nwords}] = [{formatted}];\n')

    print(f'  wrote {out_filepath} ({len(fp_values)} fp values)')


def main():
    if len(sys.argv) < 2:
        print('Usage: python3 parse_fp_constants.py <level>')
        sys.exit(1)

    level = int(sys.argv[1])

    nwords_map = {1: 5, 3: 7, 5: 9}
    nwords = nwords_map[level]

    ref_dir = f'reference/src/precomp/ref/lvl{level}'
    out_dir = f'crates/precomp/src/level{level}'

    # Parse endomorphism_action.c
    print(f'\n--- Parsing endomorphism_action.c for level {level} ---')
    generate_endomorphism_action_rs(
        f'{ref_dir}/endomorphism_action.c',
        f'{out_dir}/endomorphism_action.rs',
        level, nwords)

    # Parse e0_basis.c
    print(f'\n--- Parsing e0_basis.c for level {level} ---')
    generate_e0_basis_rs(
        f'{ref_dir}/e0_basis.c',
        f'{out_dir}/e0_basis.rs',
        level, nwords)


if __name__ == '__main__':
    main()
