#!/usr/bin/env python3
"""
Rust constant formatter for SQIsign precomputed constants.

Analogous to the C reference's cformat.py, but outputs Rust source code.
Called by the SageMath precompute scripts to generate Rust constant files.

BigInt (ibz_t) values are stored as decimal string literals and
constructed at init time via once_cell::sync::Lazy.

Fp elements (fp_t) are stored as [u64; N] limb arrays in Montgomery form.
"""
import sys
from math import ceil, floor, log
import sage.all


class Ibz:
    """A big integer value. Stored as a decimal string in the Rust output."""
    def __init__(self, v):
        self.v = int(v)

    def rust_literal(self):
        return f'ibz("{self.v}")'


class IbzMat2x2:
    """A 2x2 matrix of Ibz values."""
    def __init__(self, rows):
        # rows is [[Ibz, Ibz], [Ibz, Ibz]]
        self.rows = rows

    def rust_literal(self):
        r = self.rows
        return (f'ibz_mat_2x2(\n'
                f'        {r[0][0].rust_literal()}, {r[0][1].rust_literal()},\n'
                f'        {r[1][0].rust_literal()}, {r[1][1].rust_literal()},\n'
                f'    )')


class FpEl:
    """An Fp element in Montgomery form."""
    ref_p5248_radix_map  = { 16: 13, 32: 29, 64: 51 }
    ref_p65376_radix_map = { 16: 13, 32: 28, 64: 55 }
    ref_p27500_radix_map = { 16: 13, 32: 29, 64: 57 }

    def __init__(self, n, p, montgomery=True):
        self.n = n
        self.p = p
        self.montgomery = montgomery

    def __get_radix(self, word_size):
        # lvl1
        if self.p == 0x4ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff:
            return self.ref_p5248_radix_map[word_size]
        # lvl3
        elif self.p == 0x40ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff:
            return self.ref_p65376_radix_map[word_size]
        # lvl5
        elif self.p == 0x1afffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff:
            return self.ref_p27500_radix_map[word_size]
        raise ValueError(f'Invalid prime "{self.p}"')

    def get_limbs_64(self):
        """Return the 64-bit limb array for RADIX=64 ref (non-broadwell)."""
        radix = self.__get_radix(64)
        l = 1 + floor(log(self.p, 2**radix))
        if self.montgomery:
            R = 2**(radix * ceil(log(self.p, 2**radix)))
        else:
            R = 1
        el = (self.n * R) % self.p
        return [(int(el) >> radix*i) % 2**radix for i in range(l)]

    def rust_literal(self, nwords=None):
        limbs = self.get_limbs_64()
        if nwords is None:
            nwords = len(limbs)
        formatted = ', '.join(f'0x{v:x}' for v in limbs)
        return f'[{formatted}]'


def ibz_to_rust_static(name, ibz_val):
    """Generate a Rust lazy static for an ibz_t value."""
    return f'    pub static ref {name}: Ibz = ibz("{ibz_val.v}");'


def write_rust_header(f, module_doc):
    """Write standard Rust file header."""
    f.write(f'//! {module_doc}\n')
    f.write(f'//!\n')
    f.write(f'//! Generated by SageMath precompute scripts. DO NOT EDIT.\n\n')


def write_ibz_imports(f):
    """Write imports needed for ibz_t constants."""
    f.write('use num_bigint::BigInt;\n')
    f.write('use once_cell::sync::Lazy;\n\n')
    f.write('type Ibz = BigInt;\n\n')
    f.write('fn ibz(s: &str) -> Ibz {\n')
    f.write('    s.parse::<Ibz>().unwrap()\n')
    f.write('}\n\n')


# ---- High-level output functions ----

def generate_torsion_constants(p, outfile):
    """Generate torsion_constants.rs from the prime p."""
    f_val = (int(p) + 1).bit_length()
    # Actually compute f properly
    n = int(p) + 1
    f_val = 0
    while n % 2 == 0:
        f_val += 1
        n //= 2

    tors2part = 1 << f_val
    lambda_security = round(int(p).bit_length() / 128) * 64

    # next_prime(2^(4*lambda))
    from sage.all import next_prime
    N_sec = int(next_prime(1 << (4 * lambda_security)))
    N_com = N_sec

    with open(outfile, 'w') as out:
        write_rust_header(out, 'Torsion degree constants.')
        write_ibz_imports(out)

        out.write('lazy_static::lazy_static! {\n')
        out.write(f'    pub static ref TWO_TO_SECURITY_BITS: Ibz = ibz("{1 << lambda_security}");\n')
        out.write(f'    pub static ref TORSION_PLUS_2POWER: Ibz = ibz("{tors2part}");\n')
        out.write(f'    pub static ref SEC_DEGREE: Ibz = ibz("{N_sec}");\n')
        out.write(f'    pub static ref COM_DEGREE: Ibz = ibz("{N_com}");\n')
        out.write('}\n')

    print(f'  wrote {outfile}')


def generate_quaternion_constants(outfile, num_orders):
    """Generate quaternion_constants.rs."""
    with open(outfile, 'w') as out:
        write_rust_header(out, 'Quaternion algorithm parameters.')
        out.write(f'pub const QUAT_PRIMALITY_NUM_ITER: u32 = 32;\n')
        out.write(f'pub const QUAT_REPRES_BOUND_INPUT: u32 = 20;\n')
        out.write(f'pub const QUAT_EQUIV_BOUND_COEFF: i32 = 64;\n')
        out.write(f'pub const FINDUV_BOX_SIZE: u32 = 2;\n')
        out.write(f'pub const FINDUV_CUBE_SIZE: u32 = 624;\n')
        out.write(f'pub const NUM_EXTREMAL_ORDERS: usize = {num_orders};\n')
        out.write(f'pub const NUM_ALTERNATE_EXTREMAL_ORDERS: usize = {num_orders - 1};\n')

    print(f'  wrote {outfile}')


if __name__ == '__main__':
    print('rustformat.py: This module is meant to be imported, not run directly.')
    print('Use the precompute_*.sage scripts with --rust flag.')
