//!
//! Generated by SageMath precompute scripts. DO NOT EDIT.

/// Exponent f such that the torsion subgroup is ℤ/2ᶠ × ℤ/2ᶠ.
pub const TORSION_EVEN_POWER: u32 = 500;

/// Bit-length of the odd cofactor (p+1) / 2ᶠ.
pub const P_COFACTOR_FOR_2F_BITLENGTH: u32 = 5;

/// The odd cofactor (p+1) / 2ᶠ as 64-bit limbs (little-endian).
pub const P_COFACTOR_FOR_2F: &[u64] = &[0x1b];
